import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useForm, Controller } from 'react-hook-form';
import { useTranslation } from 'react-i18next';
import { ActionBar } from '../../../ui-kit/ActionBar';
import { Card, CardBody } from '../../../ui-kit/Card';
import { FieldWrapper, Input } from '../../../ui-kit/Field';
import { SearchableSelect } from '../../../ui-kit/SearchableSelect';
import { useToastStore } from '../../../store/toastStore';
import { getFieldErrorMessage } from '../../../app/api';
import { useFieldLabels } from '../../common/useFieldLabels';
import { useBranchesList } from '../../organization/branches/api';
import { useWarehousesList } from '../../inventory/warehouses/api';
import { useCreatePOSTerminal, useDeletePOSTerminal, usePOSTerminal, useUpdatePOSTerminal } from './api';

interface FormValues {
  code: string;
  nameAr: string;
  nameEn: string;
  branchId: number | '';
  defaultWarehouseId: number | '';
  isActive: boolean;
}

/** /pos/terminals/:id — screen مبدئي (05-Module-POS-Shifts.md, section 2.1). قاعدة 28: كل جهاز
 * تابع لفرع واحد دايمًا. */
export function POSTerminalEditPage() {
  const { t } = useTranslation();
  const { id } = useParams();
  const isNew = id === 'new';
  const terminalId = isNew ? undefined : Number(id);
  const navigate = useNavigate();
  const showToast = useToastStore((s) => s.show);

  const [isDeleted, setIsDeleted] = useState(false);
  const { data: terminal, isLoading } = usePOSTerminal(isDeleted ? undefined : terminalId);
  const { data: branches } = useBranchesList();
  const { data: warehouses } = useWarehousesList();
  const { label } = useFieldLabels('POS_TERMINALS');

  const { register, control, handleSubmit, reset } = useForm<FormValues>({
    defaultValues: { code: '', nameAr: '', nameEn: '', branchId: '', defaultWarehouseId: '', isActive: true }
  });

  useEffect(() => {
    if (terminal) {
      reset({
        code: terminal.code, nameAr: terminal.nameAr, nameEn: terminal.nameEn, branchId: terminal.branchId,
        defaultWarehouseId: terminal.defaultWarehouseId ?? '', isActive: terminal.isActive
      });
    }
  }, [terminal, reset]);

  const createMutation = useCreatePOSTerminal();
  const updateMutation = useUpdatePOSTerminal(terminalId ?? 0);
  const deleteMutation = useDeletePOSTerminal();

  const branchOptions = (branches ?? []).map((b) => ({ value: b.id, label: `${b.code} — ${b.nameAr}` }));
  const warehouseOptions = (warehouses ?? []).map((w) => ({ value: w.id, label: `${w.code} — ${w.nameAr}` }));

  const onSave = handleSubmit(async (values) => {
    const payload = {
      code: values.code || undefined, nameAr: values.nameAr, nameEn: values.nameEn, branchId: Number(values.branchId),
      defaultWarehouseId: values.defaultWarehouseId === '' ? undefined : Number(values.defaultWarehouseId), isActive: values.isActive
    };

    try {
      if (isNew) {
        const { id: newId } = await createMutation.mutateAsync(payload);
        showToast(t('posTerminals.createSuccess'), 'success');
        navigate(`/pos/terminals/${newId}`);
      } else {
        await updateMutation.mutateAsync(payload);
        showToast(t('posTerminals.updateSuccess'), 'success');
      }
    } catch (error) {
      const message = getFieldErrorMessage(error);
      if (message) showToast(message, 'error');
    }
  });

  const handleDelete = async () => {
    if (!terminalId) return;
    setIsDeleted(true);
    try {
      await deleteMutation.mutateAsync(terminalId);
      showToast(t('posTerminals.deleteSuccess'), 'success');
      navigate('/pos/terminals');
    } catch (error) {
      setIsDeleted(false);
      const message = getFieldErrorMessage(error);
      if (message) showToast(message, 'error');
    }
  };

  if (!isNew && isLoading) {
    return <div>{t('common.loading')}</div>;
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 16, minWidth: 0 }}>
      <h2 style={{ margin: 0 }}>{isNew ? t('posTerminals.addTerminal') : `${terminal?.code ?? ''} — ${terminal?.nameAr ?? ''}`}</h2>

      <ActionBar
        primary={{ key: 'save', label: isNew ? t('common.saveDraft') : t('common.saveChanges'), onClick: () => onSave() }}
        secondary={[{ key: 'back', label: t('common.back'), onClick: () => navigate('/pos/terminals') }]}
        destructive={
          !isNew
            ? [{ key: 'delete', label: t('common.remove'), onClick: handleDelete, confirmMessage: t('posTerminals.deleteConfirm') }]
            : []
        }
      />

      <form onSubmit={onSave}>
        <Card>
          <CardBody>
            <div style={{ display: 'flex', gap: 16, flexWrap: 'wrap' }}>
              <FieldWrapper label={label('code', t('posTerminals.code'))}>
                <Input placeholder={t('codingRules.autoGeneratedPlaceholder')} {...register('code')} />
              </FieldWrapper>
              <FieldWrapper label={label('nameAr', t('posTerminals.nameAr'))}>
                <Input {...register('nameAr')} />
              </FieldWrapper>
              <FieldWrapper label={label('nameEn', t('posTerminals.nameEn'))}>
                <Input {...register('nameEn')} />
              </FieldWrapper>
              <FieldWrapper label={label('branch', t('posTerminals.branch'))}>
                <Controller
                  control={control}
                  name="branchId"
                  render={({ field }) => (
                    <SearchableSelect style={{ minWidth: 200 }} value={field.value} onChange={(v) => field.onChange(v === '' ? '' : Number(v))} options={branchOptions} />
                  )}
                />
              </FieldWrapper>
              <FieldWrapper label={label('defaultWarehouse', t('posTerminals.defaultWarehouse'))}>
                <Controller
                  control={control}
                  name="defaultWarehouseId"
                  render={({ field }) => (
                    <SearchableSelect style={{ minWidth: 200 }} value={field.value} onChange={(v) => field.onChange(v === '' ? '' : Number(v))} options={warehouseOptions} />
                  )}
                />
              </FieldWrapper>
              {!isNew && (
                <FieldWrapper label={label('isActive', t('posTerminals.isActive'))}>
                  <label style={{ display: 'flex', alignItems: 'center', gap: 6, height: 38 }}>
                    <input type="checkbox" {...register('isActive')} />
                  </label>
                </FieldWrapper>
              )}
            </div>
          </CardBody>
        </Card>
      </form>
    </div>
  );
}
