using Habbak.ERP.Domain.Accounting;
using Habbak.ERP.Shared.Enums;

namespace Habbak.ERP.Application.Common.Models;

/// <summary>
/// Everything a calling module needs to provide to have IPostingService build and post a
/// balanced journal entry on its behalf (00-Project-Overview.md, section 11).
/// </summary>
public sealed class PostingRequest
{
    public required long CompanyId { get; init; }

    /// <summary>Direct, nullable — left null for company-wide entries (01-Module-Accounting.md, rule 25).</summary>
    public long? BranchId { get; init; }

    public required DateOnly EntryDate { get; init; }
    public required string Description { get; init; }
    public required SourceModule SourceModule { get; init; }
    public SourceDocumentType? SourceDocumentType { get; init; }
    public long? SourceDocumentId { get; init; }

    /// <summary>
    /// True for entries produced by another module's completed transaction (invoice, payroll...):
    /// they post directly to "مرحّل" without a Draft stop (rule 4 / section 4.1). False for the
    /// engine's own reversal entries, which are drafted for review (rule 16).
    /// </summary>
    public required bool IsAutoGenerated { get; init; }

    public long? ReversalOfEntryId { get; init; }

    /// <summary>Set by the template engine on every entry of one document posting; see JournalEntry.PostingGroupId.</summary>
    public Guid? PostingGroupId { get; init; }

    public required IReadOnlyList<PostingLineRequest> Lines { get; init; }
}

public sealed class PostingLineRequest
{
    public required long AccountId { get; init; }
    public required decimal DebitAmount { get; init; }
    public required decimal CreditAmount { get; init; }
    public required string CurrencyCode { get; init; }
    public required decimal ExchangeRate { get; init; }
    public required decimal BaseCurrencyDebitAmount { get; init; }
    public required decimal BaseCurrencyCreditAmount { get; init; }
    public string? Description { get; init; }

    /// <summary>CostCenterDimensionId -> CostCenterDimensionValueId chosen for this line.</summary>
    public IReadOnlyDictionary<long, long> DimensionValues { get; init; } =
        new Dictionary<long, long>();
}

/// <summary>
/// The journal entry is returned as a tracked (not-yet-saved) entity, not just an Id, so the
/// calling handler can wire navigation properties (e.g. voucher.JournalEntry = result.JournalEntry)
/// and commit everything in ONE SaveChangesAsync call — IPostingService never calls
/// SaveChangesAsync itself; atomicity with the source operation (rule 5) is the caller's
/// responsibility by design.
/// </summary>
public sealed class PostingResult
{
    public required JournalEntry JournalEntry { get; init; }
    public required JournalEntryStatus Status { get; init; }
    public long? ApprovalInstanceId { get; init; }
}
