namespace Habbak.ERP.Application.Sales.Settings.Dtos;

public sealed class SalesCycleSettingsDto
{
    public required string CycleType { get; init; }
    public required bool RequiresQuoteBeforeOrder { get; init; }
    public required bool RequiresOrderBeforeInvoice { get; init; }
    public required bool RequiresSeparateDeliveryDocument { get; init; }
    public required bool InvoiceBeforeDelivery { get; init; }
    public required bool AutoGenerateDownstreamDocuments { get; init; }
}
