using Habbak.ERP.Application.Accounting.JournalEntries.Dtos;
using Habbak.ERP.Application.Common.Interfaces;
using Habbak.ERP.Application.Common.Models;
using Habbak.ERP.Domain.Accounting;
using Habbak.ERP.Shared.Enums;
using MediatR;
using Microsoft.EntityFrameworkCore;

namespace Habbak.ERP.Application.Accounting.JournalEntries.Queries.GetJournalEntriesList;

/// <summary>
/// GetList (00-Frontend-Specs.md, section 6): CompanyId/BranchId filtering happens automatically
/// via the DbContext's Global Query Filter — never applied by hand here.
/// </summary>
public sealed class GetJournalEntriesListQuery : ListQuery, IRequest<PagedResult<JournalEntryListItemDto>>;

public sealed class GetJournalEntriesListQueryHandler(IApplicationDbContext db)
    : IRequestHandler<GetJournalEntriesListQuery, PagedResult<JournalEntryListItemDto>>
{
    public async Task<PagedResult<JournalEntryListItemDto>> Handle(
        GetJournalEntriesListQuery request, CancellationToken cancellationToken)
    {
        var query = db.JournalEntries.AsNoTracking().AsQueryable();

        if (!string.IsNullOrWhiteSpace(request.Search))
        {
            var term = request.Search.Trim();

            // Grid also shows Source/Status (enums) and Debit/Credit/Date columns — match those too,
            // not just EntryNumber/Description. Enum names are matched by substring (e.g. "post" -> Posted);
            // amount/date are matched by exact value since the grid formats them (commas, ISO date) rather
            // than storing display text.
            var matchingSourceModules = Enum.GetValues<SourceModule>()
                .Where(v => v.ToString().Contains(term, StringComparison.OrdinalIgnoreCase))
                .ToArray();
            var matchingStatuses = Enum.GetValues<JournalEntryStatus>()
                .Where(v => v.ToString().Contains(term, StringComparison.OrdinalIgnoreCase))
                .ToArray();
            decimal? amountTerm = decimal.TryParse(term.Replace(",", ""), out var parsedAmount) ? parsedAmount : null;
            DateOnly? dateTerm = DateOnly.TryParse(term, out var parsedDate) ? parsedDate : null;

            query = query.Where(j =>
                j.EntryNumber.Contains(term) ||
                j.Description.Contains(term) ||
                matchingSourceModules.Contains(j.SourceModule) ||
                matchingStatuses.Contains(j.Status) ||
                (amountTerm != null && (j.TotalDebit == amountTerm || j.TotalCredit == amountTerm)) ||
                (dateTerm != null && j.EntryDate == dateTerm));
        }

        var totalCount = await query.CountAsync(cancellationToken);

        var descending = string.Equals(request.SortDir, "desc", StringComparison.OrdinalIgnoreCase);
        query = request.SortBy switch
        {
            "entryDate" => descending ? query.OrderByDescending(j => j.EntryDate) : query.OrderBy(j => j.EntryDate),
            "totalDebit" => descending ? query.OrderByDescending(j => j.TotalDebit) : query.OrderBy(j => j.TotalDebit),
            "status" => descending ? query.OrderByDescending(j => j.Status) : query.OrderBy(j => j.Status),
            _ => descending ? query.OrderByDescending(j => j.EntryNumber) : query.OrderBy(j => j.EntryNumber)
        };

        var pageSize = request.PageSize is > 0 and <= 500 ? request.PageSize : 25;
        var page = request.Page > 0 ? request.Page : 1;

        var items = await query
            .Skip((page - 1) * pageSize)
            .Take(pageSize)
            .Select(j => new JournalEntryListItemDto
            {
                Id = j.Id,
                EntryNumber = j.EntryNumber,
                EntryDate = j.EntryDate,
                Description = j.Description,
                SourceModule = j.SourceModule.ToString(),
                IsAutoGenerated = j.IsAutoGenerated,
                TotalDebit = j.TotalDebit,
                TotalCredit = j.TotalCredit,
                Status = j.Status.ToString()
            })
            .ToListAsync(cancellationToken);

        return new PagedResult<JournalEntryListItemDto>
        {
            Items = items,
            TotalCount = totalCount,
            Page = page,
            PageSize = pageSize
        };
    }
}
