import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { ActionBar } from '../../../ui-kit/ActionBar';
import { Card, CardBody } from '../../../ui-kit/Card';
import { FieldWrapper, Input } from '../../../ui-kit/Field';
import { useToastStore } from '../../../store/toastStore';
import { getFieldErrorMessage } from '../../../app/api';
import { useCodingRule } from '../../settings/codingRules/api';
import { useCurrentCompany } from '../companies/api';
import { useBranchesList, useCreateBranch, useDeleteBranch, useUpdateBranch } from './api';

/** /accounting/branches/:id — Edit screen (standard List/Edit pattern, 00-Frontend-Specs.md, section 5-7). */
export function BranchEditPage() {
  const { t } = useTranslation();
  const { id } = useParams();
  const isNew = id === 'new';
  const branchId = isNew ? undefined : Number(id);
  const navigate = useNavigate();
  const showToast = useToastStore((s) => s.show);

  const { data: branches, isLoading } = useBranchesList();
  const branch = branches?.find((b) => b.id === branchId);
  const { data: codingRule } = useCodingRule('ORG_BRANCHES');
  const codeIsAutomatic = codingRule?.isAutomatic ?? false;
  // Branches stay filtered to the current company (session decision) — this field only
  // clarifies which company a branch belongs to, it isn't a free choice among all companies.
  const { data: currentCompany } = useCurrentCompany();

  const [code, setCode] = useState('');
  const [nameAr, setNameAr] = useState('');
  const [nameEn, setNameEn] = useState('');
  const [isActive, setIsActive] = useState(true);

  useEffect(() => {
    if (branch) {
      setNameAr(branch.nameAr);
      setNameEn(branch.nameEn);
      setIsActive(branch.isActive);
    }
  }, [branch]);

  const createMutation = useCreateBranch();
  const updateMutation = useUpdateBranch(branchId ?? 0);
  const deleteMutation = useDeleteBranch();

  const handleSave = async () => {
    try {
      if (isNew) {
        const { id: newId } = await createMutation.mutateAsync({ code: codeIsAutomatic ? undefined : code, nameAr, nameEn });
        showToast(t('branches.createSuccess'), 'success');
        navigate(`/accounting/branches/${newId}`);
      } else {
        await updateMutation.mutateAsync({ nameAr, nameEn, isActive });
        showToast(t('branches.updateSuccess'), 'success');
      }
    } catch (error) {
      const message = getFieldErrorMessage(error);
      if (message) showToast(message, 'error');
    }
  };

  const handleDelete = async () => {
    if (!branchId) return;
    try {
      await deleteMutation.mutateAsync(branchId);
      showToast(t('branches.deleteSuccess'), 'success');
      navigate('/accounting/branches');
    } catch (error) {
      const message = getFieldErrorMessage(error);
      if (message) showToast(message, 'error');
    }
  };

  if (!isNew && isLoading) {
    return <div>{t('common.loading')}</div>;
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 16, maxWidth: 640 }}>
      <h2 style={{ margin: 0 }}>{isNew ? t('branches.addBranch') : `${t('branches.title')} — ${branch?.code ?? ''}`}</h2>

      <ActionBar
        primary={{ key: 'save', label: isNew ? t('common.saveDraft') : t('common.saveChanges'), onClick: handleSave }}
        secondary={[{ key: 'back', label: t('common.back'), onClick: () => navigate('/accounting/branches') }]}
        destructive={
          !isNew
            ? [{ key: 'delete', label: t('common.remove'), onClick: handleDelete, confirmMessage: t('branches.deleteConfirm') }]
            : []
        }
      />

      <Card>
        <CardBody>
          <div style={{ display: 'flex', gap: 16, flexWrap: 'wrap' }}>
            <FieldWrapper label={t('branches.company')}>
              <Input value={currentCompany ? `${currentCompany.code} - ${currentCompany.nameAr}` : ''} disabled style={{ minWidth: 200 }} />
            </FieldWrapper>

            <FieldWrapper label={t('branches.code')}>
              {codeIsAutomatic ? (
                <Input value={isNew ? t('codingRules.autoGeneratedPlaceholder') : (branch?.code ?? '')} disabled />
              ) : (
                <Input value={isNew ? code : (branch?.code ?? '')} onChange={(e) => setCode(e.target.value)} disabled={!isNew} />
              )}
            </FieldWrapper>

            <FieldWrapper label={t('branches.nameAr')}>
              <Input value={nameAr} onChange={(e) => setNameAr(e.target.value)} style={{ minWidth: 200 }} />
            </FieldWrapper>

            <FieldWrapper label={t('branches.nameEn')}>
              <Input value={nameEn} onChange={(e) => setNameEn(e.target.value)} style={{ minWidth: 200 }} />
            </FieldWrapper>

            {!isNew && (
              <FieldWrapper label={t('branches.isActive')}>
                <label style={{ display: 'flex', alignItems: 'center', gap: 6, height: 38 }}>
                  <input type="checkbox" checked={isActive} onChange={(e) => setIsActive(e.target.checked)} />
                </label>
              </FieldWrapper>
            )}
          </div>
        </CardBody>
      </Card>
    </div>
  );
}
