using Habbak.ERP.Domain.Common;
using Habbak.ERP.Shared.Enums;

namespace Habbak.ERP.Domain.Accounting;

/// <summary>
/// القيد اليومي (01-Module-Accounting.md, section 2.2).
/// </summary>
public class JournalEntry : AuditableEntity, ICompanyScopedEntity, IBranchScopedEntity
{
    public Guid? PublicId { get; set; }
    public long? CompanyId { get; set; }

    /// <summary>
    /// Direct, nullable column: set for entries produced by a branch-specific operation
    /// (POS/automated sales entries), left null for company-wide entries (capital, loans...).
    /// Never inferred from an analytical dimension (rule 25).
    /// </summary>
    public long? BranchId { get; set; }

    /// <summary>Yearly sequence, unique per company.</summary>
    public string EntryNumber { get; set; } = default!;

    public DateOnly EntryDate { get; set; }
    public string Description { get; set; } = default!;
    public SourceModule SourceModule { get; set; }

    /// <summary>Polymorphic reference to the source document when the entry is automated.</summary>
    public SourceDocumentType? SourceDocumentType { get; set; }
    public long? SourceDocumentId { get; set; }

    public JournalEntryStatus Status { get; set; } = JournalEntryStatus.Draft;

    /// <summary>Automated entries can never be edited/deleted manually (rule 4).</summary>
    public bool IsAutoGenerated { get; set; }

    /// <summary>Self-reference: this entry reverses a previously posted one.</summary>
    public long? ReversalOfEntryId { get; set; }

    /// <summary>
    /// Shared by every entry one document posting produced through its templates (a sale's revenue
    /// entry and its cost-of-sales entry): they are read, and reversed, together. Null for entries
    /// made any other way.
    /// </summary>
    public Guid? PostingGroupId { get; set; }
    public JournalEntry? ReversalOfEntry { get; set; }

    public decimal TotalDebit { get; set; }
    public decimal TotalCredit { get; set; }

    public long? ApprovalInstanceId { get; set; }

    public DateTime? PostedAtUtc { get; set; }
    public long? PostedBy { get; set; }

    public ICollection<JournalEntryLine> Lines { get; set; } = new List<JournalEntryLine>();
}
