using Habbak.ERP.Application.Common.Exceptions;
using Habbak.ERP.Application.Common.Interfaces;
using Habbak.ERP.Application.Common.Models;
using Habbak.ERP.Domain.Accounting;
using Habbak.ERP.Infrastructure.Persistence;
using Habbak.ERP.Shared.Enums;
using Microsoft.EntityFrameworkCore;

namespace Habbak.ERP.Infrastructure.Services;

/// <summary>
/// Concrete implementation of IPostingService (00-Project-Overview.md, section 11), hosted here
/// — rather than in Application — because it needs direct EF Core access to share the same
/// change tracker/transaction as the calling command handler (01-Module-Accounting.md, rule 5).
/// </summary>
public class PostingService(
    AppDbContext db,
    IApprovalWorkflowService approvalWorkflowService,
    IJournalEntryNumberGenerator entryNumberGenerator,
    ICurrentCompanyContext? currentCompanyContext = null) : IPostingService
{
    public async Task<PostingResult> PostAsync(PostingRequest request, CancellationToken cancellationToken = default)
    {
        var linesForValidation = request.Lines
            .Select(l => new LineForValidation(l.AccountId, l.DebitAmount, l.CreditAmount, l.DimensionValues))
            .ToList();

        var resolvedLineDimensions = await ValidateAndThrowAsync(
            request.CompanyId, request.BranchId, request.EntryDate, linesForValidation, cancellationToken);

        var entryNumber = await entryNumberGenerator.GenerateAsync(request.CompanyId, request.EntryDate.Year, cancellationToken);

        var entry = new JournalEntry
        {
            CompanyId = request.CompanyId,
            BranchId = request.BranchId,
            EntryNumber = entryNumber,
            EntryDate = request.EntryDate,
            Description = request.Description,
            SourceModule = request.SourceModule,
            SourceDocumentType = request.SourceDocumentType,
            SourceDocumentId = request.SourceDocumentId,
            IsAutoGenerated = request.IsAutoGenerated,
            ReversalOfEntryId = request.ReversalOfEntryId,
            PostingGroupId = request.PostingGroupId,
            TotalDebit = request.Lines.Sum(l => l.DebitAmount),
            TotalCredit = request.Lines.Sum(l => l.CreditAmount),
            Status = JournalEntryStatus.Draft
        };

        var lineNumber = 1;
        for (var i = 0; i < request.Lines.Count; i++)
        {
            var lineRequest = request.Lines[i];
            var line = new JournalEntryLine
            {
                LineNumber = lineNumber++,
                AccountId = lineRequest.AccountId,
                DebitAmount = lineRequest.DebitAmount,
                CreditAmount = lineRequest.CreditAmount,
                CurrencyCode = lineRequest.CurrencyCode,
                ExchangeRate = lineRequest.ExchangeRate,
                BaseCurrencyDebitAmount = lineRequest.BaseCurrencyDebitAmount,
                BaseCurrencyCreditAmount = lineRequest.BaseCurrencyCreditAmount,
                Description = lineRequest.Description
            };

            // resolvedLineDimensions[i] carries the caller-supplied values plus any mandatory
            // Branch dimension ValidateAndThrowAsync auto-resolved from request.BranchId (Bug-001)
            // — using it here (not lineRequest.DimensionValues) is what makes the resolved value
            // actually persist on the line, not just pass validation.
            foreach (var (dimensionId, valueId) in resolvedLineDimensions[i])
            {
                line.DimensionValues.Add(new JournalEntryLineDimensionValue
                {
                    CostCenterDimensionId = dimensionId,
                    CostCenterDimensionValueId = valueId
                });
            }

            entry.Lines.Add(line);
        }

        db.JournalEntries.Add(entry);

        return await FinalizePostingAsync(entry, cancellationToken);
    }

    public async Task<PostingResult> PostDraftEntryAsync(long journalEntryId, CancellationToken cancellationToken = default)
    {
        var entry = await db.JournalEntries
            .Include(j => j.Lines)
                .ThenInclude(l => l.DimensionValues)
            .FirstOrDefaultAsync(j => j.Id == journalEntryId, cancellationToken)
            ?? throw new InvalidOperationException($"Journal entry {journalEntryId} was not found.");

        if (entry.Status != JournalEntryStatus.Draft)
        {
            throw new InvalidOperationException(
                $"Journal entry {journalEntryId} is not in Draft status (current: {entry.Status}) — only a Draft entry can be posted.");
        }

        var linesForValidation = entry.Lines
            .Select(l => new LineForValidation(
                l.AccountId,
                l.DebitAmount,
                l.CreditAmount,
                l.DimensionValues.ToDictionary(v => v.CostCenterDimensionId, v => v.CostCenterDimensionValueId)))
            .ToList();

        var resolvedLineDimensions = await ValidateAndThrowAsync(
            entry.CompanyId!.Value, entry.BranchId, entry.EntryDate, linesForValidation, cancellationToken);

        // Persist any mandatory Branch dimension ValidateAndThrowAsync auto-resolved (Bug-001) onto
        // this already-persisted draft entry's lines — SaveChangesAsync remains the caller's job.
        var entryLines = entry.Lines.ToList();
        for (var i = 0; i < entryLines.Count; i++)
        {
            var existingDimensionIds = entryLines[i].DimensionValues.Select(v => v.CostCenterDimensionId).ToHashSet();
            foreach (var (dimensionId, valueId) in resolvedLineDimensions[i])
            {
                if (existingDimensionIds.Add(dimensionId))
                {
                    entryLines[i].DimensionValues.Add(new JournalEntryLineDimensionValue
                    {
                        CostCenterDimensionId = dimensionId,
                        CostCenterDimensionValueId = valueId
                    });
                }
            }
        }

        return await FinalizePostingAsync(entry, cancellationToken);
    }

    public async Task<PostingResult> ReverseAsync(long journalEntryId, CancellationToken cancellationToken = default)
    {
        var original = await db.JournalEntries
            .Include(j => j.Lines)
                .ThenInclude(l => l.DimensionValues)
            .FirstOrDefaultAsync(j => j.Id == journalEntryId, cancellationToken)
            ?? throw new InvalidOperationException($"Journal entry {journalEntryId} was not found.");

        if (original.Status != JournalEntryStatus.Posted)
        {
            throw new InvalidOperationException("لا يمكن عكس قيد غير مرحّل — القيد لازم يكون في حالة (مرحّل) أولاً.");
        }

        var reversalDate = DateOnly.FromDateTime(DateTime.UtcNow);
        var entryNumber = await entryNumberGenerator.GenerateAsync(original.CompanyId!.Value, reversalDate.Year, cancellationToken);

        // Rule 16: keep the original description, append the standard reversal suffix; never
        // left blank or freely retyped.
        var reversal = new JournalEntry
        {
            CompanyId = original.CompanyId,
            BranchId = original.BranchId,
            EntryNumber = entryNumber,
            EntryDate = reversalDate,
            Description = $"{original.Description} — عكس قيد رقم {original.EntryNumber}",
            SourceModule = SourceModule.Manual,
            IsAutoGenerated = false,
            ReversalOfEntryId = original.Id,
            TotalDebit = original.TotalCredit,
            TotalCredit = original.TotalDebit,
            // Created as Draft, pending an explicit posting action — matches the reference
            // mockup's reversal flow, not posted automatically.
            Status = JournalEntryStatus.Draft
        };

        var lineNumber = 1;
        foreach (var originalLine in original.Lines)
        {
            var mirroredLine = new JournalEntryLine
            {
                LineNumber = lineNumber++,
                AccountId = originalLine.AccountId,
                DebitAmount = originalLine.CreditAmount,
                CreditAmount = originalLine.DebitAmount,
                CurrencyCode = originalLine.CurrencyCode,
                ExchangeRate = originalLine.ExchangeRate,
                BaseCurrencyDebitAmount = originalLine.BaseCurrencyCreditAmount,
                BaseCurrencyCreditAmount = originalLine.BaseCurrencyDebitAmount,
                Description = originalLine.Description
            };

            foreach (var dimensionValue in originalLine.DimensionValues)
            {
                mirroredLine.DimensionValues.Add(new JournalEntryLineDimensionValue
                {
                    CostCenterDimensionId = dimensionValue.CostCenterDimensionId,
                    CostCenterDimensionValueId = dimensionValue.CostCenterDimensionValueId
                });
            }

            reversal.Lines.Add(mirroredLine);
        }

        db.JournalEntries.Add(reversal);

        return new PostingResult
        {
            JournalEntry = reversal,
            Status = JournalEntryStatus.Draft,
            ApprovalInstanceId = null
        };
    }

    /// <summary>
    /// Decides Posted vs. Draft-pending-approval (rule 11) for an entry that has already passed
    /// validation. Shared by PostAsync (new entry) and PostDraftEntryAsync (existing Draft).
    /// </summary>
    private async Task<PostingResult> FinalizePostingAsync(JournalEntry entry, CancellationToken cancellationToken)
    {
        // Auto-generated entries never wait for approval (00-Posting-Engine-Architecture.md, rules
        // 4 and 22): the invoice, voucher or shift behind them already went through its own approval
        // chain before it could post, so a second gate on the resulting entry is the same check twice.
        // Today's approval service is a stub that never starts a workflow, so this held only by
        // accident; the day a real one is plugged in, template postings must not start stalling.
        if (entry.IsAutoGenerated)
        {
            entry.Status = JournalEntryStatus.Posted;
            entry.PostedAtUtc = DateTime.UtcNow;
            entry.PostedBy = currentCompanyContext?.UserId ?? 0;
            return new PostingResult { JournalEntry = entry, Status = entry.Status, ApprovalInstanceId = null };
        }

        // Docs/Implementation/Phase-2-Research.md §3.1 / Phase-2-Final.md — the note this replaced
        // flagged that entry.Id is 0 for a brand-new entry from PostAsync (IPostingService never
        // calls SaveChangesAsync itself, so the caller's own commit is still pending). The real
        // ApprovalWorkflowService cannot correlate an ApprovalInstance against an Id that will
        // change under it, and forcing an extra SaveChangesAsync here to get a real Id would split
        // what today is one atomic commit (entry + the caller's own document) into two — a real
        // regression risk across every existing IPostingService caller, not something Phase 2's
        // scope covers. So a brand-new entry (PostAsync) always posts immediately regardless of any
        // ACCOUNTING_JOURNAL_ENTRIES assignment, same as before this phase; only PostDraftEntryAsync
        // (an already-saved entry, real Id) can actually be gated. No caller creates a Draft entry
        // and calls PostDraftEntryAsync separately today, so this is a documented scope limit, not
        // a regression.
        var approvalInstanceId = entry.Id == 0
            ? null
            : await approvalWorkflowService.TryStartApprovalAsync(
                new ApprovalWorkflowTrigger
                {
                    CompanyId = entry.CompanyId!.Value,
                    EntityType = "JournalEntry",
                    EntityId = entry.Id,
                    Amount = entry.TotalDebit,
                    RequestedByUserId = currentCompanyContext?.UserId ?? 0
                },
                cancellationToken);

        if (approvalInstanceId is not null)
        {
            entry.Status = JournalEntryStatus.Draft;
            entry.ApprovalInstanceId = approvalInstanceId;
        }
        else
        {
            entry.Status = JournalEntryStatus.Posted;
            entry.PostedAtUtc = DateTime.UtcNow;
            entry.PostedBy = currentCompanyContext?.UserId ?? 0;
        }

        return new PostingResult
        {
            JournalEntry = entry,
            Status = entry.Status,
            ApprovalInstanceId = approvalInstanceId
        };
    }

    private async Task<IReadOnlyList<IReadOnlyDictionary<long, long>>> ValidateAndThrowAsync(
        long companyId, long? branchId, DateOnly entryDate, IReadOnlyList<LineForValidation> lines, CancellationToken cancellationToken)
    {
        var errors = new List<PostingValidationError>();
        var resolvedLineDimensions = lines.Select(l => new Dictionary<long, long>(l.DimensionValues)).ToList();

        // Rule 1: the entry must balance.
        var totalDebit = lines.Sum(l => l.DebitAmount);
        var totalCredit = lines.Sum(l => l.CreditAmount);
        if (totalDebit != totalCredit)
        {
            errors.Add(new PostingValidationError(
                "ACC-R1-UNBALANCED",
                $"القيد غير متزن: إجمالي المدين {totalDebit} لا يساوي إجمالي الدائن {totalCredit}."));
        }

        var accountIds = lines.Select(l => l.AccountId).Distinct().ToList();
        var accounts = await db.Accounts
            .Include(a => a.DimensionLinks)
            .Where(a => accountIds.Contains(a.Id))
            .ToDictionaryAsync(a => a.Id, cancellationToken);

        var referencedValueIds = lines.SelectMany(l => l.DimensionValues.Values).Distinct().ToList();
        var dimensionValues = referencedValueIds.Count == 0
            ? []
            : await db.CostCenterDimensionValues
                .Where(v => referencedValueIds.Contains(v.Id))
                .ToDictionaryAsync(v => v.Id, cancellationToken);

        // Bug-001: a mandatory dimension backed by the Branches screen (LinkedEntityType.Branch —
        // the same mirror-by-Code convention as BranchDimensionSync/PostingEntityValueMapper) is
        // resolved from the document's own BranchId instead of forcing every caller to pass it in
        // by hand. Resolved once per request, not per line, since it only depends on branchId.
        var mandatoryDimensionIds = accounts.Values
            .SelectMany(a => a.DimensionLinks.Where(l => l.IsMandatory))
            .Select(l => l.CostCenterDimensionId)
            .Distinct()
            .ToList();

        var branchLinkedDimensionNames = mandatoryDimensionIds.Count == 0
            ? new Dictionary<long, string>()
            : await db.CostCenterDimensions
                .Where(d => mandatoryDimensionIds.Contains(d.Id) && d.LinkedEntityType == CostCenterLinkedEntityType.Branch && d.IsActive)
                .ToDictionaryAsync(d => d.Id, d => d.NameAr, cancellationToken);

        string? branchNameAr = null;
        var resolvedBranchDimensionValues = new Dictionary<long, long>();
        if (branchLinkedDimensionNames.Count > 0)
        {
            var branch = branchId is null
                ? null
                : await db.Branches
                    .Where(b => b.Id == branchId)
                    .Select(b => new { b.Code, b.NameAr })
                    .FirstOrDefaultAsync(cancellationToken);
            branchNameAr = branch?.NameAr;

            if (branch is not null)
            {
                var branchLinkedDimensionIds = branchLinkedDimensionNames.Keys.ToList();
                resolvedBranchDimensionValues = await db.CostCenterDimensionValues
                    .Where(v => branchLinkedDimensionIds.Contains(v.CostCenterDimensionId) && v.Code == branch.Code && v.IsActive)
                    .ToDictionaryAsync(v => v.CostCenterDimensionId, v => v.Id, cancellationToken);
            }
        }

        for (var lineIndex = 0; lineIndex < lines.Count; lineIndex++)
        {
            var line = lines[lineIndex];

            if (!accounts.TryGetValue(line.AccountId, out var account))
            {
                errors.Add(new PostingValidationError(
                    "ACC-UNKNOWN-ACCOUNT", $"الحساب رقم {line.AccountId} غير موجود."));
                continue;
            }

            // Rule 2: grouping accounts never accept direct postings.
            if (!account.IsPostable)
            {
                errors.Add(new PostingValidationError(
                    "ACC-R2-NOT-POSTABLE",
                    $"الحساب '{account.NameAr}' حساب تجميعي ولا يقبل ترحيل قيود مباشرة عليه."));
            }

            // Rule 3: every dimension marked mandatory on this account must have a value on the line.
            foreach (var link in account.DimensionLinks.Where(l => l.IsMandatory))
            {
                if (line.DimensionValues.ContainsKey(link.CostCenterDimensionId))
                {
                    continue;
                }

                if (!branchLinkedDimensionNames.TryGetValue(link.CostCenterDimensionId, out var dimensionName))
                {
                    errors.Add(new PostingValidationError(
                        "ACC-R3-MISSING-DIMENSION",
                        $"الحساب '{account.NameAr}' يتطلب تحديد قيمة للبُعد الإلزامي رقم {link.CostCenterDimensionId}."));
                }
                else if (branchId is null)
                {
                    errors.Add(new PostingValidationError(
                        "ACC-R3-NO-BRANCH-ON-DOCUMENT",
                        $"الحساب '{account.NameAr}' يتطلب تحديد قيمة لبُعد '{dimensionName}' الإلزامي — لكن هذا المستند غير مرتبط بفرع."));
                }
                else if (resolvedBranchDimensionValues.TryGetValue(link.CostCenterDimensionId, out var resolvedValueId))
                {
                    resolvedLineDimensions[lineIndex][link.CostCenterDimensionId] = resolvedValueId;
                }
                else
                {
                    errors.Add(new PostingValidationError(
                        "ACC-R3-BRANCH-DIMENSION-UNRESOLVED",
                        $"الفرع '{branchNameAr}' مفيش له قيمة في بُعد '{dimensionName}' — كلم المدير المالي."));
                }
            }

            // Rule 21: a value must actually belong to the dimension it is declared under.
            foreach (var (dimensionId, valueId) in line.DimensionValues)
            {
                if (!dimensionValues.TryGetValue(valueId, out var value) || value.CostCenterDimensionId != dimensionId)
                {
                    errors.Add(new PostingValidationError(
                        "ACC-R21-DIMENSION-MISMATCH",
                        $"قيمة البُعد رقم {valueId} لا تنتمي للبُعد رقم {dimensionId}."));
                }
            }
        }

        // Rule 9: no posting into a closed period. Filtered explicitly by companyId in addition
        // to the DbContext's own Global Query Filter, per the Overview's second-line-of-defense
        // principle (section 3).
        var isClosedPeriod = await db.AccountingPeriods
            .AnyAsync(p => p.CompanyId == companyId
                && p.Status == AccountingPeriodStatus.Closed
                && p.PeriodStart <= entryDate
                && p.PeriodEnd >= entryDate,
                cancellationToken);

        if (isClosedPeriod)
        {
            errors.Add(new PostingValidationError(
                "ACC-R9-PERIOD-CLOSED",
                $"الفترة المالية التي يقع فيها تاريخ {entryDate:yyyy-MM-dd} مُقفلة — لا يمكن الترحيل عليها."));
        }

        if (errors.Count > 0)
        {
            throw new PostingValidationException(errors);
        }

        return resolvedLineDimensions;
    }

    private sealed record LineForValidation(
        long AccountId, decimal DebitAmount, decimal CreditAmount, IReadOnlyDictionary<long, long> DimensionValues);
}
