using FluentValidation;
using Habbak.ERP.Application.Common;
using Habbak.ERP.Application.Common.Interfaces;
using Habbak.ERP.Domain.Accounting;
using Habbak.ERP.Shared.Enums;
using MediatR;

namespace Habbak.ERP.Application.Accounting.JournalEntries.Commands.CreateManualJournalEntry;

/// <summary>
/// Creates a manual journal entry as Draft (00-Frontend-Specs.md, section 7 — Create). No
/// posting-time business rules (balance, mandatory dimensions, open period — see
/// 01-Module-Accounting.md, section 3) are enforced here: an accountant can save a
/// work-in-progress draft freely. Those rules are enforced by IPostingService only once the
/// user actually attempts to post it (rule 1's wording is specifically about ترحيل/posting).
/// </summary>
public sealed record CreateManualJournalEntryCommand : IRequest<long>
{
    public long? BranchId { get; init; }
    public required DateOnly EntryDate { get; init; }
    public required string Description { get; init; }
    public required IReadOnlyList<JournalEntryLineInput> Lines { get; init; }
}

public sealed record JournalEntryLineInput
{
    public required long AccountId { get; init; }
    public required decimal DebitAmount { get; init; }
    public required decimal CreditAmount { get; init; }
    public required string CurrencyCode { get; init; }
    public required decimal ExchangeRate { get; init; }
    public required decimal BaseCurrencyDebitAmount { get; init; }
    public required decimal BaseCurrencyCreditAmount { get; init; }
    public string? Description { get; init; }
    public IReadOnlyDictionary<long, long> DimensionValues { get; init; } = new Dictionary<long, long>();
}

public sealed class CreateManualJournalEntryCommandValidator : AbstractValidator<CreateManualJournalEntryCommand>
{
    public CreateManualJournalEntryCommandValidator()
    {
        RuleFor(x => x.Description).NotEmpty().MaximumLength(500);
        RuleFor(x => x.EntryDate).NotEqual(default(DateOnly));

        // A balanced double-entry line needs at least two legs — rule 1 in
        // 01-Module-Accounting.md is about posting, but a single-line entry can never balance
        // regardless, so it is never a useful draft either.
        RuleFor(x => x.Lines).Must(lines => lines.Count >= 2)
            .WithMessage("القيد يحتاج سطرين على الأقل.");

        RuleForEach(x => x.Lines).ChildRules(line =>
        {
            line.RuleFor(l => l.AccountId).GreaterThan(0);
            line.RuleFor(l => l.CurrencyCode).NotEmpty().Length(3);
            line.RuleFor(l => l.ExchangeRate).GreaterThan(0);
            line.RuleFor(l => l.DebitAmount).GreaterThanOrEqualTo(0);
            line.RuleFor(l => l.CreditAmount).GreaterThanOrEqualTo(0);

            // Rule (JournalEntryLine, section 2.2): exactly one of Debit/Credit is > 0.
            line.RuleFor(l => l)
                .Must(l => (l.DebitAmount > 0) ^ (l.CreditAmount > 0))
                .WithMessage("كل سطر لازم يحمل قيمة مدين أو دائن، وليس الاثنين معًا ولا صفر.")
                .WithName("Amount");
        });
    }
}

public sealed class CreateManualJournalEntryCommandHandler(
    IApplicationDbContext db,
    ICurrentCompanyContext currentCompanyContext,
    IJournalEntryNumberGenerator entryNumberGenerator)
    : IRequestHandler<CreateManualJournalEntryCommand, long>
{
    public async Task<long> Handle(CreateManualJournalEntryCommand request, CancellationToken cancellationToken)
    {
        var entryNumber = await entryNumberGenerator.GenerateAsync(
            currentCompanyContext.CompanyId, request.EntryDate.Year, cancellationToken);

        var entry = new JournalEntry
        {
            CompanyId = currentCompanyContext.CompanyId,
            BranchId = BranchRequirement.Resolve(request.BranchId, currentCompanyContext.BranchId),
            EntryNumber = entryNumber,
            EntryDate = request.EntryDate,
            Description = request.Description,
            SourceModule = SourceModule.Manual,
            IsAutoGenerated = false,
            Status = JournalEntryStatus.Draft,
            TotalDebit = request.Lines.Sum(l => l.DebitAmount),
            TotalCredit = request.Lines.Sum(l => l.CreditAmount)
        };

        var lineNumber = 1;
        foreach (var lineInput in request.Lines)
        {
            var line = new JournalEntryLine
            {
                LineNumber = lineNumber++,
                AccountId = lineInput.AccountId,
                DebitAmount = lineInput.DebitAmount,
                CreditAmount = lineInput.CreditAmount,
                CurrencyCode = lineInput.CurrencyCode,
                ExchangeRate = lineInput.ExchangeRate,
                BaseCurrencyDebitAmount = lineInput.BaseCurrencyDebitAmount,
                BaseCurrencyCreditAmount = lineInput.BaseCurrencyCreditAmount,
                Description = lineInput.Description
            };

            foreach (var (dimensionId, valueId) in lineInput.DimensionValues)
            {
                line.DimensionValues.Add(new JournalEntryLineDimensionValue
                {
                    CostCenterDimensionId = dimensionId,
                    CostCenterDimensionValueId = valueId
                });
            }

            entry.Lines.Add(line);
        }

        db.JournalEntries.Add(entry);
        await db.SaveChangesAsync(cancellationToken);

        return entry.Id;
    }
}
