import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useForm } from 'react-hook-form';
import { useTranslation } from 'react-i18next';
import { ActionBar } from '../../../ui-kit/ActionBar';
import { Card, CardBody } from '../../../ui-kit/Card';
import { FieldWrapper, Input } from '../../../ui-kit/Field';
import { useToastStore } from '../../../store/toastStore';
import { getFieldErrorMessage } from '../../../app/api';
import { useFieldLabels } from '../../common/useFieldLabels';
import { useCreateLoyaltyTier, useDeleteLoyaltyTier, useLoyaltyTier, useUpdateLoyaltyTier } from './api';

interface FormValues {
  code: string;
  nameAr: string;
  nameEn: string;
  displayOrder: string;
  minPointsThreshold: string;
  earnRateMultiplier: string;
  isActive: boolean;
}

/** /sales/loyalty-tiers/:id — screen #4 (04-Module-Sales.md, section 5). */
export function LoyaltyTierEditPage() {
  const { t } = useTranslation();
  const { id } = useParams();
  const isNew = id === 'new';
  const tierId = isNew ? undefined : Number(id);
  const navigate = useNavigate();
  const showToast = useToastStore((s) => s.show);

  const [isDeleted, setIsDeleted] = useState(false);
  const { data: tier, isLoading } = useLoyaltyTier(isDeleted ? undefined : tierId);
  const { label } = useFieldLabels('SALES_LOYALTY_TIERS');

  const { register, handleSubmit, reset } = useForm<FormValues>({
    defaultValues: { code: '', nameAr: '', nameEn: '', displayOrder: '0', minPointsThreshold: '0', earnRateMultiplier: '1', isActive: true }
  });

  useEffect(() => {
    if (tier) {
      reset({
        code: tier.code,
        nameAr: tier.nameAr,
        nameEn: tier.nameEn,
        displayOrder: tier.displayOrder.toString(),
        minPointsThreshold: tier.minPointsThreshold.toString(),
        earnRateMultiplier: tier.earnRateMultiplier.toString(),
        isActive: tier.isActive
      });
    }
  }, [tier, reset]);

  const createMutation = useCreateLoyaltyTier();
  const updateMutation = useUpdateLoyaltyTier(tierId ?? 0);
  const deleteMutation = useDeleteLoyaltyTier();

  const onSave = handleSubmit(async (values) => {
    const payload = {
      code: values.code || undefined,
      nameAr: values.nameAr,
      nameEn: values.nameEn,
      displayOrder: Number(values.displayOrder || 0),
      minPointsThreshold: Number(values.minPointsThreshold || 0),
      earnRateMultiplier: Number(values.earnRateMultiplier || 1),
      isActive: values.isActive
    };

    try {
      if (isNew) {
        const { id: newId } = await createMutation.mutateAsync(payload);
        showToast(t('loyaltyTiers.createSuccess'), 'success');
        navigate(`/sales/loyalty-tiers/${newId}`);
      } else {
        await updateMutation.mutateAsync(payload);
        showToast(t('loyaltyTiers.updateSuccess'), 'success');
      }
    } catch (error) {
      const message = getFieldErrorMessage(error);
      if (message) showToast(message, 'error');
    }
  });

  const handleDelete = async () => {
    if (!tierId) return;
    setIsDeleted(true);
    try {
      await deleteMutation.mutateAsync(tierId);
      showToast(t('loyaltyTiers.deleteSuccess'), 'success');
      navigate('/sales/loyalty-tiers');
    } catch (error) {
      setIsDeleted(false);
      const message = getFieldErrorMessage(error);
      if (message) showToast(message, 'error');
    }
  };

  if (!isNew && isLoading) {
    return <div>{t('common.loading')}</div>;
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 16, minWidth: 0 }}>
      <h2 style={{ margin: 0 }}>{isNew ? t('loyaltyTiers.addTier') : `${tier?.code ?? ''} — ${tier?.nameAr ?? ''}`}</h2>

      <ActionBar
        primary={{ key: 'save', label: isNew ? t('common.saveDraft') : t('common.saveChanges'), onClick: () => onSave() }}
        secondary={[{ key: 'back', label: t('common.back'), onClick: () => navigate('/sales/loyalty-tiers') }]}
        destructive={
          !isNew
            ? [{ key: 'delete', label: t('common.remove'), onClick: handleDelete, confirmMessage: t('loyaltyTiers.deleteConfirm') }]
            : []
        }
      />

      <form onSubmit={onSave}>
        <Card>
          <CardBody>
            <div style={{ display: 'flex', gap: 16, flexWrap: 'wrap' }}>
              <FieldWrapper label={label('code', t('loyaltyTiers.code'))}>
                <Input placeholder={t('codingRules.autoGeneratedPlaceholder')} {...register('code')} />
              </FieldWrapper>
              <FieldWrapper label={label('nameAr', t('loyaltyTiers.nameAr'))}>
                <Input {...register('nameAr')} />
              </FieldWrapper>
              <FieldWrapper label={label('nameEn', t('loyaltyTiers.nameEn'))}>
                <Input {...register('nameEn')} />
              </FieldWrapper>
              <FieldWrapper label={label('displayOrder', t('loyaltyTiers.displayOrder'))}>
                <Input type="number" style={{ width: 100 }} {...register('displayOrder')} />
              </FieldWrapper>
              <FieldWrapper label={label('minPointsThreshold', t('loyaltyTiers.minPointsThreshold'))}>
                <Input type="number" step="0.01" style={{ width: 140 }} {...register('minPointsThreshold')} />
              </FieldWrapper>
              <FieldWrapper label={label('earnRateMultiplier', t('loyaltyTiers.earnRateMultiplier'))}>
                <Input type="number" step="0.01" style={{ width: 120 }} {...register('earnRateMultiplier')} />
              </FieldWrapper>
              {!isNew && (
                <FieldWrapper label={label('isActive', t('loyaltyTiers.isActive'))}>
                  <label style={{ display: 'flex', alignItems: 'center', gap: 6, height: 38 }}>
                    <input type="checkbox" {...register('isActive')} />
                  </label>
                </FieldWrapper>
              )}
            </div>
          </CardBody>
        </Card>
      </form>
    </div>
  );
}
