using Habbak.ERP.Application.Common.Exceptions;
using Habbak.ERP.Application.Common.Interfaces;
using Habbak.ERP.Application.Common.Models;
using Habbak.ERP.Domain.Accounting;
using Habbak.ERP.Shared.Enums;
using MediatR;
using Microsoft.EntityFrameworkCore;

namespace Habbak.ERP.Application.Accounting.TreasuryTransfers.Commands.PostTreasuryTransfer;

/// <summary>
/// Posts a Draft transfer: builds its double-entry PostingRequest and posts it through the
/// central engine, in the SAME SaveChangesAsync call as the transfer's own status/JournalEntry
/// update — the same atomicity rule 5 requires for vouchers (01-Module-Accounting.md, rule 5).
/// </summary>
public sealed record PostTreasuryTransferCommand(long Id) : IRequest<PostTreasuryTransferResult>;

public sealed record PostTreasuryTransferResult(string Status, long? ApprovalInstanceId);

public sealed class PostTreasuryTransferCommandHandler(IApplicationDbContext db, IPostingService postingService)
    : IRequestHandler<PostTreasuryTransferCommand, PostTreasuryTransferResult>
{
    public async Task<PostTreasuryTransferResult> Handle(PostTreasuryTransferCommand request, CancellationToken cancellationToken)
    {
        var transfer = await db.TreasuryTransfers.FirstOrDefaultAsync(t => t.Id == request.Id, cancellationToken)
            ?? throw new NotFoundException(nameof(TreasuryTransfer), request.Id);

        if (transfer.Status != TreasuryTransferStatus.Draft)
        {
            throw new BusinessRuleException("ACC-TRANSFER-NOT-DRAFT", "لا يمكن ترحيل تحويل إلا وهو في حالة مسودة.");
        }

        var fromAccount = await db.Accounts.FirstAsync(a => a.Id == transfer.FromTreasuryAccountId, cancellationToken);
        var currencyCode = fromAccount.CurrencyCode ?? "EGP";

        var postingRequest = new PostingRequest
        {
            CompanyId = transfer.CompanyId!.Value,
            BranchId = transfer.BranchId,
            EntryDate = transfer.TransferDate,
            Description = $"تحويل بين الخزائن/البنوك رقم {transfer.Id}" + (string.IsNullOrWhiteSpace(transfer.Notes) ? "" : $" - {transfer.Notes}"),
            SourceModule = SourceModule.Manual,
            SourceDocumentType = SourceDocumentType.TreasuryTransfer,
            SourceDocumentId = transfer.Id,
            // Rule 5: this entry is a direct, automatic consequence of posting the transfer — not
            // separately user-editable afterward, matching every other IsAutoGenerated entry.
            IsAutoGenerated = true,
            Lines =
            [
                new PostingLineRequest
                {
                    AccountId = transfer.ToTreasuryAccountId,
                    DebitAmount = transfer.Amount,
                    CreditAmount = 0m,
                    CurrencyCode = currencyCode,
                    ExchangeRate = 1m,
                    BaseCurrencyDebitAmount = transfer.Amount,
                    BaseCurrencyCreditAmount = 0m
                },
                new PostingLineRequest
                {
                    AccountId = transfer.FromTreasuryAccountId,
                    DebitAmount = 0m,
                    CreditAmount = transfer.Amount,
                    CurrencyCode = currencyCode,
                    ExchangeRate = 1m,
                    BaseCurrencyDebitAmount = 0m,
                    BaseCurrencyCreditAmount = transfer.Amount
                }
            ]
        };

        var result = await postingService.PostAsync(postingRequest, cancellationToken);

        // Navigation-property fixup: JournalEntry.Id may not exist yet (not saved), but EF Core
        // resolves the FK automatically at SaveChanges — see IPostingService's XML doc.
        transfer.JournalEntry = result.JournalEntry;
        transfer.Status = result.Status == JournalEntryStatus.Posted ? TreasuryTransferStatus.Posted : TreasuryTransferStatus.Draft;

        await db.SaveChangesAsync(cancellationToken);

        return new PostTreasuryTransferResult(transfer.Status.ToString(), result.ApprovalInstanceId);
    }
}
