using Habbak.ERP.Application.Common.Exceptions;
using Habbak.ERP.Application.Common.Interfaces;
using Habbak.ERP.Application.Common.Models;
using Habbak.ERP.Domain.Accounting;
using Habbak.ERP.Shared.Enums;
using MediatR;
using Microsoft.EntityFrameworkCore;

namespace Habbak.ERP.Application.Accounting.AccountOpeningBalances.Commands.PostAccountOpeningBalanceBatch;

/// <summary>
/// Posts a Draft batch: each line becomes a Debit or Credit journal line depending on its own
/// Account.Nature (rule from 3.9's "طبيعة الحساب تظهر تلقائياً"), then IPostingService.PostAsync
/// builds and posts the entry in the SAME SaveChangesAsync call as this batch's own status update
/// (atomicity, mirroring PostVoucherCommand). IPostingService's own validation already rejects an
/// unbalanced set of lines (rule 3.9's "التحقق من توازن الأرصدة قبل الحفظ") and a closed period —
/// no separate balance check is hand-rolled here.
/// </summary>
public sealed record PostAccountOpeningBalanceBatchCommand(long Id) : IRequest;

public sealed class PostAccountOpeningBalanceBatchCommandHandler(
    IApplicationDbContext db, IPostingService postingService, ICurrentCompanyContext currentCompanyContext)
    : IRequestHandler<PostAccountOpeningBalanceBatchCommand>
{
    public async Task Handle(PostAccountOpeningBalanceBatchCommand request, CancellationToken cancellationToken)
    {
        var batch = await db.AccountOpeningBalanceBatches
            .Include(b => b.Lines).ThenInclude(l => l.Account)
            .FirstOrDefaultAsync(b => b.Id == request.Id, cancellationToken)
            ?? throw new NotFoundException(nameof(AccountOpeningBalanceBatch), request.Id);

        if (batch.Status != AccountOpeningBalanceStatus.Draft)
        {
            throw new BusinessRuleException("ACC-OPENING-BALANCE-NOT-DRAFT", "لا يمكن ترحيل قيد الأرصدة الافتتاحية إلا وهو في حالة مسودة.");
        }

        var postingRequest = new PostingRequest
        {
            CompanyId = currentCompanyContext.CompanyId,
            EntryDate = batch.TransactionDate,
            Description = $"قيد افتتاحي رقم {batch.BatchNumber}" + (string.IsNullOrWhiteSpace(batch.Notes) ? "" : $" - {batch.Notes}"),
            SourceModule = SourceModule.Manual,
            SourceDocumentType = SourceDocumentType.AccountOpeningBalance,
            SourceDocumentId = batch.Id,
            // Rule 5 style atomicity: this entry is a direct, automatic consequence of posting the
            // batch — not separately user-editable afterward, matching every other IsAutoGenerated entry.
            IsAutoGenerated = true,
            Lines = batch.Lines
                .OrderBy(l => l.LineNumber)
                .Select(l => new PostingLineRequest
                {
                    AccountId = l.AccountId,
                    DebitAmount = l.Account!.Nature == AccountNature.Debit ? l.Amount : 0m,
                    CreditAmount = l.Account!.Nature == AccountNature.Credit ? l.Amount : 0m,
                    CurrencyCode = l.Account!.CurrencyCode ?? "EGP",
                    ExchangeRate = 1,
                    BaseCurrencyDebitAmount = l.Account!.Nature == AccountNature.Debit ? l.Amount : 0m,
                    BaseCurrencyCreditAmount = l.Account!.Nature == AccountNature.Credit ? l.Amount : 0m,
                    Description = l.Notes
                })
                .ToList()
        };

        var result = await postingService.PostAsync(postingRequest, cancellationToken);

        batch.JournalEntry = result.JournalEntry;
        batch.Status = result.Status == JournalEntryStatus.Posted ? AccountOpeningBalanceStatus.Posted : AccountOpeningBalanceStatus.Draft;

        await db.SaveChangesAsync(cancellationToken);
    }
}
