using Habbak.ERP.Application.Accounting.JournalEntries.Dtos;
using Habbak.ERP.Application.Common.Exceptions;
using Habbak.ERP.Application.Common.Interfaces;
using Habbak.ERP.Domain.Accounting;
using MediatR;
using Microsoft.EntityFrameworkCore;

namespace Habbak.ERP.Application.Accounting.JournalEntries.Queries.GetJournalEntryById;

/// <summary>GET .../{id} (00-Frontend-Specs.md, section 7, step 1).</summary>
public sealed record GetJournalEntryByIdQuery(long Id) : IRequest<JournalEntryDetailDto>;

public sealed class GetJournalEntryByIdQueryHandler(IApplicationDbContext db)
    : IRequestHandler<GetJournalEntryByIdQuery, JournalEntryDetailDto>
{
    public async Task<JournalEntryDetailDto> Handle(GetJournalEntryByIdQuery request, CancellationToken cancellationToken)
    {
        var entry = await db.JournalEntries
            .Include(j => j.Lines)
                .ThenInclude(l => l.DimensionValues)
            .AsNoTracking()
            .FirstOrDefaultAsync(j => j.Id == request.Id, cancellationToken)
            ?? throw new NotFoundException(nameof(JournalEntry), request.Id);

        return new JournalEntryDetailDto
        {
            Id = entry.Id,
            PublicId = entry.PublicId,
            BranchId = entry.BranchId,
            EntryNumber = entry.EntryNumber,
            EntryDate = entry.EntryDate,
            Description = entry.Description,
            SourceModule = entry.SourceModule.ToString(),
            SourceDocumentType = entry.SourceDocumentType?.ToString(),
            SourceDocumentId = entry.SourceDocumentId,
            Status = entry.Status.ToString(),
            IsAutoGenerated = entry.IsAutoGenerated,
            ReversalOfEntryId = entry.ReversalOfEntryId,
            TotalDebit = entry.TotalDebit,
            TotalCredit = entry.TotalCredit,
            ApprovalInstanceId = entry.ApprovalInstanceId,
            PostedAtUtc = entry.PostedAtUtc,
            RowVersion = Convert.ToBase64String(entry.RowVersion),
            Lines = entry.Lines
                .OrderBy(l => l.LineNumber)
                .Select(l => new JournalEntryLineDto
                {
                    Id = l.Id,
                    LineNumber = l.LineNumber,
                    AccountId = l.AccountId,
                    DebitAmount = l.DebitAmount,
                    CreditAmount = l.CreditAmount,
                    CurrencyCode = l.CurrencyCode,
                    ExchangeRate = l.ExchangeRate,
                    BaseCurrencyDebitAmount = l.BaseCurrencyDebitAmount,
                    BaseCurrencyCreditAmount = l.BaseCurrencyCreditAmount,
                    Description = l.Description,
                    DimensionValues = l.DimensionValues.ToDictionary(
                        v => v.CostCenterDimensionId, v => v.CostCenterDimensionValueId)
                })
                .ToList()
        };
    }
}
