using Habbak.ERP.Application.Common.Interfaces;
using Habbak.ERP.Domain.Sales;
using MediatR;
using Microsoft.EntityFrameworkCore;

namespace Habbak.ERP.Application.Sales.Settings.Commands.UpdateSalesCycleSettings;

/// <summary>Screen #12 — upserts the single SalesCycleSettings row for the current company.</summary>
public sealed record UpdateSalesCycleSettingsCommand : IRequest
{
    public required SalesCycleType CycleType { get; init; }
    public required bool RequiresQuoteBeforeOrder { get; init; }
    public required bool RequiresOrderBeforeInvoice { get; init; }
    public required bool RequiresSeparateDeliveryDocument { get; init; }
    public required bool InvoiceBeforeDelivery { get; init; }
    public required bool AutoGenerateDownstreamDocuments { get; init; }
}

public sealed class UpdateSalesCycleSettingsCommandHandler(IApplicationDbContext db, ICurrentCompanyContext currentCompanyContext)
    : IRequestHandler<UpdateSalesCycleSettingsCommand>
{
    public async Task Handle(UpdateSalesCycleSettingsCommand request, CancellationToken cancellationToken)
    {
        var settings = await db.SalesCycleSettingsRows
            .FirstOrDefaultAsync(s => s.CompanyId == currentCompanyContext.CompanyId, cancellationToken);

        if (settings is null)
        {
            settings = new SalesCycleSettings { CompanyId = currentCompanyContext.CompanyId };
            db.SalesCycleSettingsRows.Add(settings);
        }

        settings.CycleType = request.CycleType;
        settings.RequiresQuoteBeforeOrder = request.RequiresQuoteBeforeOrder;
        settings.RequiresOrderBeforeInvoice = request.RequiresOrderBeforeInvoice;
        settings.RequiresSeparateDeliveryDocument = request.RequiresSeparateDeliveryDocument;
        settings.InvoiceBeforeDelivery = request.InvoiceBeforeDelivery;
        settings.AutoGenerateDownstreamDocuments = request.AutoGenerateDownstreamDocuments;

        await db.SaveChangesAsync(cancellationToken);
    }
}
