using Habbak.ERP.API.Auth;
using Habbak.ERP.Application.Sales.Settings.Commands.UpdateLoyaltyProgramSettings;
using Habbak.ERP.Application.Sales.Settings.Commands.UpdateSalesCycleSettings;
using Habbak.ERP.Application.Sales.Settings.Queries.GetLoyaltyProgramSettings;
using Habbak.ERP.Application.Sales.Settings.Queries.GetSalesCycleSettings;
using Habbak.ERP.Domain.Sales;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Habbak.ERP.API.Controllers.Sales;

/// <summary>/sales/settings/* — screens #4 (برنامج الولاء) و#12 (إعدادات دورة المبيعات)
/// (04-Module-Sales.md, section 5).</summary>
[ApiController]
[Authorize]
[Screen("SALES_LOYALTY_PROGRAM_SETTINGS", "SALES_CYCLE_SETTINGS", LookupReads = true)]
[Route("api/v1/sales/settings")]
public class SalesSettingsController(ISender mediator) : ControllerBase
{
    public sealed record UpdateSalesCycleSettingsRequest(
        SalesCycleType CycleType, bool RequiresQuoteBeforeOrder, bool RequiresOrderBeforeInvoice,
        bool RequiresSeparateDeliveryDocument, bool InvoiceBeforeDelivery, bool AutoGenerateDownstreamDocuments);

    public sealed record UpdateLoyaltyProgramSettingsRequest(decimal PointsEarnRate, decimal PointsRedemptionValue);

    [HttpGet("sales-cycle")]
    public async Task<IActionResult> GetSalesCycleSettings(CancellationToken cancellationToken) =>
        Ok(await mediator.Send(new GetSalesCycleSettingsQuery(), cancellationToken));

    [HttpPut("sales-cycle")]
    public async Task<IActionResult> UpdateSalesCycleSettings([FromBody] UpdateSalesCycleSettingsRequest request, CancellationToken cancellationToken)
    {
        await mediator.Send(new UpdateSalesCycleSettingsCommand
        {
            CycleType = request.CycleType,
            RequiresQuoteBeforeOrder = request.RequiresQuoteBeforeOrder,
            RequiresOrderBeforeInvoice = request.RequiresOrderBeforeInvoice,
            RequiresSeparateDeliveryDocument = request.RequiresSeparateDeliveryDocument,
            InvoiceBeforeDelivery = request.InvoiceBeforeDelivery,
            AutoGenerateDownstreamDocuments = request.AutoGenerateDownstreamDocuments
        }, cancellationToken);

        return NoContent();
    }

    [HttpGet("loyalty-program")]
    public async Task<IActionResult> GetLoyaltyProgramSettings(CancellationToken cancellationToken) =>
        Ok(await mediator.Send(new GetLoyaltyProgramSettingsQuery(), cancellationToken));

    [HttpPut("loyalty-program")]
    public async Task<IActionResult> UpdateLoyaltyProgramSettings([FromBody] UpdateLoyaltyProgramSettingsRequest request, CancellationToken cancellationToken)
    {
        await mediator.Send(new UpdateLoyaltyProgramSettingsCommand
        {
            PointsEarnRate = request.PointsEarnRate,
            PointsRedemptionValue = request.PointsRedemptionValue
        }, cancellationToken);

        return NoContent();
    }
}
