import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useForm, useFieldArray, Controller } from 'react-hook-form';
import { useTranslation } from 'react-i18next';
import { useQueries } from '@tanstack/react-query';
import { Button } from '../../../ui-kit/Button';
import { ActionBar } from '../../../ui-kit/ActionBar';
import { AttachmentPanel } from '../../../ui-kit/AttachmentPanel';
import { Card, CardBody } from '../../../ui-kit/Card';
import { Alert } from '../../../ui-kit/Alert';
import { FieldWrapper, Input } from '../../../ui-kit/Field';
import { SearchableSelect } from '../../../ui-kit/SearchableSelect';
import { StatusBadge } from '../../../ui-kit/Badge';
import { useToastStore } from '../../../store/toastStore';
import { useFieldLabels } from '../../common/useFieldLabels';
import { useMandatorySettings } from '../../settings/codingRules/useMandatorySettings';
import { api, getFieldErrorMessage } from '../../../app/api';
import { BranchField } from '../../organization/branches/BranchField';
import { useAccountsList } from '../accounts/api';
import type { AccountDimensionLink, DimensionValue } from '../dimensions/api';
import { useCreateJournalEntry, useDeleteJournalEntry, useJournalEntry, usePostJournalEntry, useReverseJournalEntry, useUpdateJournalEntry } from './api';
import type { JournalEntryLineInput } from './types';
import { todayLocal } from '../../../lib/date';

interface FormValues {
  branchId?: number;
  entryDate: string;
  description: string;
  lines: JournalEntryLineInput[];
}

const emptyLine = (): JournalEntryLineInput => ({
  accountId: 0,
  debitAmount: 0,
  creditAmount: 0,
  currencyCode: 'EGP',
  exchangeRate: 1,
  baseCurrencyDebitAmount: 0,
  baseCurrencyCreditAmount: 0,
  dimensionValues: {}
});

/** /accounting/journal-entries/:id — Edit screen (00-Frontend-Specs.md, section 7 + 18: LineItemsGrid). */
export function JournalEntryEditPage() {
  const { t } = useTranslation();
  const { id } = useParams();
  const isNew = id === 'new';
  const entryId = isNew ? undefined : Number(id);
  const navigate = useNavigate();
  const showToast = useToastStore((s) => s.show);

  // Fix for the spurious "not found" toast on delete: once the delete mutation starts, this page
  // stops asking for the entry at all (rather than relying on cache invalidation timing) — the
  // query would otherwise still be `enabled` while this component is mounted mid-navigate-away,
  // see it's now missing from the cache, and refetch straight into a 404.
  const [isDeleted, setIsDeleted] = useState(false);
  const [showAttachments, setShowAttachments] = useState(false);
  const { data: entry, isLoading } = useJournalEntry(isDeleted ? undefined : entryId);
  const { data: accounts } = useAccountsList(true);
  const { label } = useFieldLabels('ACCOUNTING_JOURNAL_ENTRY_EDIT');
  const { checkDescriptionMandatory, checkAttachmentMandatory } = useMandatorySettings('ACCOUNTING_JOURNAL_ENTRIES', 'JournalEntry', entryId);

  const { register, control, handleSubmit, reset, watch } = useForm<FormValues>({
    defaultValues: {
      entryDate: todayLocal(),
      description: '',
      lines: [emptyLine(), emptyLine()]
    }
  });
  const { fields, append, remove } = useFieldArray({ control, name: 'lines' });

  useEffect(() => {
    if (entry) {
      reset({
        branchId: entry.branchId,
        entryDate: entry.entryDate,
        description: entry.description,
        lines: entry.lines.map((l) => ({
          accountId: l.accountId,
          debitAmount: l.debitAmount,
          creditAmount: l.creditAmount,
          currencyCode: l.currencyCode,
          exchangeRate: l.exchangeRate,
          baseCurrencyDebitAmount: l.baseCurrencyDebitAmount,
          baseCurrencyCreditAmount: l.baseCurrencyCreditAmount,
          dimensionValues: l.dimensionValues
        }))
      });
    }
  }, [entry, reset]);

  const createMutation = useCreateJournalEntry();
  const updateMutation = useUpdateJournalEntry(entryId ?? 0);
  const postMutation = usePostJournalEntry(entryId ?? 0);
  const reverseMutation = useReverseJournalEntry(entryId ?? 0);
  const deleteMutation = useDeleteJournalEntry();

  const watchedLines = watch('lines');
  const totalDebit = watchedLines.reduce((sum, l) => sum + (Number(l.debitAmount) || 0), 0);
  const totalCredit = watchedLines.reduce((sum, l) => sum + (Number(l.creditAmount) || 0), 0);
  const balanced = totalDebit === totalCredit && totalDebit > 0;

  const isEditable = isNew || (entry?.status === 'Draft' && !entry.isAutoGenerated);

  // Dimension columns (01-Module-Accounting.md, rule 14): the account picked on each line
  // decides which dimension columns apply to that line — the table shows the UNION across every
  // line's currently selected account, up to the system-wide max of 5 (rule 24).
  const accountIds = [...new Set(watchedLines.map((l) => Number(l.accountId)).filter((id) => id > 0))];

  const linkQueries = useQueries({
    queries: accountIds.map((accountId) => ({
      queryKey: ['dimension-links', accountId],
      queryFn: async () => (await api.get<AccountDimensionLink[]>('/accounting/dimensions/links', { params: { accountId } })).data
    }))
  });
  const linksByAccount = new Map<number, AccountDimensionLink[]>();
  accountIds.forEach((id, i) => linksByAccount.set(id, linkQueries[i].data ?? []));

  const dimensionColumnsMap = new Map<number, { id: number; name: string; order: number; mandatory: boolean }>();
  for (const links of linksByAccount.values()) {
    for (const link of links) {
      const existing = dimensionColumnsMap.get(link.costCenterDimensionId);
      dimensionColumnsMap.set(link.costCenterDimensionId, {
        id: link.costCenterDimensionId,
        name: link.dimensionNameAr,
        order: existing ? Math.min(existing.order, link.displayOrder) : link.displayOrder,
        mandatory: (existing?.mandatory ?? false) || link.isMandatory
      });
    }
  }
  const dimensionColumns = [...dimensionColumnsMap.values()].sort((a, b) => a.order - b.order);

  const valueQueries = useQueries({
    queries: dimensionColumns.map((d) => ({
      queryKey: ['dimension-values', d.id],
      queryFn: async () => (await api.get<DimensionValue[]>(`/accounting/dimensions/${d.id}/values`)).data
    }))
  });
  const valuesByDimension = new Map<number, DimensionValue[]>();
  dimensionColumns.forEach((d, i) => valuesByDimension.set(d.id, valueQueries[i].data ?? []));

  const onSubmit = handleSubmit(async (values) => {
    if (!checkDescriptionMandatory(values.description)) return;
    if (!values.branchId) {
      showToast(t('journalEntries.branchRequired'), 'error');
      return;
    }
    const payload = {
      branchId: values.branchId,
      entryDate: values.entryDate,
      description: values.description,
      lines: values.lines.map((l) => {
        const dimensionValues: Record<string, number> = {};
        for (const [dimensionId, valueId] of Object.entries(l.dimensionValues ?? {})) {
          const numericValueId = Number(valueId);
          if (numericValueId > 0) dimensionValues[dimensionId] = numericValueId;
        }

        return {
          ...l,
          dimensionValues,
          debitAmount: Number(l.debitAmount),
          creditAmount: Number(l.creditAmount),
          baseCurrencyDebitAmount: Number(l.debitAmount),
          baseCurrencyCreditAmount: Number(l.creditAmount),
          exchangeRate: 1,
          currencyCode: 'EGP'
        };
      })
    };

    try {
      if (isNew) {
        const newId = await createMutation.mutateAsync(payload);
        showToast(t('journalEntries.createSuccess'), 'success');
        navigate(`/accounting/journal-entries/${newId}`);
      } else if (entry) {
        await updateMutation.mutateAsync({ ...payload, rowVersion: entry.rowVersion });
        showToast(t('journalEntries.updateSuccess'), 'success');
      }
    } catch (error) {
      // General errors are already toasted centrally by the Axios interceptor — only
      // field-level validation errors (excluded from that central toast) need surfacing here.
      const message = getFieldErrorMessage(error);
      if (message) showToast(message, 'error');
    }
  });

  const handlePost = async () => {
    if (!checkAttachmentMandatory()) return;
    try {
      const result = await postMutation.mutateAsync();
      showToast(result.status === 'Posted' ? t('journalEntries.postSuccessPosted') : t('journalEntries.postSuccessPending'), 'success');
    } catch (error) {
      const message = getFieldErrorMessage(error);
      if (message) showToast(message, 'error');
    }
  };

  const handleReverse = async () => {
    try {
      const result = await reverseMutation.mutateAsync();
      showToast(t('journalEntries.reverseSuccess'), 'success');
      navigate(`/accounting/journal-entries/${result.id}`);
    } catch (error) {
      const message = getFieldErrorMessage(error);
      if (message) showToast(message, 'error');
    }
  };

  const handleDelete = async () => {
    if (!entryId) return;
    setIsDeleted(true);
    try {
      await deleteMutation.mutateAsync(entryId);
      showToast(t('journalEntries.deleteSuccess'), 'success');
      navigate('/accounting/journal-entries');
    } catch (error) {
      setIsDeleted(false);
      const message = getFieldErrorMessage(error);
      if (message) showToast(message, 'error');
    }
  };

  if (!isNew && isLoading) {
    return <div>{t('common.loading')}</div>;
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 16, minWidth: 0 }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <h2 style={{ margin: 0 }}>{isNew ? t('journalEntries.newTitle') : `${t('journalEntries.detailTitle')} ${entry?.entryNumber ?? ''}`}</h2>
        {entry && <StatusBadge status={entry.status} />}
      </div>

      <ActionBar
        primary={
          entry?.status === 'Draft'
            ? { key: 'post', label: t('common.post'), onClick: handlePost }
            : isEditable
              ? { key: 'save', label: isNew ? t('common.saveDraft') : t('common.saveChanges'), onClick: () => onSubmit() }
              : undefined
        }
        secondary={[
          { key: 'back', label: isEditable ? t('common.cancel') : t('common.back'), onClick: () => navigate('/accounting/journal-entries') },
          ...(!isNew ? [{ key: 'attachments', label: t('attachments.title'), icon: 'paperclip', onClick: () => setShowAttachments((v) => !v) }] : []),
          ...(entry?.status === 'Draft'
            ? [{ key: 'saveChanges', label: t('common.saveChanges'), onClick: () => onSubmit() }]
            : []),
          ...(entry?.status === 'Posted'
            ? [{ key: 'reverse', label: t('journalEntries.createReversal'), onClick: handleReverse }]
            : [])
        ]}
        destructive={
          !isNew && isEditable
            ? [{ key: 'delete', label: t('common.delete'), onClick: handleDelete, confirmMessage: t('journalEntries.deleteConfirm') }]
            : []
        }
      />

      {entry?.isAutoGenerated && <Alert tone="warning">{t('journalEntries.lockedAutoGenerated')}</Alert>}
      {!entry?.isAutoGenerated && entry?.status === 'Posted' && <Alert tone="warning">{t('journalEntries.lockedPosted')}</Alert>}

      <form onSubmit={onSubmit} style={{ display: 'flex', flexDirection: 'column', gap: 16, minWidth: 0 }}>
        <Card style={{ minWidth: 0 }}>
        <CardBody>
        <div style={{ display: 'flex', gap: 16 }}>
          <FieldWrapper label={label('entryNumber', t('journalEntries.entryNumber'))}>
            <Input value={isNew ? t('codingRules.autoGeneratedPlaceholder') : (entry?.entryNumber ?? '')} disabled />
          </FieldWrapper>
          <FieldWrapper label={label('date', t('journalEntries.date'))}>
            <Input type="date" disabled={!isEditable} {...register('entryDate')} />
          </FieldWrapper>
          <Controller
            control={control}
            name="branchId"
            render={({ field }) => (
              <BranchField
                value={field.value}
                onChange={field.onChange}
                label={label('branch', t('journalEntries.branch'))}
                autoSelect={isNew}
                disabled={!isEditable}
              />
            )}
          />
        </div>

        <div style={{ overflowX: 'auto', marginTop: 16 }}>
        <table style={{ fontSize: 13, borderCollapse: 'collapse' }}>
          <thead>
            <tr>
              <th style={{ textAlign: 'start', padding: 8, whiteSpace: 'nowrap' }}>{label('account', t('journalEntries.account'))}</th>
              <th style={{ textAlign: 'start', padding: 8, whiteSpace: 'nowrap' }}>{label('debit', t('journalEntries.debit'))}</th>
              <th style={{ textAlign: 'start', padding: 8, whiteSpace: 'nowrap' }}>{label('credit', t('journalEntries.credit'))}</th>
              {dimensionColumns.map((d) => (
                <th key={d.id} style={{ textAlign: 'start', padding: 8, whiteSpace: 'nowrap' }} title={d.name}>
                  <span style={{ display: 'inline-block', maxWidth: 110, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', verticalAlign: 'bottom' }}>
                    {d.name}
                  </span>
                  {d.mandatory ? ' *' : ''}
                </th>
              ))}
              {isEditable && <th />}
            </tr>
          </thead>
          <tbody>
            {fields.map((field, index) => {
              const lineAccountId = Number(watchedLines[index]?.accountId) || 0;
              const lineLinks = linksByAccount.get(lineAccountId) ?? [];
              const lineDimensionIds = new Set(lineLinks.map((l) => l.costCenterDimensionId));

              return (
                <tr key={field.id}>
                  <td style={{ padding: 8 }}>
                    <Controller
                      control={control}
                      name={`lines.${index}.accountId` as const}
                      render={({ field }) => (
                        <SearchableSelect
                          disabled={!isEditable}
                          style={{ width: 190 }}
                          value={field.value}
                          onChange={(v) => field.onChange(Number(v))}
                          options={[
                            { value: 0, label: t('common.selectAccount') },
                            ...(accounts?.map((a) => ({ value: a.id, label: `${a.code} - ${a.nameAr}` })) ?? [])
                          ]}
                        />
                      )}
                    />
                  </td>
                  <td style={{ padding: 8 }}>
                    <Input type="number" step="0.01" disabled={!isEditable} style={{ width: 100 }} {...register(`lines.${index}.debitAmount` as const, { valueAsNumber: true })} />
                  </td>
                  <td style={{ padding: 8 }}>
                    <Input type="number" step="0.01" disabled={!isEditable} style={{ width: 100 }} {...register(`lines.${index}.creditAmount` as const, { valueAsNumber: true })} />
                  </td>
                  {dimensionColumns.map((d) => (
                    <td key={d.id} style={{ padding: 8 }}>
                      {lineDimensionIds.has(d.id) ? (
                        <Controller
                          control={control}
                          name={`lines.${index}.dimensionValues.${d.id}` as const}
                          render={({ field }) => (
                            <SearchableSelect
                              disabled={!isEditable}
                              style={{ width: 120 }}
                              value={field.value}
                              onChange={(v) => field.onChange(v === '' ? undefined : Number(v))}
                              options={[
                                { value: '', label: '—' },
                                ...(valuesByDimension.get(d.id)?.filter((v) => v.isActive).map((v) => ({ value: v.id, label: `${v.code} - ${v.nameAr}` })) ?? [])
                              ]}
                            />
                          )}
                        />
                      ) : (
                        <span style={{ color: 'var(--color-text-muted)', display: 'inline-block', width: 120, textAlign: 'center' }}>—</span>
                      )}
                    </td>
                  ))}
                  {isEditable && (
                    <td>
                      <Button type="button" variant="ghost" onClick={() => remove(index)}>
                        {t('common.delete')}
                      </Button>
                    </td>
                  )}
                </tr>
              );
            })}
          </tbody>
          <tfoot>
            <tr>
              <td style={{ padding: 8, fontWeight: 700, whiteSpace: 'nowrap' }}>{t('common.total')}</td>
              <td style={{ padding: 8, fontWeight: 700, color: balanced ? 'var(--color-success)' : 'var(--color-error)' }}>
                {totalDebit.toLocaleString()}
              </td>
              <td style={{ padding: 8, fontWeight: 700, color: balanced ? 'var(--color-success)' : 'var(--color-error)' }}>
                {totalCredit.toLocaleString()}
              </td>
              {dimensionColumns.length > 0 && <td colSpan={dimensionColumns.length} />}
              {isEditable && <td />}
            </tr>
          </tfoot>
        </table>
        </div>

        {isEditable && (
          <Button type="button" variant="ghost" onClick={() => append(emptyLine())} style={{ alignSelf: 'flex-start', marginTop: 8 }}>
            {t('journalEntries.addLine')}
          </Button>
        )}

        <div style={{ marginTop: 16, width: '100%' }}>
          <FieldWrapper label={label('description', t('journalEntries.description'))}>
            <textarea
              disabled={!isEditable}
              rows={3}
              style={{
                width: '100%', padding: '9px 12px', borderRadius: 'var(--radius-chip)', border: '1px solid transparent',
                background: 'var(--color-surface-2)', fontSize: 14, fontFamily: 'inherit', resize: 'vertical', boxSizing: 'border-box'
              }}
              {...register('description')}
            />
          </FieldWrapper>
        </div>
        </CardBody>
        </Card>
      </form>

      {showAttachments && !isNew && <AttachmentPanel entityType="JournalEntry" entityId={entryId} />}
    </div>
  );
}
