export interface JournalEntryListItem {
  id: number;
  entryNumber: string;
  entryDate: string;
  description: string;
  sourceModule: string;
  isAutoGenerated: boolean;
  totalDebit: number;
  totalCredit: number;
  status: string;
}

export interface JournalEntryLine {
  id?: number;
  lineNumber: number;
  accountId: number;
  debitAmount: number;
  creditAmount: number;
  currencyCode: string;
  exchangeRate: number;
  baseCurrencyDebitAmount: number;
  baseCurrencyCreditAmount: number;
  description?: string;
  dimensionValues: Record<string, number>;
}

export interface JournalEntryDetail {
  id: number;
  publicId?: string;
  branchId?: number;
  entryNumber: string;
  entryDate: string;
  description: string;
  sourceModule: string;
  sourceDocumentType?: string;
  sourceDocumentId?: number;
  status: string;
  isAutoGenerated: boolean;
  reversalOfEntryId?: number;
  totalDebit: number;
  totalCredit: number;
  approvalInstanceId?: number;
  postedAtUtc?: string;
  rowVersion: string;
  lines: JournalEntryLine[];
}

export interface JournalEntryLineInput {
  accountId: number;
  debitAmount: number;
  creditAmount: number;
  currencyCode: string;
  exchangeRate: number;
  baseCurrencyDebitAmount: number;
  baseCurrencyCreditAmount: number;
  description?: string;
  dimensionValues: Record<string, number>;
}
