import { useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Card, CardBody } from '../../../../ui-kit/Card';
import { FieldWrapper, Input } from '../../../../ui-kit/Field';
import { SearchableSelect } from '../../../../ui-kit/SearchableSelect';
import { Button } from '../../../../ui-kit/Button';
import { useToastStore } from '../../../../store/toastStore';
import { getFieldErrorMessage } from '../../../../app/api';
import { useCodingRule } from '../../../settings/codingRules/api';
import { useBranchesList } from '../../../organization/branches/api';
import { useOrgUnits } from '../../orgUnits/api';
import { useJobPositions } from '../../jobPositions/api';
import { useJobGrades } from '../../jobGrades/api';
import { useCreateEmployee, useEmployeesLookup } from '../../employees/api';
import type { EmploymentType } from '../../employees/types';

const EMPLOYMENT_TYPES: EmploymentType[] = ['FullTime', 'PartTime', 'Temporary'];

interface FormState {
  code: string;
  nameAr: string;
  nameEn: string;
  branchId: number | '';
  orgUnitId: number | '';
  jobPositionId: number | '';
  jobGradeId: number | '';
  managerId: number | '';
  hireDate: string;
  employmentType: EmploymentType;
}

/** خطوة 1: بيانات الموظف الأساسية — نفس حقول BasicInfoTab وقت الإنشاء، بدون زرار "حفظ" منفصل. */
export function EmployeeStep({ onComplete }: { onComplete: (employeeId: number) => void }) {
  const { t } = useTranslation();
  const showToast = useToastStore((s) => s.show);

  const { data: codingRule } = useCodingRule('HR_EMPLOYEES');
  const codeIsAutomatic = codingRule?.isAutomatic ?? false;

  const { data: branches } = useBranchesList();
  const branchOptions = useMemo(() => (branches ?? []).map((b) => ({ value: b.id, label: b.nameAr })), [branches]);
  const { data: orgUnits } = useOrgUnits();
  const orgUnitOptions = useMemo(() => (orgUnits ?? []).map((u) => ({ value: u.id, label: u.nameAr })), [orgUnits]);
  const { data: jobPositions } = useJobPositions();
  const jobPositionOptions = useMemo(() => (jobPositions ?? []).map((p) => ({ value: p.id, label: p.nameAr })), [jobPositions]);
  const { data: jobGrades } = useJobGrades();
  const jobGradeOptions = useMemo(() => (jobGrades ?? []).map((g) => ({ value: g.id, label: g.nameAr })), [jobGrades]);
  const { data: employeesLookup } = useEmployeesLookup();
  const managerOptions = useMemo(
    () => [{ value: '', label: t('hr.employees.noManager') }, ...(employeesLookup ?? []).map((e) => ({ value: e.id, label: `${e.code} — ${e.nameAr}` }))],
    [employeesLookup, t]
  );

  const [form, setForm] = useState<FormState>({
    code: '', nameAr: '', nameEn: '', branchId: '', orgUnitId: '', jobPositionId: '', jobGradeId: '',
    managerId: '', hireDate: new Date().toISOString().slice(0, 10), employmentType: 'FullTime'
  });

  const createEmployee = useCreateEmployee();

  const handleNext = async () => {
    if (!form.nameAr || !form.nameEn || form.branchId === '' || form.orgUnitId === '' || form.jobPositionId === '' || form.jobGradeId === '') {
      showToast(t('hr.hiring.requiredFields'), 'error');
      return;
    }
    try {
      const result = await createEmployee.mutateAsync({
        code: codeIsAutomatic ? undefined : form.code,
        nameAr: form.nameAr,
        nameEn: form.nameEn,
        branchId: Number(form.branchId),
        orgUnitId: Number(form.orgUnitId),
        jobPositionId: Number(form.jobPositionId),
        jobGradeId: Number(form.jobGradeId),
        managerId: form.managerId === '' ? undefined : Number(form.managerId),
        hireDate: form.hireDate,
        employmentType: form.employmentType
      });
      onComplete(result.id);
    } catch (error) {
      const message = getFieldErrorMessage(error);
      if (message) showToast(message, 'error');
    }
  };

  return (
    <Card>
      <CardBody>
        <div style={{ display: 'flex', gap: 16, flexWrap: 'wrap' }}>
          <FieldWrapper label={t('hr.code')}>
            <Input
              value={codeIsAutomatic ? t('codingRules.autoGeneratedPlaceholder') : form.code}
              onChange={(e) => setForm((f) => ({ ...f, code: e.target.value }))}
              disabled={codeIsAutomatic}
            />
          </FieldWrapper>
          <FieldWrapper label={t('hr.nameAr')}>
            <Input value={form.nameAr} onChange={(e) => setForm((f) => ({ ...f, nameAr: e.target.value }))} style={{ minWidth: 220 }} />
          </FieldWrapper>
          <FieldWrapper label={t('hr.nameEn')}>
            <Input value={form.nameEn} onChange={(e) => setForm((f) => ({ ...f, nameEn: e.target.value }))} style={{ minWidth: 220 }} />
          </FieldWrapper>
          <FieldWrapper label={t('hr.orgUnits.branch')}>
            <SearchableSelect value={form.branchId} onChange={(v) => setForm((f) => ({ ...f, branchId: v === '' ? '' : Number(v) }))} options={branchOptions} style={{ minWidth: 200 }} />
          </FieldWrapper>
          <FieldWrapper label={t('hr.orgUnits.title')}>
            <SearchableSelect value={form.orgUnitId} onChange={(v) => setForm((f) => ({ ...f, orgUnitId: v === '' ? '' : Number(v) }))} options={orgUnitOptions} style={{ minWidth: 200 }} />
          </FieldWrapper>
          <FieldWrapper label={t('hr.jobPositions.title')}>
            <SearchableSelect value={form.jobPositionId} onChange={(v) => setForm((f) => ({ ...f, jobPositionId: v === '' ? '' : Number(v) }))} options={jobPositionOptions} style={{ minWidth: 200 }} />
          </FieldWrapper>
          <FieldWrapper label={t('hr.jobGrades.title')}>
            <SearchableSelect value={form.jobGradeId} onChange={(v) => setForm((f) => ({ ...f, jobGradeId: v === '' ? '' : Number(v) }))} options={jobGradeOptions} style={{ minWidth: 200 }} />
          </FieldWrapper>
          <FieldWrapper label={t('hr.employees.manager')}>
            <SearchableSelect value={form.managerId} onChange={(v) => setForm((f) => ({ ...f, managerId: v === '' ? '' : Number(v) }))} options={managerOptions} style={{ minWidth: 220 }} />
          </FieldWrapper>
          <FieldWrapper label={t('hr.employees.hireDate')}>
            <Input type="date" value={form.hireDate} onChange={(e) => setForm((f) => ({ ...f, hireDate: e.target.value }))} />
          </FieldWrapper>
          <FieldWrapper label={t('hr.employees.employmentType')}>
            <SearchableSelect
              value={form.employmentType}
              onChange={(v) => setForm((f) => ({ ...f, employmentType: v as EmploymentType }))}
              options={EMPLOYMENT_TYPES.map((v) => ({ value: v, label: t(`hr.employees.employmentTypes.${v}`) }))}
              style={{ minWidth: 160 }}
            />
          </FieldWrapper>
        </div>
        <div style={{ marginTop: 16 }}>
          <Button variant="primary" onClick={handleNext}>{t('hr.hiring.next')}</Button>
        </div>
      </CardBody>
    </Card>
  );
}
