using FluentValidation;
using Habbak.ERP.Application.Common;
using Habbak.ERP.Application.Common.Interfaces;
using Habbak.ERP.Application.Common.Models;
using Habbak.ERP.Domain.Accounting;
using Habbak.ERP.Shared.Enums;
using MediatR;

namespace Habbak.ERP.Application.Accounting.Custody.Commands.CreateCustodyRegister;

/// <summary>
/// Issues a new custody and posts its disbursement entry immediately (Dr custody-receivable
/// account / Cr treasury). EmployeeId references the future HR module's aggregate (no FK yet —
/// see CustodyRegister's mapping). CustodyReceivableAccountId is NOT persisted on the entity (it
/// isn't part of the documented schema, 01-Module-Accounting.md section 2.4) — it is supplied
/// again at settlement time (CreateCustodySettlementCommand), a pragmatic simplification while
/// there is no HR-owned subsidiary account to resolve automatically.
/// </summary>
public sealed record CreateCustodyRegisterCommand(
    long EmployeeId, long? BranchId, decimal Amount, DateOnly IssueDate,
    long TreasuryAccountId, long CustodyReceivableAccountId) : IRequest<long>;

public sealed class CreateCustodyRegisterCommandValidator : AbstractValidator<CreateCustodyRegisterCommand>
{
    public CreateCustodyRegisterCommandValidator()
    {
        RuleFor(x => x.EmployeeId).GreaterThan(0);
        RuleFor(x => x.Amount).GreaterThan(0);
        RuleFor(x => x.TreasuryAccountId).GreaterThan(0);
        RuleFor(x => x.CustodyReceivableAccountId).GreaterThan(0);
    }
}

public sealed class CreateCustodyRegisterCommandHandler(
    IApplicationDbContext db, IPostingService postingService, ICurrentCompanyContext currentCompanyContext)
    : IRequestHandler<CreateCustodyRegisterCommand, long>
{
    public async Task<long> Handle(CreateCustodyRegisterCommand request, CancellationToken cancellationToken)
    {
        var branchId = BranchRequirement.Resolve(request.BranchId, currentCompanyContext.BranchId);

        var custody = new CustodyRegister
        {
            CompanyId = currentCompanyContext.CompanyId,
            BranchId = branchId,
            EmployeeId = request.EmployeeId,
            Amount = request.Amount,
            IssueDate = request.IssueDate,
            Status = CustodyStatus.Open
        };

        var postingRequest = new PostingRequest
        {
            CompanyId = currentCompanyContext.CompanyId,
            BranchId = branchId,
            EntryDate = request.IssueDate,
            Description = $"صرف عهدة للموظف رقم {request.EmployeeId}",
            SourceModule = SourceModule.Manual,
            IsAutoGenerated = true,
            Lines =
            [
                new PostingLineRequest
                {
                    AccountId = request.CustodyReceivableAccountId, DebitAmount = request.Amount, CreditAmount = 0m,
                    CurrencyCode = "EGP", ExchangeRate = 1m, BaseCurrencyDebitAmount = request.Amount, BaseCurrencyCreditAmount = 0m
                },
                new PostingLineRequest
                {
                    AccountId = request.TreasuryAccountId, DebitAmount = 0m, CreditAmount = request.Amount,
                    CurrencyCode = "EGP", ExchangeRate = 1m, BaseCurrencyDebitAmount = 0m, BaseCurrencyCreditAmount = request.Amount
                }
            ]
        };

        var result = await postingService.PostAsync(postingRequest, cancellationToken);
        custody.JournalEntry = result.JournalEntry;

        db.CustodyRegisters.Add(custody);
        await db.SaveChangesAsync(cancellationToken);

        return custody.Id;
    }
}
