import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { ActionBar } from '../../../ui-kit/ActionBar';
import { Card, CardBody } from '../../../ui-kit/Card';
import { FieldWrapper, Input } from '../../../ui-kit/Field';
import { useToastStore } from '../../../store/toastStore';
import { getFieldErrorMessage } from '../../../app/api';
import { useCodingRule } from '../../settings/codingRules/api';
import { useCreatePaymentMethod, useDeletePaymentMethod, usePaymentMethodsList, useUpdatePaymentMethod } from './api';

/** /accounting/payment-methods/:id — Edit screen (standard List/Edit pattern, 00-Frontend-Specs.md, section 5-7). */
export function PaymentMethodEditPage() {
  const { t } = useTranslation();
  const { id } = useParams();
  const isNew = id === 'new';
  const paymentMethodId = isNew ? undefined : Number(id);
  const navigate = useNavigate();
  const showToast = useToastStore((s) => s.show);

  const { data: paymentMethods, isLoading } = usePaymentMethodsList();
  const paymentMethod = paymentMethods?.find((p) => p.id === paymentMethodId);
  const { data: codingRule } = useCodingRule('ACCOUNTING_PAYMENT_METHODS');
  const codeIsAutomatic = codingRule?.isAutomatic ?? false;

  const [code, setCode] = useState('');
  const [nameAr, setNameAr] = useState('');
  const [nameEn, setNameEn] = useState('');
  const [isActive, setIsActive] = useState(true);

  useEffect(() => {
    if (paymentMethod) {
      setNameAr(paymentMethod.nameAr);
      setNameEn(paymentMethod.nameEn);
      setIsActive(paymentMethod.isActive);
    }
  }, [paymentMethod]);

  const createMutation = useCreatePaymentMethod();
  const updateMutation = useUpdatePaymentMethod(paymentMethodId ?? 0);
  const deleteMutation = useDeletePaymentMethod();

  const handleSave = async () => {
    try {
      if (isNew) {
        const { id: newId } = await createMutation.mutateAsync({ code: codeIsAutomatic ? undefined : code, nameAr, nameEn });
        showToast(t('paymentMethods.createSuccess'), 'success');
        navigate(`/accounting/payment-methods/${newId}`);
      } else {
        await updateMutation.mutateAsync({ nameAr, nameEn, isActive });
        showToast(t('paymentMethods.updateSuccess'), 'success');
      }
    } catch (error) {
      const message = getFieldErrorMessage(error);
      if (message) showToast(message, 'error');
    }
  };

  const handleDelete = async () => {
    if (!paymentMethodId) return;
    try {
      await deleteMutation.mutateAsync(paymentMethodId);
      showToast(t('paymentMethods.deleteSuccess'), 'success');
      navigate('/accounting/payment-methods');
    } catch (error) {
      const message = getFieldErrorMessage(error);
      if (message) showToast(message, 'error');
    }
  };

  if (!isNew && isLoading) {
    return <div>{t('common.loading')}</div>;
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 16, maxWidth: 640 }}>
      <h2 style={{ margin: 0 }}>{isNew ? t('paymentMethods.addPaymentMethod') : `${t('paymentMethods.title')} — ${paymentMethod?.code ?? ''}`}</h2>

      <ActionBar
        primary={{ key: 'save', label: isNew ? t('common.saveDraft') : t('common.saveChanges'), onClick: handleSave }}
        secondary={[{ key: 'back', label: t('common.back'), onClick: () => navigate('/accounting/payment-methods') }]}
        destructive={
          !isNew
            ? [{ key: 'delete', label: t('common.remove'), onClick: handleDelete, confirmMessage: t('paymentMethods.deleteConfirm') }]
            : []
        }
      />

      <Card>
        <CardBody>
          <div style={{ display: 'flex', gap: 16, flexWrap: 'wrap' }}>
            <FieldWrapper label={t('paymentMethods.code')}>
              {codeIsAutomatic ? (
                <Input value={isNew ? t('codingRules.autoGeneratedPlaceholder') : (paymentMethod?.code ?? '')} disabled />
              ) : (
                <Input value={isNew ? code : (paymentMethod?.code ?? '')} onChange={(e) => setCode(e.target.value)} disabled={!isNew} />
              )}
            </FieldWrapper>

            <FieldWrapper label={t('paymentMethods.nameAr')}>
              <Input value={nameAr} onChange={(e) => setNameAr(e.target.value)} style={{ minWidth: 200 }} />
            </FieldWrapper>

            <FieldWrapper label={t('paymentMethods.nameEn')}>
              <Input value={nameEn} onChange={(e) => setNameEn(e.target.value)} style={{ minWidth: 200 }} />
            </FieldWrapper>

            {!isNew && (
              <FieldWrapper label={t('paymentMethods.isActive')}>
                <label style={{ display: 'flex', alignItems: 'center', gap: 6, height: 38 }}>
                  <input type="checkbox" checked={isActive} onChange={(e) => setIsActive(e.target.checked)} />
                </label>
              </FieldWrapper>
            )}
          </div>
        </CardBody>
      </Card>
    </div>
  );
}
