import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { ActionBar } from '../../../ui-kit/ActionBar';
import { Card, CardBody } from '../../../ui-kit/Card';
import { FieldWrapper, Input } from '../../../ui-kit/Field';
import { SearchableSelect } from '../../../ui-kit/SearchableSelect';
import { useToastStore } from '../../../store/toastStore';
import { getFieldErrorMessage } from '../../../app/api';
import { useCodingRule } from '../../settings/codingRules/api';
import { useBranchesList } from '../../organization/branches/api';
import { useCreateCustodyOfficer, useCustodyOfficersList, useDeleteCustodyOfficer, useUpdateCustodyOfficer } from './api';

/** /inventory/custody-officers/:id — Edit screen (standard List/Edit pattern, 00-Frontend-Specs.md, section 5-7). */
export function CustodyOfficerEditPage() {
  const { t } = useTranslation();
  const { id } = useParams();
  const isNew = id === 'new';
  const officerId = isNew ? undefined : Number(id);
  const navigate = useNavigate();
  const showToast = useToastStore((s) => s.show);

  const { data: officers, isLoading } = useCustodyOfficersList();
  const officer = officers?.find((o) => o.id === officerId);
  const { data: branches } = useBranchesList();
  const { data: codingRule } = useCodingRule('INVENTORY_CUSTODY_OFFICERS');
  const codeIsAutomatic = codingRule?.isAutomatic ?? false;

  const [code, setCode] = useState('');
  const [nameAr, setNameAr] = useState('');
  const [nameEn, setNameEn] = useState('');
  const [branchId, setBranchId] = useState<number | ''>('');
  const [isActive, setIsActive] = useState(true);

  useEffect(() => {
    if (officer) {
      setNameAr(officer.nameAr);
      setNameEn(officer.nameEn);
      setBranchId(officer.branchId ?? '');
      setIsActive(officer.isActive);
    }
  }, [officer]);

  const createMutation = useCreateCustodyOfficer();
  const updateMutation = useUpdateCustodyOfficer(officerId ?? 0);
  const deleteMutation = useDeleteCustodyOfficer();

  const branchOptions = [{ value: '', label: t('custodyOfficers.none') }, ...(branches ?? []).map((b) => ({ value: b.id, label: b.nameAr }))];

  const handleSave = async () => {
    try {
      const resolvedBranchId = branchId === '' ? null : Number(branchId);
      if (isNew) {
        const { id: newId } = await createMutation.mutateAsync({ code: codeIsAutomatic ? undefined : code, nameAr, nameEn, branchId: resolvedBranchId });
        showToast(t('custodyOfficers.createSuccess'), 'success');
        navigate(`/inventory/custody-officers/${newId}`);
      } else {
        await updateMutation.mutateAsync({ nameAr, nameEn, branchId: resolvedBranchId, isActive });
        showToast(t('custodyOfficers.updateSuccess'), 'success');
      }
    } catch (error) {
      const message = getFieldErrorMessage(error);
      if (message) showToast(message, 'error');
    }
  };

  const handleDelete = async () => {
    if (!officerId) return;
    try {
      await deleteMutation.mutateAsync(officerId);
      showToast(t('custodyOfficers.deleteSuccess'), 'success');
      navigate('/inventory/custody-officers');
    } catch (error) {
      const message = getFieldErrorMessage(error);
      if (message) showToast(message, 'error');
    }
  };

  if (!isNew && isLoading) {
    return <div>{t('common.loading')}</div>;
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 16, maxWidth: 640 }}>
      <h2 style={{ margin: 0 }}>{isNew ? t('custodyOfficers.addCustodyOfficer') : `${t('custodyOfficers.title')} — ${officer?.code ?? ''}`}</h2>

      <ActionBar
        primary={{ key: 'save', label: isNew ? t('common.saveDraft') : t('common.saveChanges'), onClick: handleSave }}
        secondary={[{ key: 'back', label: t('common.back'), onClick: () => navigate('/inventory/custody-officers') }]}
        destructive={
          !isNew
            ? [{ key: 'delete', label: t('common.remove'), onClick: handleDelete, confirmMessage: t('custodyOfficers.deleteConfirm') }]
            : []
        }
      />

      <Card>
        <CardBody>
          <div style={{ display: 'flex', gap: 16, flexWrap: 'wrap' }}>
            <FieldWrapper label={t('custodyOfficers.code')}>
              {codeIsAutomatic ? (
                <Input value={isNew ? t('codingRules.autoGeneratedPlaceholder') : (officer?.code ?? '')} disabled />
              ) : (
                <Input value={isNew ? code : (officer?.code ?? '')} onChange={(e) => setCode(e.target.value)} disabled={!isNew} />
              )}
            </FieldWrapper>

            <FieldWrapper label={t('custodyOfficers.nameAr')}>
              <Input value={nameAr} onChange={(e) => setNameAr(e.target.value)} style={{ minWidth: 200 }} />
            </FieldWrapper>

            <FieldWrapper label={t('custodyOfficers.nameEn')}>
              <Input value={nameEn} onChange={(e) => setNameEn(e.target.value)} style={{ minWidth: 200 }} />
            </FieldWrapper>

            <FieldWrapper label={t('custodyOfficers.branch')}>
              <SearchableSelect
                value={branchId}
                onChange={(v) => setBranchId(v === '' ? '' : Number(v))}
                options={branchOptions}
                style={{ minWidth: 200 }}
              />
            </FieldWrapper>

            {!isNew && (
              <FieldWrapper label={t('custodyOfficers.isActive')}>
                <label style={{ display: 'flex', alignItems: 'center', gap: 6, height: 38 }}>
                  <input type="checkbox" checked={isActive} onChange={(e) => setIsActive(e.target.checked)} />
                </label>
              </FieldWrapper>
            )}
          </div>
        </CardBody>
      </Card>
    </div>
  );
}
