import { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { ActionBar } from '../../../ui-kit/ActionBar';
import { Card, CardBody } from '../../../ui-kit/Card';
import { FieldWrapper } from '../../../ui-kit/Field';
import { SearchableSelect } from '../../../ui-kit/SearchableSelect';
import { useToastStore } from '../../../store/toastStore';
import { getFieldErrorMessage } from '../../../app/api';
import { useSalesCycleSettings, useUpdateSalesCycleSettings } from './api';
import type { SalesCycleSettings } from './types';

const CYCLE_TYPES = ['InvoiceOnly', 'InvoiceWithIssue', 'Full', 'OrderBased', 'DeliveryBased', 'Simplified'] as const;

const DEFAULTS: SalesCycleSettings = {
  cycleType: 'Full',
  requiresQuoteBeforeOrder: false,
  requiresOrderBeforeInvoice: true,
  requiresSeparateDeliveryDocument: true,
  invoiceBeforeDelivery: true,
  autoGenerateDownstreamDocuments: false
};

// The reference preset table from 04-Module-Sales.md section 2.6 — applied once when CycleType is
// picked from the dropdown, then each flag stays independently editable (matches PurchaseCycleSettings'
// own "preset fills flags, flags are the only thing read" split, rule 28).
const PRESETS: Record<(typeof CYCLE_TYPES)[number], Omit<SalesCycleSettings, 'cycleType'>> = {
  InvoiceOnly: { requiresQuoteBeforeOrder: false, requiresOrderBeforeInvoice: false, requiresSeparateDeliveryDocument: false, invoiceBeforeDelivery: false, autoGenerateDownstreamDocuments: false },
  InvoiceWithIssue: { requiresQuoteBeforeOrder: false, requiresOrderBeforeInvoice: false, requiresSeparateDeliveryDocument: true, invoiceBeforeDelivery: true, autoGenerateDownstreamDocuments: false },
  Full: { requiresQuoteBeforeOrder: true, requiresOrderBeforeInvoice: true, requiresSeparateDeliveryDocument: true, invoiceBeforeDelivery: true, autoGenerateDownstreamDocuments: false },
  OrderBased: { requiresQuoteBeforeOrder: false, requiresOrderBeforeInvoice: true, requiresSeparateDeliveryDocument: true, invoiceBeforeDelivery: true, autoGenerateDownstreamDocuments: false },
  DeliveryBased: { requiresQuoteBeforeOrder: false, requiresOrderBeforeInvoice: true, requiresSeparateDeliveryDocument: true, invoiceBeforeDelivery: false, autoGenerateDownstreamDocuments: false },
  Simplified: { requiresQuoteBeforeOrder: false, requiresOrderBeforeInvoice: true, requiresSeparateDeliveryDocument: true, invoiceBeforeDelivery: false, autoGenerateDownstreamDocuments: true }
};

const CHECKBOX_FIELDS: { key: keyof Omit<SalesCycleSettings, 'cycleType'>; labelKey: string }[] = [
  { key: 'requiresQuoteBeforeOrder', labelKey: 'salesCycleSettings.requiresQuoteBeforeOrder' },
  { key: 'requiresOrderBeforeInvoice', labelKey: 'salesCycleSettings.requiresOrderBeforeInvoice' },
  { key: 'requiresSeparateDeliveryDocument', labelKey: 'salesCycleSettings.requiresSeparateDeliveryDocument' },
  { key: 'invoiceBeforeDelivery', labelKey: 'salesCycleSettings.invoiceBeforeDelivery' },
  { key: 'autoGenerateDownstreamDocuments', labelKey: 'salesCycleSettings.autoGenerateDownstreamDocuments' }
];

/** /sales/settings/sales-cycle — screen #12 (04-Module-Sales.md, section 2.6). One row per
 * company; each checkbox mirrors a SalesCycleSettings flag a Sales document command checks —
 * CycleType itself stays a display-only preset (rule 28). */
export function SalesCycleSettingsPage() {
  const { t } = useTranslation();
  const showToast = useToastStore((s) => s.show);
  const { data: settings, isLoading } = useSalesCycleSettings();
  const updateMutation = useUpdateSalesCycleSettings();

  const [form, setForm] = useState<SalesCycleSettings>(DEFAULTS);

  useEffect(() => {
    if (settings) setForm(settings);
  }, [settings]);

  const handleCycleTypeChange = (cycleType: string) => {
    const preset = PRESETS[cycleType as (typeof CYCLE_TYPES)[number]];
    setForm((prev) => ({ ...prev, cycleType, ...preset }));
  };

  const handleSave = async () => {
    try {
      await updateMutation.mutateAsync(form);
      showToast(t('salesCycleSettings.saveSuccess'), 'success');
    } catch (error) {
      const message = getFieldErrorMessage(error);
      if (message) showToast(message, 'error');
    }
  };

  if (isLoading) {
    return <div>{t('common.loading')}</div>;
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
      <h2 style={{ margin: 0 }}>{t('salesCycleSettings.title')}</h2>
      <ActionBar primary={{ key: 'save', label: t('common.saveChanges'), onClick: handleSave }} />

      <Card>
        <CardBody>
          <FieldWrapper label={t('salesCycleSettings.cycleType')}>
            <SearchableSelect
              style={{ minWidth: 180 }}
              value={form.cycleType}
              onChange={handleCycleTypeChange}
              options={CYCLE_TYPES.map((ct) => ({ value: ct, label: t(`salesCycleSettings.cycle${ct}`) }))}
            />
          </FieldWrapper>

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))', gap: 10, marginTop: 20 }}>
            {CHECKBOX_FIELDS.map(({ key, labelKey }) => (
              <label key={key} style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: 13.5 }}>
                <input
                  type="checkbox"
                  checked={form[key] as boolean}
                  onChange={(e) => setForm((prev) => ({ ...prev, [key]: e.target.checked }))}
                />
                {t(labelKey)}
              </label>
            ))}
          </div>
        </CardBody>
      </Card>
    </div>
  );
}
