export interface SalesCycleSettings {
  cycleType: string;
  requiresQuoteBeforeOrder: boolean;
  requiresOrderBeforeInvoice: boolean;
  requiresSeparateDeliveryDocument: boolean;
  invoiceBeforeDelivery: boolean;
  autoGenerateDownstreamDocuments: boolean;
}

export interface LoyaltyProgramSettings {
  pointsEarnRate: number;
  pointsRedemptionValue: number;
}
