using Habbak.ERP.Application.Common.Interfaces;
using Habbak.ERP.Application.Sales.Settings.Dtos;
using Habbak.ERP.Domain.Sales;
using MediatR;
using Microsoft.EntityFrameworkCore;

namespace Habbak.ERP.Application.Sales.Settings.Queries.GetSalesCycleSettings;

/// <summary>Screen #12 — one row per company; returns the entity's own defaults (Full cycle) when
/// no row has been configured yet.</summary>
public sealed record GetSalesCycleSettingsQuery : IRequest<SalesCycleSettingsDto>;

public sealed class GetSalesCycleSettingsQueryHandler(IApplicationDbContext db, ICurrentCompanyContext currentCompanyContext)
    : IRequestHandler<GetSalesCycleSettingsQuery, SalesCycleSettingsDto>
{
    public async Task<SalesCycleSettingsDto> Handle(GetSalesCycleSettingsQuery request, CancellationToken cancellationToken)
    {
        var settings = await db.SalesCycleSettingsRows
            .AsNoTracking()
            .FirstOrDefaultAsync(s => s.CompanyId == currentCompanyContext.CompanyId, cancellationToken)
            ?? new SalesCycleSettings();

        return new SalesCycleSettingsDto
        {
            CycleType = settings.CycleType.ToString(),
            RequiresQuoteBeforeOrder = settings.RequiresQuoteBeforeOrder,
            RequiresOrderBeforeInvoice = settings.RequiresOrderBeforeInvoice,
            RequiresSeparateDeliveryDocument = settings.RequiresSeparateDeliveryDocument,
            InvoiceBeforeDelivery = settings.InvoiceBeforeDelivery,
            AutoGenerateDownstreamDocuments = settings.AutoGenerateDownstreamDocuments
        };
    }
}
