using Habbak.ERP.Domain.Common;

namespace Habbak.ERP.Domain.Sales;

/// <summary>نمط دورة المبيعات (04-Module-Sales.md, section 2.6) — تسمية عرض (Preset) في واجهة
/// الإعدادات فقط، غير مقروءة من أي منطق عمل مباشرة (قاعدة 28، درس مستفاد إلزامي من تدقيق فعلي
/// لموديول المشتريات حيث انحرف `PurchaseCycleSettings.CycleType` عن الأعلام الفعلية بمرور الوقت
/// لأنه لم يكن مقروءًا من الأساس). أي Command Handler يتحقق من الأعلام الخمسة أدناه مباشرة، أبدًا
/// من قيمة هذا الـ Enum.</summary>
public enum SalesCycleType
{
    InvoiceOnly = 1,
    InvoiceWithIssue = 2,
    Full = 3,
    OrderBased = 4,
    DeliveryBased = 5,
    Simplified = 6
}

/// <summary>
/// إعدادات دورة المبيعات (04-Module-Sales.md, section 2.6) — screen #12. صف واحد لكل شركة، بنفس
/// نمط `PurchaseCycleSettings` في موديول المشتريات.
/// </summary>
public class SalesCycleSettings : AuditableEntity, ICompanyScopedEntity
{
    public long? CompanyId { get; set; }

    public SalesCycleType CycleType { get; set; } = SalesCycleType.Full;

    public bool RequiresQuoteBeforeOrder { get; set; }

    /// <summary>لو `false`، الفاتورة تُنشأ مباشرة بدون أمر بيع سابق (`SourceOrderId = null` مسموح).</summary>
    public bool RequiresOrderBeforeInvoice { get; set; } = true;

    /// <summary>لو `false`، الفاتورة نفسها تخصم `StockBalance` مباشرة. لو `true`، الخصم يتم حصريًا
    /// عبر `DeliveryOrder` منفصل (قاعدة 18).</summary>
    public bool RequiresSeparateDeliveryDocument { get; set; } = true;

    /// <summary>ذات معنى فقط لو `RequiresSeparateDeliveryDocument = true`. `true` = الفاتورة تُنشأ
    /// أولًا (`DeliveryOrder.SourceInvoiceId`)؛ `false` = أمر التسليم يسبق الفاتورة
    /// (`DeliveryOrder.SourceOrderId` ثم `SalesInvoice.SourceDeliveryOrderId`).</summary>
    public bool InvoiceBeforeDelivery { get; set; } = true;

    /// <summary>لو `true`، ترحيل المستند الأول في الدورة ينشئ ويرحّل تلقائيًا كل المستندات التالية
    /// له بدون تدخل يدوي (قاعدة 32).</summary>
    public bool AutoGenerateDownstreamDocuments { get; set; }
}
