import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { ActionBar } from '../../../ui-kit/ActionBar';
import { Card, CardBody } from '../../../ui-kit/Card';
import { FieldWrapper, Input } from '../../../ui-kit/Field';
import { SearchableSelect } from '../../../ui-kit/SearchableSelect';
import { useToastStore } from '../../../store/toastStore';
import { getFieldErrorMessage } from '../../../app/api';
import { useCodingRule } from '../../settings/codingRules/api';
import { useCreateUnitOfMeasure, useDeleteUnitOfMeasure, useUnitsOfMeasureList, useUpdateUnitOfMeasure } from './api';
import type { UnitCategory } from './api';

const categoryOptions: { value: UnitCategory; labelKey: string }[] = [
  { value: 'Weight', labelKey: 'unitsOfMeasure.categoryWeight' },
  { value: 'Volume', labelKey: 'unitsOfMeasure.categoryVolume' },
  { value: 'Count', labelKey: 'unitsOfMeasure.categoryCount' }
];

/** /inventory/units-of-measure/:id — Edit screen (standard List/Edit pattern, 00-Frontend-Specs.md, section 5-7). */
export function UnitOfMeasureEditPage() {
  const { t } = useTranslation();
  const { id } = useParams();
  const isNew = id === 'new';
  const unitId = isNew ? undefined : Number(id);
  const navigate = useNavigate();
  const showToast = useToastStore((s) => s.show);

  const { data: units, isLoading } = useUnitsOfMeasureList();
  const unit = units?.find((u) => u.id === unitId);
  const { data: codingRule } = useCodingRule('INVENTORY_UNITS_OF_MEASURE');
  const codeIsAutomatic = codingRule?.isAutomatic ?? false;

  const [code, setCode] = useState('');
  const [nameAr, setNameAr] = useState('');
  const [nameEn, setNameEn] = useState('');
  const [category, setCategory] = useState<UnitCategory>('Count');
  const [isActive, setIsActive] = useState(true);

  useEffect(() => {
    if (unit) {
      setNameAr(unit.nameAr);
      setNameEn(unit.nameEn);
      setCategory(unit.category);
      setIsActive(unit.isActive);
    }
  }, [unit]);

  const createMutation = useCreateUnitOfMeasure();
  const updateMutation = useUpdateUnitOfMeasure(unitId ?? 0);
  const deleteMutation = useDeleteUnitOfMeasure();

  const handleSave = async () => {
    try {
      if (isNew) {
        const { id: newId } = await createMutation.mutateAsync({ code: codeIsAutomatic ? undefined : code, nameAr, nameEn, category });
        showToast(t('unitsOfMeasure.createSuccess'), 'success');
        navigate(`/inventory/units-of-measure/${newId}`);
      } else {
        await updateMutation.mutateAsync({ nameAr, nameEn, category, isActive });
        showToast(t('unitsOfMeasure.updateSuccess'), 'success');
      }
    } catch (error) {
      const message = getFieldErrorMessage(error);
      if (message) showToast(message, 'error');
    }
  };

  const handleDelete = async () => {
    if (!unitId) return;
    try {
      await deleteMutation.mutateAsync(unitId);
      showToast(t('unitsOfMeasure.deleteSuccess'), 'success');
      navigate('/inventory/units-of-measure');
    } catch (error) {
      const message = getFieldErrorMessage(error);
      if (message) showToast(message, 'error');
    }
  };

  if (!isNew && isLoading) {
    return <div>{t('common.loading')}</div>;
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 16, maxWidth: 640 }}>
      <h2 style={{ margin: 0 }}>{isNew ? t('unitsOfMeasure.addUnitOfMeasure') : `${t('unitsOfMeasure.title')} — ${unit?.code ?? ''}`}</h2>

      <ActionBar
        primary={{ key: 'save', label: isNew ? t('common.saveDraft') : t('common.saveChanges'), onClick: handleSave }}
        secondary={[{ key: 'back', label: t('common.back'), onClick: () => navigate('/inventory/units-of-measure') }]}
        destructive={
          !isNew
            ? [{ key: 'delete', label: t('common.remove'), onClick: handleDelete, confirmMessage: t('unitsOfMeasure.deleteConfirm') }]
            : []
        }
      />

      <Card>
        <CardBody>
          <div style={{ display: 'flex', gap: 16, flexWrap: 'wrap' }}>
            <FieldWrapper label={t('unitsOfMeasure.code')}>
              {codeIsAutomatic ? (
                <Input value={isNew ? t('codingRules.autoGeneratedPlaceholder') : (unit?.code ?? '')} disabled />
              ) : (
                <Input value={isNew ? code : (unit?.code ?? '')} onChange={(e) => setCode(e.target.value)} disabled={!isNew} />
              )}
            </FieldWrapper>

            <FieldWrapper label={t('unitsOfMeasure.nameAr')}>
              <Input value={nameAr} onChange={(e) => setNameAr(e.target.value)} style={{ minWidth: 200 }} />
            </FieldWrapper>

            <FieldWrapper label={t('unitsOfMeasure.nameEn')}>
              <Input value={nameEn} onChange={(e) => setNameEn(e.target.value)} style={{ minWidth: 200 }} />
            </FieldWrapper>

            <FieldWrapper label={t('unitsOfMeasure.category')}>
              <SearchableSelect
                value={category}
                onChange={(v) => setCategory(v as UnitCategory)}
                options={categoryOptions.map((o) => ({ value: o.value, label: t(o.labelKey) }))}
                style={{ minWidth: 140 }}
              />
            </FieldWrapper>

            {!isNew && (
              <FieldWrapper label={t('unitsOfMeasure.isActive')}>
                <label style={{ display: 'flex', alignItems: 'center', gap: 6, height: 38 }}>
                  <input type="checkbox" checked={isActive} onChange={(e) => setIsActive(e.target.checked)} />
                </label>
              </FieldWrapper>
            )}
          </div>
        </CardBody>
      </Card>
    </div>
  );
}
