using Habbak.ERP.Application.Common.Exceptions;
using Habbak.ERP.Application.Common.Interfaces;
using Habbak.ERP.Domain.Accounting;
using MediatR;

namespace Habbak.ERP.Application.Accounting.JournalEntries.Commands.DeleteJournalEntry;

/// <summary>
/// Soft-deletes a manual Draft entry (00-Project-Overview.md, section 16). Only a Draft,
/// non-automated entry may be deleted — a Posted one must be reversed instead (rule 4), and an
/// automated one is never touched manually at all.
/// </summary>
public sealed record DeleteJournalEntryCommand(long Id) : IRequest;

public sealed class DeleteJournalEntryCommandHandler(IApplicationDbContext db) : IRequestHandler<DeleteJournalEntryCommand>
{
    public async Task Handle(DeleteJournalEntryCommand request, CancellationToken cancellationToken)
    {
        var entry = await db.JournalEntries.FindAsync([request.Id], cancellationToken)
            ?? throw new NotFoundException(nameof(JournalEntry), request.Id);

        if (entry.IsAutoGenerated)
        {
            throw new BusinessRuleException(
                "ACC-R4-AUTO-ENTRY-READONLY", "القيود الآلية لا يمكن حذفها يدويًا.");
        }

        if (entry.Status != JournalEntryStatus.Draft)
        {
            throw new BusinessRuleException(
                "ACC-ENTRY-NOT-DRAFT", "لا يمكن حذف قيد إلا وهو في حالة مسودة — القيد المرحّل يُعكس بدل حذفه.");
        }

        db.JournalEntries.Remove(entry);
        await db.SaveChangesAsync(cancellationToken);
    }
}
