import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { ActionBar } from '../../../ui-kit/ActionBar';
import { Card, CardBody } from '../../../ui-kit/Card';
import { FieldWrapper, Input } from '../../../ui-kit/Field';
import { useToastStore } from '../../../store/toastStore';
import { getFieldErrorMessage } from '../../../app/api';
import { useCodingRule } from '../../settings/codingRules/api';
import { useBlendTypesList, useCreateBlendType, useDeleteBlendType, useUpdateBlendType } from './api';

/** /pos/blend-types/:id — Edit screen (نمط List/Edit القياسي). */
export function BlendTypeEditPage() {
  const { t } = useTranslation();
  const { id } = useParams();
  const isNew = id === 'new';
  const blendTypeId = isNew ? undefined : Number(id);
  const navigate = useNavigate();
  const showToast = useToastStore((s) => s.show);

  const { data: blendTypes, isLoading } = useBlendTypesList();
  const blendType = blendTypes?.find((b) => b.id === blendTypeId);
  const { data: codingRule } = useCodingRule('POS_BLEND_TYPES');
  const codeIsAutomatic = codingRule?.isAutomatic ?? false;

  const [code, setCode] = useState('');
  const [nameAr, setNameAr] = useState('');
  const [nameEn, setNameEn] = useState('');
  const [pricePerGram, setPricePerGram] = useState('');
  const [isActive, setIsActive] = useState(true);

  useEffect(() => {
    if (blendType) {
      setNameAr(blendType.nameAr);
      setNameEn(blendType.nameEn);
      setPricePerGram(String(blendType.pricePerGram));
      setIsActive(blendType.isActive);
    }
  }, [blendType]);

  const createMutation = useCreateBlendType();
  const updateMutation = useUpdateBlendType(blendTypeId ?? 0);
  const deleteMutation = useDeleteBlendType();

  const handleSave = async () => {
    try {
      if (isNew) {
        const { id: newId } = await createMutation.mutateAsync({
          code: codeIsAutomatic ? undefined : code, nameAr, nameEn, pricePerGram: Number(pricePerGram) || 0
        });
        showToast(t('blendTypes.createSuccess'), 'success');
        navigate(`/pos/blend-types/${newId}`);
      } else {
        await updateMutation.mutateAsync({ nameAr, nameEn, pricePerGram: Number(pricePerGram) || 0, isActive });
        showToast(t('blendTypes.updateSuccess'), 'success');
      }
    } catch (error) {
      const message = getFieldErrorMessage(error);
      if (message) showToast(message, 'error');
    }
  };

  const handleDelete = async () => {
    if (!blendTypeId) return;
    try {
      await deleteMutation.mutateAsync(blendTypeId);
      showToast(t('blendTypes.deleteSuccess'), 'success');
      navigate('/pos/blend-types');
    } catch (error) {
      const message = getFieldErrorMessage(error);
      if (message) showToast(message, 'error');
    }
  };

  if (!isNew && isLoading) {
    return <div>{t('common.loading')}</div>;
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 16, maxWidth: 640 }}>
      <h2 style={{ margin: 0 }}>{isNew ? t('blendTypes.addBlendType') : `${t('blendTypes.title')} — ${blendType?.code ?? ''}`}</h2>

      <ActionBar
        primary={{ key: 'save', label: isNew ? t('common.saveDraft') : t('common.saveChanges'), onClick: handleSave }}
        secondary={[{ key: 'back', label: t('common.back'), onClick: () => navigate('/pos/blend-types') }]}
        destructive={
          !isNew
            ? [{ key: 'delete', label: t('common.remove'), onClick: handleDelete, confirmMessage: t('blendTypes.deleteConfirm') }]
            : []
        }
      />

      <Card>
        <CardBody>
          <div style={{ display: 'flex', gap: 16, flexWrap: 'wrap' }}>
            <FieldWrapper label={t('blendTypes.code')}>
              {codeIsAutomatic ? (
                <Input value={isNew ? t('codingRules.autoGeneratedPlaceholder') : (blendType?.code ?? '')} disabled />
              ) : (
                <Input value={isNew ? code : (blendType?.code ?? '')} onChange={(e) => setCode(e.target.value)} disabled={!isNew} />
              )}
            </FieldWrapper>

            <FieldWrapper label={t('blendTypes.nameAr')}>
              <Input value={nameAr} onChange={(e) => setNameAr(e.target.value)} style={{ minWidth: 200 }} />
            </FieldWrapper>

            <FieldWrapper label={t('blendTypes.nameEn')}>
              <Input value={nameEn} onChange={(e) => setNameEn(e.target.value)} style={{ minWidth: 200 }} />
            </FieldWrapper>

            <FieldWrapper label={t('blendTypes.pricePerGram')}>
              <Input type="number" step="0.01" min={0} value={pricePerGram} onChange={(e) => setPricePerGram(e.target.value)} style={{ width: 120 }} />
            </FieldWrapper>

            {!isNew && (
              <FieldWrapper label={t('blendTypes.isActive')}>
                <label style={{ display: 'flex', alignItems: 'center', gap: 6, height: 38 }}>
                  <input type="checkbox" checked={isActive} onChange={(e) => setIsActive(e.target.checked)} />
                </label>
              </FieldWrapper>
            )}
          </div>
        </CardBody>
      </Card>
    </div>
  );
}
