namespace Habbak.ERP.Application.Accounting.JournalEntries.Dtos;

public sealed class JournalEntryListItemDto
{
    public required long Id { get; init; }
    public required string EntryNumber { get; init; }
    public required DateOnly EntryDate { get; init; }
    public required string Description { get; init; }
    public required string SourceModule { get; init; }
    public required bool IsAutoGenerated { get; init; }
    public required decimal TotalDebit { get; init; }
    public required decimal TotalCredit { get; init; }
    public required string Status { get; init; }
}

public sealed class JournalEntryDetailDto
{
    public required long Id { get; init; }
    public Guid? PublicId { get; init; }
    public long? BranchId { get; init; }
    public required string EntryNumber { get; init; }
    public required DateOnly EntryDate { get; init; }
    public required string Description { get; init; }
    public required string SourceModule { get; init; }
    public string? SourceDocumentType { get; init; }
    public long? SourceDocumentId { get; init; }
    public required string Status { get; init; }
    public required bool IsAutoGenerated { get; init; }
    public long? ReversalOfEntryId { get; init; }
    public required decimal TotalDebit { get; init; }
    public required decimal TotalCredit { get; init; }
    public long? ApprovalInstanceId { get; init; }
    public DateTime? PostedAtUtc { get; init; }

    /// <summary>Base64-encoded RowVersion — sent back on PUT/Post for optimistic concurrency (00-Frontend-Specs.md, section 7).</summary>
    public required string RowVersion { get; init; }

    public required IReadOnlyList<JournalEntryLineDto> Lines { get; init; }
}

public sealed class JournalEntryLineDto
{
    public long? Id { get; init; }
    public required int LineNumber { get; init; }
    public required long AccountId { get; init; }
    public required decimal DebitAmount { get; init; }
    public required decimal CreditAmount { get; init; }
    public required string CurrencyCode { get; init; }
    public required decimal ExchangeRate { get; init; }
    public required decimal BaseCurrencyDebitAmount { get; init; }
    public required decimal BaseCurrencyCreditAmount { get; init; }
    public string? Description { get; init; }

    /// <summary>CostCenterDimensionId -> CostCenterDimensionValueId.</summary>
    public IReadOnlyDictionary<long, long> DimensionValues { get; init; } = new Dictionary<long, long>();
}
