using Habbak.ERP.Application.Common.Exceptions;
using Habbak.ERP.Application.Common.Interfaces;
using Habbak.ERP.Domain.Payroll;
using MediatR;
using Microsoft.EntityFrameworkCore;

namespace Habbak.ERP.Application.Payroll;

// Docs/Implementation/HR-MASTER-PLAN.md §Phase 4, Sub-Batch 4.6 — screen PAY_PAYSLIPS. Read-only:
// Payslip rows are generated by PostPayrollRunCommandHandler (Sub-Batch 4.5/4.6) when a run reaches
// Posted, never created or edited directly here (rule 29/38 — a payslip is a frozen record).

public sealed record PayslipDto(
    long Id, long PayrollRunId, long EmployeeId, decimal Gross, decimal TotalDeductions, decimal Net, DateTime IssuedAtUtc, DateTime? ViewedAtUtc);

/// <summary>Both filters optional — omit both for "every payslip this company has issued" (an HR-wide
/// list), pass PayrollRunId for one run's payslips, or EmployeeId for one employee's history
/// (the same query self-service will eventually reuse with an added Self-scope filter, Phase 6).</summary>
public sealed record GetPayslipsQuery(long? PayrollRunId, long? EmployeeId) : IRequest<IReadOnlyList<PayslipDto>>;

public sealed class GetPayslipsQueryHandler(IApplicationDbContext db) : IRequestHandler<GetPayslipsQuery, IReadOnlyList<PayslipDto>>
{
    public async Task<IReadOnlyList<PayslipDto>> Handle(GetPayslipsQuery request, CancellationToken cancellationToken) =>
        await db.Payslips.AsNoTracking()
            .Where(p => request.PayrollRunId == null || p.PayrollRunId == request.PayrollRunId)
            .Where(p => request.EmployeeId == null || p.EmployeeId == request.EmployeeId)
            .OrderByDescending(p => p.IssuedAtUtc)
            .Select(p => new PayslipDto(p.Id, p.PayrollRunId, p.EmployeeId, p.Gross, p.TotalDeductions, p.Net, p.IssuedAtUtc, p.ViewedAtUtc))
            .ToListAsync(cancellationToken);
}

public sealed record GetPayslipByIdQuery(long Id) : IRequest<PayslipDto>;

public sealed class GetPayslipByIdQueryHandler(IApplicationDbContext db) : IRequestHandler<GetPayslipByIdQuery, PayslipDto>
{
    public async Task<PayslipDto> Handle(GetPayslipByIdQuery request, CancellationToken cancellationToken)
    {
        var payslip = await db.Payslips.FirstOrDefaultAsync(p => p.Id == request.Id, cancellationToken)
            ?? throw new NotFoundException(nameof(Payslip), request.Id);

        if (payslip.ViewedAtUtc is null)
        {
            payslip.ViewedAtUtc = DateTime.UtcNow;
            await db.SaveChangesAsync(cancellationToken);
        }

        return new PayslipDto(payslip.Id, payslip.PayrollRunId, payslip.EmployeeId, payslip.Gross, payslip.TotalDeductions, payslip.Net, payslip.IssuedAtUtc, payslip.ViewedAtUtc);
    }
}
