using FluentValidation;
using Habbak.ERP.Application.Common;
using Habbak.ERP.Application.Common.Exceptions;
using Habbak.ERP.Application.Common.Interfaces;
using Habbak.ERP.Domain.Accounting;
using MediatR;
using Microsoft.EntityFrameworkCore;

namespace Habbak.ERP.Application.Accounting.JournalEntries.Commands.UpdateManualJournalEntry;

/// <summary>
/// Edits a manual Draft entry (00-Frontend-Specs.md, section 7 — Edit). Rule 4: automated
/// entries (IsAutoGenerated = true) can never be edited manually, and section 4.1 forbids
/// editing anything already Posted/Rejected/Reversed — only a Draft can change.
/// </summary>
public sealed record UpdateManualJournalEntryCommand : IRequest
{
    public required long Id { get; init; }

    /// <summary>Base64 RowVersion from the GetById response — 409 Conflict on mismatch (00-Frontend-Specs.md, section 7).</summary>
    public required string RowVersion { get; init; }

    public long? BranchId { get; init; }
    public required DateOnly EntryDate { get; init; }
    public required string Description { get; init; }
    public required IReadOnlyList<CreateManualJournalEntry.JournalEntryLineInput> Lines { get; init; }
}

public sealed class UpdateManualJournalEntryCommandValidator : AbstractValidator<UpdateManualJournalEntryCommand>
{
    public UpdateManualJournalEntryCommandValidator()
    {
        RuleFor(x => x.Id).GreaterThan(0);
        RuleFor(x => x.Description).NotEmpty().MaximumLength(500);
        RuleFor(x => x.Lines).Must(lines => lines.Count >= 2)
            .WithMessage("القيد يحتاج سطرين على الأقل.");

        RuleForEach(x => x.Lines).ChildRules(line =>
        {
            line.RuleFor(l => l.AccountId).GreaterThan(0);
            line.RuleFor(l => l.CurrencyCode).NotEmpty().Length(3);
            line.RuleFor(l => l.ExchangeRate).GreaterThan(0);
            line.RuleFor(l => l.DebitAmount).GreaterThanOrEqualTo(0);
            line.RuleFor(l => l.CreditAmount).GreaterThanOrEqualTo(0);
            line.RuleFor(l => l)
                .Must(l => (l.DebitAmount > 0) ^ (l.CreditAmount > 0))
                .WithMessage("كل سطر لازم يحمل قيمة مدين أو دائن، وليس الاثنين معًا ولا صفر.")
                .WithName("Amount");
        });
    }
}

public sealed class UpdateManualJournalEntryCommandHandler(IApplicationDbContext db, ICurrentCompanyContext currentCompanyContext)
    : IRequestHandler<UpdateManualJournalEntryCommand>
{
    public async Task Handle(UpdateManualJournalEntryCommand request, CancellationToken cancellationToken)
    {
        var entry = await db.JournalEntries
            .Include(j => j.Lines)
                .ThenInclude(l => l.DimensionValues)
            .FirstOrDefaultAsync(j => j.Id == request.Id, cancellationToken)
            ?? throw new NotFoundException(nameof(JournalEntry), request.Id);

        if (entry.IsAutoGenerated)
        {
            throw new BusinessRuleException(
                "ACC-R4-AUTO-ENTRY-READONLY", "القيود الآلية لا يمكن تعديلها يدويًا — التصحيح يكون بقيد عكسي فقط.");
        }

        if (entry.Status != JournalEntryStatus.Draft)
        {
            throw new BusinessRuleException(
                "ACC-ENTRY-NOT-DRAFT", "لا يمكن تعديل قيد إلا وهو في حالة مسودة.");
        }

        db.Entry(entry).Property(nameof(JournalEntry.RowVersion)).OriginalValue = Convert.FromBase64String(request.RowVersion);

        entry.BranchId = BranchRequirement.Resolve(request.BranchId, currentCompanyContext.BranchId);
        entry.EntryDate = request.EntryDate;
        entry.Description = request.Description;

        // Two round trips, not one: replacement lines reuse LineNumber 1, 2, 3... just like the
        // lines being replaced, and SQL Server checks the unique (JournalEntryId, LineNumber)
        // index per-statement — deleting and inserting the same LineNumber in a single
        // SaveChanges batch trips it even though the net result never actually collides.
        db.JournalEntryLines.RemoveRange(entry.Lines);
        entry.Lines.Clear();
        await db.SaveChangesAsync(cancellationToken);

        var lineNumber = 1;
        foreach (var lineInput in request.Lines)
        {
            var line = new JournalEntryLine
            {
                LineNumber = lineNumber++,
                AccountId = lineInput.AccountId,
                DebitAmount = lineInput.DebitAmount,
                CreditAmount = lineInput.CreditAmount,
                CurrencyCode = lineInput.CurrencyCode,
                ExchangeRate = lineInput.ExchangeRate,
                BaseCurrencyDebitAmount = lineInput.BaseCurrencyDebitAmount,
                BaseCurrencyCreditAmount = lineInput.BaseCurrencyCreditAmount,
                Description = lineInput.Description
            };

            foreach (var (dimensionId, valueId) in lineInput.DimensionValues)
            {
                line.DimensionValues.Add(new JournalEntryLineDimensionValue
                {
                    CostCenterDimensionId = dimensionId,
                    CostCenterDimensionValueId = valueId
                });
            }

            entry.Lines.Add(line);
        }

        entry.TotalDebit = request.Lines.Sum(l => l.DebitAmount);
        entry.TotalCredit = request.Lines.Sum(l => l.CreditAmount);

        await db.SaveChangesAsync(cancellationToken);
    }
}
