using Habbak.ERP.Application.Common.Exceptions;
using Habbak.ERP.Application.Common.Interfaces;
using Habbak.ERP.Application.Common.Models;
using Habbak.ERP.Domain.Accounting;
using Habbak.ERP.Domain.Purchasing;
using Habbak.ERP.Domain.Sales;
using Habbak.ERP.Shared.Enums;
using MediatR;
using Microsoft.EntityFrameworkCore;

namespace Habbak.ERP.Application.Accounting.Vouchers.Commands.PostVoucher;

/// <summary>
/// Posts a Draft voucher: builds its double-entry PostingRequest and posts it through the
/// central engine, in the SAME SaveChangesAsync call as the Voucher's own status/JournalEntry
/// update — the atomicity rule 5 explicitly requires (01-Module-Accounting.md, rule 5).
///
/// A Payment voucher against CounterpartyType.Supplier with a RelatedInvoiceId also applies its
/// Amount to that PurchaseInvoice's AmountPaid and advances its Status (03-Module-Purchasing.md,
/// screen #9 "سداد الموردين" — no dedicated SupplierPayment entity exists; this IS that feature,
/// layered on the Voucher screen already built for section 2.3 of the Accounting module).
/// </summary>
public sealed record PostVoucherCommand(long Id) : IRequest<PostVoucherResult>;

public sealed record PostVoucherResult(string Status, long? ApprovalInstanceId);

public sealed class PostVoucherCommandHandler(
    IApplicationDbContext db,
    IPostingService postingService,
    ICounterpartyAccountResolver counterpartyAccountResolver)
    : IRequestHandler<PostVoucherCommand, PostVoucherResult>
{
    public async Task<PostVoucherResult> Handle(PostVoucherCommand request, CancellationToken cancellationToken)
    {
        var voucher = await db.Vouchers.FirstOrDefaultAsync(v => v.Id == request.Id, cancellationToken)
            ?? throw new NotFoundException(nameof(Voucher), request.Id);

        if (voucher.Status != VoucherStatus.Draft)
        {
            throw new BusinessRuleException("ACC-VOUCHER-NOT-DRAFT", "لا يمكن ترحيل سند إلا وهو في حالة مسودة.");
        }

        var offsetAccountId = voucher.CounterpartyType == CounterpartyType.Other
            ? voucher.DirectAccountId!.Value
            : await counterpartyAccountResolver.ResolveAccountIdAsync(
                voucher.CounterpartyType, voucher.CounterpartyId!.Value, cancellationToken);

        var isReceipt = voucher.VoucherType == VoucherType.Receipt;

        // Receipt: Debit Treasury / Credit the offset account. Payment: the mirror image
        // (01-Module-Accounting.md, section 2.3 field docs).
        var postingRequest = new PostingRequest
        {
            CompanyId = voucher.CompanyId!.Value,
            BranchId = voucher.BranchId,
            EntryDate = voucher.VoucherDate,
            Description = $"{(isReceipt ? "سند قبض" : "سند صرف")} رقم {voucher.VoucherNumber}"
                + (string.IsNullOrWhiteSpace(voucher.Description) ? "" : $" - {voucher.Description}"),
            SourceModule = SourceModule.Manual,
            SourceDocumentType = isReceipt ? SourceDocumentType.ReceiptVoucher : SourceDocumentType.PaymentVoucher,
            SourceDocumentId = voucher.Id,
            // Rule 5: this entry is a direct, automatic consequence of posting the voucher — not
            // separately user-editable afterward, matching every other IsAutoGenerated entry.
            IsAutoGenerated = true,
            Lines =
            [
                new PostingLineRequest
                {
                    AccountId = voucher.TreasuryAccountId,
                    DebitAmount = isReceipt ? voucher.Amount : 0m,
                    CreditAmount = isReceipt ? 0m : voucher.Amount,
                    CurrencyCode = voucher.CurrencyCode,
                    ExchangeRate = voucher.ExchangeRate,
                    BaseCurrencyDebitAmount = isReceipt ? voucher.BaseCurrencyAmount : 0m,
                    BaseCurrencyCreditAmount = isReceipt ? 0m : voucher.BaseCurrencyAmount
                },
                new PostingLineRequest
                {
                    AccountId = offsetAccountId,
                    DebitAmount = isReceipt ? 0m : voucher.Amount,
                    CreditAmount = isReceipt ? voucher.Amount : 0m,
                    CurrencyCode = voucher.CurrencyCode,
                    ExchangeRate = voucher.ExchangeRate,
                    BaseCurrencyDebitAmount = isReceipt ? 0m : voucher.BaseCurrencyAmount,
                    BaseCurrencyCreditAmount = isReceipt ? voucher.BaseCurrencyAmount : 0m
                }
            ]
        };

        var result = await postingService.PostAsync(postingRequest, cancellationToken);

        // Navigation-property fixup: JournalEntry.Id may not exist yet (not saved), but EF Core
        // resolves the FK automatically at SaveChanges — see IPostingService's XML doc.
        voucher.JournalEntry = result.JournalEntry;
        voucher.Status = result.Status == JournalEntryStatus.Posted ? VoucherStatus.Posted : VoucherStatus.Draft;

        // A supplier payment spread over several invoices (Remarks4, item 7) applies each
        // allocation to its own invoice. The single-invoice path below still runs for a payment
        // that was never allocated — older vouchers, and payments that name one invoice.
        var appliedAllocations = false;
        if (voucher.Status == VoucherStatus.Posted && !isReceipt && voucher.CounterpartyType == CounterpartyType.Supplier)
        {
            var allocations = await db.SupplierPaymentAllocations
                .Include(a => a.PurchaseInvoice)
                .Where(a => a.VoucherId == voucher.Id)
                .ToListAsync(cancellationToken);

            foreach (var allocation in allocations)
            {
                var allocated = allocation.PurchaseInvoice!;
                if (voucher.CurrencyCode != allocated.CurrencyCode)
                {
                    throw new BusinessRuleException(
                        "PAY-VOUCHER-CURRENCY-MISMATCH",
                        $"عملة سند الدفع ({voucher.CurrencyCode}) لا تطابق عملة الفاتورة ({allocated.CurrencyCode}) — لا يمكن السداد بعملة مختلفة عن عملة الفاتورة.");
                }

                if (allocation.Amount > allocated.TotalAmount - allocated.AmountPaid)
                {
                    throw new BusinessRuleException(
                        "PUR-PAYMENT-EXCEEDS-OUTSTANDING",
                        $"المتبقي على الفاتورة {allocated.InvoiceNumber} اتغيّر بعد التوزيع — راجع توزيع السداد قبل الترحيل.");
                }

                allocated.AmountPaid += allocation.Amount;
                allocated.Status = allocated.AmountPaid >= allocated.TotalAmount ? PurchaseInvoiceStatus.Paid : PurchaseInvoiceStatus.PartiallyPaid;
                appliedAllocations = true;
            }
        }

        // A supplier payment voucher that just posted applies its amount against the invoice it
        // settles (03-Module-Purchasing.md, rule 8) — PartiallyPaid/Paid, never past TotalAmount.
        if (!appliedAllocations && voucher.Status == VoucherStatus.Posted && !isReceipt
            && voucher.CounterpartyType == CounterpartyType.Supplier && voucher.RelatedInvoiceId is { } invoiceId)
        {
            var invoice = await db.PurchaseInvoices.FirstOrDefaultAsync(i => i.Id == invoiceId, cancellationToken);
            if (invoice is not null && invoice.Status is PurchaseInvoiceStatus.Posted or PurchaseInvoiceStatus.PartiallyPaid)
            {
                // Amount is in the voucher's own currency and TotalAmount/AmountPaid are in the
                // invoice's own currency — neither entity carries a base-currency-equivalent field
                // to convert through, so a mismatched currency here would silently misapply the
                // payment's face value. Require the two to match rather than convert blindly.
                if (voucher.CurrencyCode != invoice.CurrencyCode)
                {
                    throw new BusinessRuleException(
                        "PAY-VOUCHER-CURRENCY-MISMATCH",
                        $"عملة سند الدفع ({voucher.CurrencyCode}) لا تطابق عملة الفاتورة ({invoice.CurrencyCode}) — لا يمكن السداد بعملة مختلفة عن عملة الفاتورة.");
                }

                invoice.AmountPaid += voucher.Amount;
                invoice.Status = invoice.AmountPaid >= invoice.TotalAmount ? PurchaseInvoiceStatus.Paid : PurchaseInvoiceStatus.PartiallyPaid;
            }
        }

        // A customer receipt voucher that just posted applies its amount against the invoice it
        // settles (04-Module-Sales.md, screen #10 "التحصيلات" — same no-dedicated-entity pattern as
        // Purchasing's supplier payments, layered on this same Voucher screen). Unlike
        // PurchaseInvoiceStatus, SalesInvoiceStatus has no PartiallyPaid/Paid states (not part of
        // the spec's own enum for this document) — only AmountPaid moves, Status stays Posted.
        if (voucher.Status == VoucherStatus.Posted && isReceipt
            && voucher.CounterpartyType == CounterpartyType.Customer && voucher.RelatedInvoiceId is { } salesInvoiceId)
        {
            var salesInvoice = await db.SalesInvoices.FirstOrDefaultAsync(i => i.Id == salesInvoiceId, cancellationToken);
            if (salesInvoice is not null && salesInvoice.Status == SalesInvoiceStatus.Posted)
            {
                // SalesInvoice carries no CurrencyCode of its own (04-Module-Sales.md's field table
                // never gives it one — every Sales document is implicitly single-currency, unlike
                // Purchasing) — so it's implicitly in the company's own base currency. Same
                // currency-safety reasoning as Bug #1 (Docs/Notes-Purchasing-QA.md): applying a
                // voucher's face value across a currency boundary with no conversion would silently
                // misapply it, so require the voucher to actually be in that base currency.
                var baseCurrencyCode = await db.Companies
                    .Where(c => c.Id == voucher.CompanyId)
                    .Select(c => c.BaseCurrency.Code)
                    .FirstOrDefaultAsync(cancellationToken);

                if (baseCurrencyCode is not null && voucher.CurrencyCode != baseCurrencyCode)
                {
                    throw new BusinessRuleException(
                        "REC-VOUCHER-CURRENCY-MISMATCH",
                        $"عملة سند القبض ({voucher.CurrencyCode}) لا تطابق العملة الأساسية للشركة ({baseCurrencyCode}) — لا يمكن التحصيل بعملة مختلفة عن عملة فاتورة المبيعات.");
                }

                salesInvoice.AmountPaid += voucher.Amount;
            }
        }

        await db.SaveChangesAsync(cancellationToken);

        return new PostVoucherResult(voucher.Status.ToString(), result.ApprovalInstanceId);
    }
}
