import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { ActionBar } from '../../../ui-kit/ActionBar';
import { Card, CardBody } from '../../../ui-kit/Card';
import { FieldWrapper, Input } from '../../../ui-kit/Field';
import { SearchableSelect } from '../../../ui-kit/SearchableSelect';
import { useToastStore } from '../../../store/toastStore';
import { getFieldErrorMessage } from '../../../app/api';
import { useCodingRule } from '../../settings/codingRules/api';
import { useCreateItemGroup, useDeleteItemGroup, useItemGroupsList, useUpdateItemGroup } from './api';

/** /inventory/item-groups/:id — Edit screen (standard List/Edit pattern, 00-Frontend-Specs.md, section 5-7). */
export function ItemGroupEditPage() {
  const { t } = useTranslation();
  const { id } = useParams();
  const isNew = id === 'new';
  const groupId = isNew ? undefined : Number(id);
  const navigate = useNavigate();
  const showToast = useToastStore((s) => s.show);

  const { data: groups, isLoading } = useItemGroupsList();
  const group = groups?.find((g) => g.id === groupId);
  const { data: codingRule } = useCodingRule('INVENTORY_ITEM_GROUPS');
  const codeIsAutomatic = codingRule?.isAutomatic ?? false;

  const [code, setCode] = useState('');
  const [nameAr, setNameAr] = useState('');
  const [nameEn, setNameEn] = useState('');
  const [parentId, setParentId] = useState<number | ''>('');
  const [isActive, setIsActive] = useState(true);

  useEffect(() => {
    if (group) {
      setNameAr(group.nameAr);
      setNameEn(group.nameEn);
      setParentId(group.parentId ?? '');
      setIsActive(group.isActive);
    }
  }, [group]);

  const createMutation = useCreateItemGroup();
  const updateMutation = useUpdateItemGroup(groupId ?? 0);
  const deleteMutation = useDeleteItemGroup();

  const parentOptions = [
    { value: '', label: t('itemGroups.none') },
    ...(groups ?? []).filter((g) => g.id !== groupId).map((g) => ({ value: g.id, label: g.nameAr }))
  ];

  const handleSave = async () => {
    try {
      const resolvedParentId = parentId === '' ? null : Number(parentId);
      if (isNew) {
        const { id: newId } = await createMutation.mutateAsync({ code: codeIsAutomatic ? undefined : code, nameAr, nameEn, parentId: resolvedParentId });
        showToast(t('itemGroups.createSuccess'), 'success');
        navigate(`/inventory/item-groups/${newId}`);
      } else {
        await updateMutation.mutateAsync({ nameAr, nameEn, parentId: resolvedParentId, isActive });
        showToast(t('itemGroups.updateSuccess'), 'success');
      }
    } catch (error) {
      const message = getFieldErrorMessage(error);
      if (message) showToast(message, 'error');
    }
  };

  const handleDelete = async () => {
    if (!groupId) return;
    try {
      await deleteMutation.mutateAsync(groupId);
      showToast(t('itemGroups.deleteSuccess'), 'success');
      navigate('/inventory/item-groups');
    } catch (error) {
      const message = getFieldErrorMessage(error);
      if (message) showToast(message, 'error');
    }
  };

  if (!isNew && isLoading) {
    return <div>{t('common.loading')}</div>;
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 16, maxWidth: 640 }}>
      <h2 style={{ margin: 0 }}>{isNew ? t('itemGroups.addItemGroup') : `${t('itemGroups.title')} — ${group?.code ?? ''}`}</h2>

      <ActionBar
        primary={{ key: 'save', label: isNew ? t('common.saveDraft') : t('common.saveChanges'), onClick: handleSave }}
        secondary={[{ key: 'back', label: t('common.back'), onClick: () => navigate('/inventory/item-groups') }]}
        destructive={
          !isNew
            ? [{ key: 'delete', label: t('common.remove'), onClick: handleDelete, confirmMessage: t('itemGroups.deleteConfirm') }]
            : []
        }
      />

      <Card>
        <CardBody>
          <div style={{ display: 'flex', gap: 16, flexWrap: 'wrap' }}>
            <FieldWrapper label={t('itemGroups.code')}>
              {codeIsAutomatic ? (
                <Input value={isNew ? t('codingRules.autoGeneratedPlaceholder') : (group?.code ?? '')} disabled />
              ) : (
                <Input value={isNew ? code : (group?.code ?? '')} onChange={(e) => setCode(e.target.value)} disabled={!isNew} />
              )}
            </FieldWrapper>

            <FieldWrapper label={t('itemGroups.nameAr')}>
              <Input value={nameAr} onChange={(e) => setNameAr(e.target.value)} style={{ minWidth: 200 }} />
            </FieldWrapper>

            <FieldWrapper label={t('itemGroups.nameEn')}>
              <Input value={nameEn} onChange={(e) => setNameEn(e.target.value)} style={{ minWidth: 200 }} />
            </FieldWrapper>

            <FieldWrapper label={t('itemGroups.parent')}>
              <SearchableSelect
                value={parentId}
                onChange={(v) => setParentId(v === '' ? '' : Number(v))}
                options={parentOptions}
                style={{ minWidth: 200 }}
              />
            </FieldWrapper>

            {!isNew && (
              <FieldWrapper label={t('itemGroups.isActive')}>
                <label style={{ display: 'flex', alignItems: 'center', gap: 6, height: 38 }}>
                  <input type="checkbox" checked={isActive} onChange={(e) => setIsActive(e.target.checked)} />
                </label>
              </FieldWrapper>
            )}
          </div>
        </CardBody>
      </Card>
    </div>
  );
}
