using Habbak.ERP.Application.Common.Interfaces;
using Habbak.ERP.Application.Posting.Screens;
using Habbak.ERP.Domain.Accounting;
using Habbak.ERP.Domain.Inventory;
using Habbak.ERP.Domain.POS;
using Habbak.ERP.Domain.Purchasing;
using Habbak.ERP.Domain.Sales;
using Habbak.ERP.Shared.Enums;
using MediatR;
using Microsoft.EntityFrameworkCore;

namespace Habbak.ERP.Application.Posting.Reports;

// The posting engine's reports (00-Posting-Engine-Architecture.md section 10), plus the one the
// "activation = active template" design calls for: documents that posted with no entry.

// ---------------------------------------------------------------------------- 1. automatic entries

public sealed record AutoEntryRow(
    long Id, string EntryNumber, DateOnly EntryDate, string SourceModule, string? SourceDocumentType, long? SourceDocumentId,
    long? BranchId, string Description, decimal Total, string Status, bool IsReversal, string? ScreenCode, int? TemplateVersion);

public sealed record GetAutoEntriesReportQuery(DateOnly From, DateOnly To, string? SourceModule = null, long? BranchId = null)
    : IRequest<IReadOnlyList<AutoEntryRow>>;

public sealed class GetAutoEntriesReportQueryHandler(IApplicationDbContext db) : IRequestHandler<GetAutoEntriesReportQuery, IReadOnlyList<AutoEntryRow>>
{
    public async Task<IReadOnlyList<AutoEntryRow>> Handle(GetAutoEntriesReportQuery request, CancellationToken cancellationToken)
    {
        var module = Enum.TryParse<SourceModule>(request.SourceModule, out var m) ? m : (SourceModule?)null;

        var rows = await db.JournalEntries.AsNoTracking()
            .Where(e => e.IsAutoGenerated && e.EntryDate >= request.From && e.EntryDate <= request.To)
            .Where(e => module == null || e.SourceModule == module)
            .Where(e => request.BranchId == null || e.BranchId == request.BranchId)
            .OrderByDescending(e => e.EntryDate).ThenByDescending(e => e.Id)
            .Select(e => new
            {
                e.Id, e.EntryNumber, e.EntryDate, e.SourceModule, e.SourceDocumentType, e.SourceDocumentId, e.BranchId,
                e.Description, e.TotalDebit, e.Status, e.ReversalOfEntryId
            })
            .Take(2000)
            .ToListAsync(cancellationToken);

        var ids = rows.Select(r => r.Id).ToList();
        var snapshots = await db.JournalEntryTemplateSnapshots.AsNoTracking()
            .Where(s => ids.Contains(s.JournalEntryId))
            .Join(db.PostingTemplates, s => s.PostingTemplateId, t => t.Id, (s, t) => new { s.JournalEntryId, t.ScreenCode, s.TemplateVersionNumber })
            .ToDictionaryAsync(s => s.JournalEntryId, cancellationToken);

        return rows.Select(r => new AutoEntryRow(
            r.Id, r.EntryNumber, r.EntryDate, r.SourceModule.ToString(), r.SourceDocumentType?.ToString(), r.SourceDocumentId, r.BranchId,
            r.Description, r.TotalDebit, r.Status.ToString(), r.ReversalOfEntryId is not null,
            snapshots.GetValueOrDefault(r.Id)?.ScreenCode, snapshots.GetValueOrDefault(r.Id)?.TemplateVersionNumber)).ToList();
    }
}

// ---------------------------------------------------------------------------- 2. failed postings

public sealed record PostingFailureRow(
    long Id, DateTime OccurredAtUtc, string ScreenCode, string ScreenNameAr, string SourceModule, long SourceDocumentId,
    long? BranchId, string Description, string ErrorCode, string ErrorMessage, bool IsResolved, DateTime? ResolvedAtUtc,
    string? ResolvedByEntryNumber);

public sealed record GetPostingFailuresReportQuery(bool IncludeResolved = false) : IRequest<IReadOnlyList<PostingFailureRow>>;

public sealed class GetPostingFailuresReportQueryHandler(IApplicationDbContext db)
    : IRequestHandler<GetPostingFailuresReportQuery, IReadOnlyList<PostingFailureRow>>
{
    public async Task<IReadOnlyList<PostingFailureRow>> Handle(GetPostingFailuresReportQuery request, CancellationToken cancellationToken)
    {
        var rows = await db.PostingFailures.AsNoTracking()
            .Where(f => request.IncludeResolved || !f.IsResolved)
            .OrderByDescending(f => f.OccurredAtUtc)
            .Select(f => new
            {
                f.Id, f.OccurredAtUtc, f.ScreenCode, f.SourceModule, f.SourceDocumentId, f.BranchId, f.Description,
                f.ErrorCode, f.ErrorMessage, f.IsResolved, f.ResolvedAtUtc,
                ResolvedBy = f.ResolvedByJournalEntry != null ? f.ResolvedByJournalEntry.EntryNumber : null
            })
            .Take(2000)
            .ToListAsync(cancellationToken);

        return rows.Select(f => new PostingFailureRow(
            f.Id, f.OccurredAtUtc, f.ScreenCode, PostingScreenCatalog.Find(f.ScreenCode)?.NameAr ?? f.ScreenCode, f.SourceModule.ToString(),
            f.SourceDocumentId, f.BranchId, f.Description, f.ErrorCode, f.ErrorMessage, f.IsResolved, f.ResolvedAtUtc, f.ResolvedBy)).ToList();
    }
}

// ---------------------------------------------------------------------------- 3. by source

public sealed record EntriesBySourceRow(string SourceModule, string? SourceDocumentType, int EntryCount, decimal Total, int ReversalCount);

public sealed record GetEntriesBySourceReportQuery(DateOnly From, DateOnly To) : IRequest<IReadOnlyList<EntriesBySourceRow>>;

public sealed class GetEntriesBySourceReportQueryHandler(IApplicationDbContext db)
    : IRequestHandler<GetEntriesBySourceReportQuery, IReadOnlyList<EntriesBySourceRow>>
{
    public async Task<IReadOnlyList<EntriesBySourceRow>> Handle(GetEntriesBySourceReportQuery request, CancellationToken cancellationToken)
    {
        var rows = await db.JournalEntries.AsNoTracking()
            .Where(e => e.Status == JournalEntryStatus.Posted && e.EntryDate >= request.From && e.EntryDate <= request.To)
            .GroupBy(e => new { e.SourceModule, e.SourceDocumentType })
            .Select(g => new
            {
                g.Key.SourceModule, g.Key.SourceDocumentType, Count = g.Count(), Total = g.Sum(e => e.TotalDebit),
                Reversals = g.Count(e => e.ReversalOfEntryId != null)
            })
            .ToListAsync(cancellationToken);

        return rows
            .OrderBy(r => r.SourceModule).ThenBy(r => r.SourceDocumentType)
            .Select(r => new EntriesBySourceRow(r.SourceModule.ToString(), r.SourceDocumentType?.ToString(), r.Count, r.Total, r.Reversals))
            .ToList();
    }
}

// ---------------------------------------------------------------------------- 4. POS entries

public sealed record POSEntryRow(
    long EntryId, string EntryNumber, DateOnly EntryDate, long? BranchId, string Scope, int InvoiceCount, decimal Total, string Description);

public sealed record GetPOSEntriesReportQuery(DateOnly From, DateOnly To, long? BranchId = null) : IRequest<IReadOnlyList<POSEntryRow>>;

public sealed class GetPOSEntriesReportQueryHandler(IApplicationDbContext db) : IRequestHandler<GetPOSEntriesReportQuery, IReadOnlyList<POSEntryRow>>
{
    public async Task<IReadOnlyList<POSEntryRow>> Handle(GetPOSEntriesReportQuery request, CancellationToken cancellationToken)
    {
        var entries = await db.JournalEntries.AsNoTracking()
            .Where(e => e.SourceModule == SourceModule.POS && e.EntryDate >= request.From && e.EntryDate <= request.To)
            .Where(e => request.BranchId == null || e.BranchId == request.BranchId)
            .OrderByDescending(e => e.EntryDate).ThenByDescending(e => e.Id)
            .Select(e => new { e.Id, e.EntryNumber, e.EntryDate, e.BranchId, e.SourceDocumentType, e.TotalDebit, e.Description })
            .Take(2000)
            .ToListAsync(cancellationToken);

        var ids = entries.Select(e => e.Id).ToList();
        var invoiceCounts = await db.POSInvoices.AsNoTracking()
            .Where(i => i.JournalEntryId != null && ids.Contains(i.JournalEntryId.Value))
            .GroupBy(i => i.JournalEntryId!.Value)
            .Select(g => new { g.Key, Count = g.Count() })
            .ToDictionaryAsync(g => g.Key, g => g.Count, cancellationToken);

        return entries.Select(e => new POSEntryRow(
            e.Id, e.EntryNumber, e.EntryDate, e.BranchId, e.SourceDocumentType?.ToString() ?? "-",
            invoiceCounts.GetValueOrDefault(e.Id), e.TotalDebit, e.Description)).ToList();
    }
}

// ---------------------------------------------------------------------------- 5. shift variances

public sealed record ShiftVarianceRow(
    long ShiftId, long? BranchId, long POSTerminalId, long CashierUserId, DateTime? ClosedAtUtc, string Status,
    decimal Expected, decimal Actual, decimal Difference, decimal Threshold, string Classification, string? VarianceEntryNumber);

/// <summary>Rule 20's split made visible: which shortages the company absorbed and which the cashier owes.</summary>
public sealed record GetShiftVarianceReportQuery(DateOnly From, DateOnly To, long? BranchId = null) : IRequest<IReadOnlyList<ShiftVarianceRow>>;

public sealed class GetShiftVarianceReportQueryHandler(IApplicationDbContext db)
    : IRequestHandler<GetShiftVarianceReportQuery, IReadOnlyList<ShiftVarianceRow>>
{
    public async Task<IReadOnlyList<ShiftVarianceRow>> Handle(GetShiftVarianceReportQuery request, CancellationToken cancellationToken)
    {
        var from = request.From.ToDateTime(TimeOnly.MinValue);
        var to = request.To.ToDateTime(TimeOnly.MaxValue);

        var shifts = await db.Shifts.AsNoTracking()
            .Where(s => s.ClosedAtUtc != null && s.ClosedAtUtc >= from && s.ClosedAtUtc <= to && s.DifferenceAmount != null && s.DifferenceAmount != 0)
            .Where(s => request.BranchId == null || s.BranchId == request.BranchId)
            .OrderByDescending(s => s.ClosedAtUtc)
            .Select(s => new
            {
                s.Id, s.BranchId, s.POSTerminalId, s.CashierUserId, s.ClosedAtUtc, s.Status, s.ExpectedClosingCashAmount,
                s.ActualClosingCashAmount, s.DifferenceAmount,
                Entry = s.VarianceJournalEntry != null ? s.VarianceJournalEntry.EntryNumber : null
            })
            .ToListAsync(cancellationToken);

        var thresholds = await db.BranchPOSSettingsRows.AsNoTracking()
            .ToDictionaryAsync(s => s.BranchId ?? 0, s => s.ShiftVarianceEmployeeLiabilityThreshold, cancellationToken);
        var fallback = new BranchPOSSettings().ShiftVarianceEmployeeLiabilityThreshold;

        return shifts.Select(s =>
        {
            var threshold = thresholds.GetValueOrDefault(s.BranchId ?? 0, fallback);
            var difference = s.DifferenceAmount!.Value;
            var classification = difference > 0 ? "Surplus" : -difference <= threshold ? "CompanyShortage" : "CashierShortage";
            return new ShiftVarianceRow(
                s.Id, s.BranchId, s.POSTerminalId, s.CashierUserId, s.ClosedAtUtc, s.Status.ToString(),
                s.ExpectedClosingCashAmount ?? 0m, s.ActualClosingCashAmount ?? 0m, difference, threshold, classification, s.Entry);
        }).ToList();
    }
}

// ---------------------------------------------------------------------------- 6. periods

public sealed record PeriodStatusRow(long Id, DateOnly PeriodStart, DateOnly PeriodEnd, string Status, DateTime? ClosedAtUtc, int PostedEntries, int AutoEntries);

public sealed record GetPeriodStatusReportQuery : IRequest<IReadOnlyList<PeriodStatusRow>>;

public sealed class GetPeriodStatusReportQueryHandler(IApplicationDbContext db) : IRequestHandler<GetPeriodStatusReportQuery, IReadOnlyList<PeriodStatusRow>>
{
    public async Task<IReadOnlyList<PeriodStatusRow>> Handle(GetPeriodStatusReportQuery request, CancellationToken cancellationToken)
    {
        var periods = await db.AccountingPeriods.AsNoTracking().OrderByDescending(p => p.PeriodStart).ToListAsync(cancellationToken);
        var result = new List<PeriodStatusRow>();
        foreach (var p in periods)
        {
            var entries = db.JournalEntries.AsNoTracking()
                .Where(e => e.Status == JournalEntryStatus.Posted && e.EntryDate >= p.PeriodStart && e.EntryDate <= p.PeriodEnd);
            result.Add(new PeriodStatusRow(
                p.Id, p.PeriodStart, p.PeriodEnd, p.Status.ToString(), p.ClosedAtUtc,
                await entries.CountAsync(cancellationToken), await entries.CountAsync(e => e.IsAutoGenerated, cancellationToken)));
        }
        return result;
    }
}

// ---------------------------------------------------------------------------- 7. integrity

public sealed record IntegrityIssueRow(long EntryId, string EntryNumber, DateOnly EntryDate, string Issue, decimal HeaderDebit, decimal HeaderCredit, decimal LinesDebit, decimal LinesCredit);

/// <summary>
/// Entries whose totals do not hold together: unbalanced, or whose header disagrees with its lines.
/// IPostingService refuses to create either, so anything listed here got in some other way.
/// </summary>
public sealed record GetEntryIntegrityReportQuery : IRequest<IReadOnlyList<IntegrityIssueRow>>;

public sealed class GetEntryIntegrityReportQueryHandler(IApplicationDbContext db) : IRequestHandler<GetEntryIntegrityReportQuery, IReadOnlyList<IntegrityIssueRow>>
{
    public async Task<IReadOnlyList<IntegrityIssueRow>> Handle(GetEntryIntegrityReportQuery request, CancellationToken cancellationToken)
    {
        var rows = await db.JournalEntries.AsNoTracking()
            .Where(e => e.Status == JournalEntryStatus.Posted)
            .Select(e => new
            {
                e.Id, e.EntryNumber, e.EntryDate, e.TotalDebit, e.TotalCredit,
                LinesDebit = e.Lines.Sum(l => l.DebitAmount), LinesCredit = e.Lines.Sum(l => l.CreditAmount)
            })
            .Where(e => e.TotalDebit != e.TotalCredit || e.LinesDebit != e.LinesCredit || e.LinesDebit != e.TotalDebit)
            .Take(1000)
            .ToListAsync(cancellationToken);

        return rows.Select(e => new IntegrityIssueRow(
            e.Id, e.EntryNumber, e.EntryDate,
            e.LinesDebit != e.LinesCredit ? "Unbalanced" : "HeaderMismatch",
            e.TotalDebit, e.TotalCredit, e.LinesDebit, e.LinesCredit)).ToList();
    }
}

// ---------------------------------------------------------------------------- 8. template usage

public sealed record TemplateUsageRow(
    long TemplateId, string ScreenCode, string ScreenNameAr, string TemplateNameAr, int VersionNumber, bool IsCurrentVersion,
    bool IsActive, int EntryCount, DateTime? LastUsedAtUtc);

public sealed record GetTemplateUsageReportQuery : IRequest<IReadOnlyList<TemplateUsageRow>>;

public sealed class GetTemplateUsageReportQueryHandler(IApplicationDbContext db) : IRequestHandler<GetTemplateUsageReportQuery, IReadOnlyList<TemplateUsageRow>>
{
    public async Task<IReadOnlyList<TemplateUsageRow>> Handle(GetTemplateUsageReportQuery request, CancellationToken cancellationToken)
    {
        var usage = await db.JournalEntryTemplateSnapshots.AsNoTracking()
            .GroupBy(s => s.PostingTemplateId)
            .Select(g => new { g.Key, Count = g.Count(), Last = g.Max(s => s.CreatedAtUtc) })
            .ToDictionaryAsync(g => g.Key, cancellationToken);

        var templates = await db.PostingTemplates.AsNoTracking()
            .OrderBy(t => t.ScreenCode).ThenBy(t => t.ExecutionOrder).ThenBy(t => t.FamilyId).ThenByDescending(t => t.VersionNumber)
            .ToListAsync(cancellationToken);

        return templates.Select(t => new TemplateUsageRow(
            t.Id, t.ScreenCode, PostingScreenCatalog.Find(t.ScreenCode)?.NameAr ?? t.ScreenCode, t.NameAr, t.VersionNumber,
            t.IsCurrentVersion, t.IsActive, usage.GetValueOrDefault(t.Id)?.Count ?? 0, usage.GetValueOrDefault(t.Id)?.Last)).ToList();
    }
}

// ---------------------------------------------------------------------------- 9. documents without an entry

public sealed record UnpostedDocumentsRow(string ScreenCode, string ScreenNameAr, bool IsConfigured, int WithoutEntry, int WithoutEntrySinceActivation);

/// <summary>
/// Final documents that carry no entry, per screen. Before a screen's template is switched on this
/// is expected (they predate accounting); after it, every one is a gap to chase — that second number
/// is the one that should always read zero.
/// </summary>
public sealed record GetUnpostedDocumentsReportQuery : IRequest<IReadOnlyList<UnpostedDocumentsRow>>;

public sealed class GetUnpostedDocumentsReportQueryHandler(IApplicationDbContext db)
    : IRequestHandler<GetUnpostedDocumentsReportQuery, IReadOnlyList<UnpostedDocumentsRow>>
{
    public async Task<IReadOnlyList<UnpostedDocumentsRow>> Handle(GetUnpostedDocumentsReportQuery request, CancellationToken cancellationToken)
    {
        // Earliest moment each screen had an active template: activation is recorded as the
        // template's last update (switching on) or its creation, whichever applies.
        var activeSince = await db.PostingTemplates.AsNoTracking()
            .Where(t => t.IsActive && t.IsCurrentVersion)
            .GroupBy(t => t.ScreenCode)
            .Select(g => new { g.Key, Since = g.Min(t => t.UpdatedAtUtc > t.CreatedAtUtc ? t.UpdatedAtUtc : t.CreatedAtUtc) })
            .ToDictionaryAsync(g => g.Key, g => g.Since, cancellationToken);

        IQueryable<DateTime> UnpostedWarehouseDocuments(WarehouseDocumentType type) =>
            db.WarehouseDocuments
                .Where(d => d.JournalEntryId == null && d.Status == WarehouseDocumentStatus.Posted && d.DocumentType == type)
                .Select(d => d.UpdatedAtUtc);

        async Task<UnpostedDocumentsRow> Row(string screen, IQueryable<DateTime> createdAtOfUnposted)
        {
            var total = await createdAtOfUnposted.CountAsync(cancellationToken);
            var configured = activeSince.TryGetValue(screen, out var since);
            var afterActivation = configured ? await createdAtOfUnposted.CountAsync(c => c >= since, cancellationToken) : 0;
            return new UnpostedDocumentsRow(screen, PostingScreenCatalog.Find(screen)!.NameAr, configured, total, afterActivation);
        }

        return
        [
            await Row(PostingScreenCatalog.PurchaseInvoice, db.PurchaseInvoices.Where(i =>
                i.JournalEntryId == null && i.Status != PurchaseInvoiceStatus.Draft && i.Status != PurchaseInvoiceStatus.PendingApproval
                && i.Status != PurchaseInvoiceStatus.Rejected && i.Status != PurchaseInvoiceStatus.Cancelled).Select(i => i.UpdatedAtUtc)),
            await Row(PostingScreenCatalog.PurchaseReturn, db.PurchaseReturns.Where(r => r.JournalEntryId == null && r.Status == PurchaseReturnStatus.Posted).Select(r => r.UpdatedAtUtc)),
            await Row(PostingScreenCatalog.SalesInvoice, db.SalesInvoices.Where(i => i.JournalEntryId == null && i.Status == SalesInvoiceStatus.Posted).Select(i => i.UpdatedAtUtc)),
            await Row(PostingScreenCatalog.DeliveryOrder, db.DeliveryOrders.Where(d => d.JournalEntryId == null && d.Status == DeliveryOrderStatus.Posted).Select(d => d.UpdatedAtUtc)),
            await Row(PostingScreenCatalog.SalesReturn, db.SalesReturns.Where(r => r.JournalEntryId == null && r.Status == SalesReturnStatus.Posted).Select(r => r.UpdatedAtUtc)),
            await Row(PostingScreenCatalog.PosInvoice, db.POSInvoices.Where(i => i.JournalEntryId == null && i.Status == POSInvoiceStatus.Posted).Select(i => i.CreatedAtUtc)),
            await Row(PostingScreenCatalog.PosReturn, db.POSReturns.Where(r => r.JournalEntryId == null).Select(r => r.CreatedAtUtc)),
            await Row(PostingScreenCatalog.PosShiftVariance, db.Shifts.Where(s =>
                s.VarianceJournalEntryId == null && s.Status == ShiftStatus.Closed && s.DifferenceAmount != null && s.DifferenceAmount != 0).Select(s => s.UpdatedAtUtc)),
            await Row(PostingScreenCatalog.PosDrawerExpense, db.DrawerExpenses.Where(e => e.JournalEntryId == null).Select(e => e.CreatedAtUtc)),
            await Row(PostingScreenCatalog.StockIn, UnpostedWarehouseDocuments(WarehouseDocumentType.StockIn)),
            await Row(PostingScreenCatalog.StockOut, UnpostedWarehouseDocuments(WarehouseDocumentType.StockOut)),
            await Row(PostingScreenCatalog.OpeningBalance, UnpostedWarehouseDocuments(WarehouseDocumentType.OpeningBalance)),
            // A count's own adjustment document posts under the count (INVENTORY_COUNT) and is counted
            // there; CloseInventoryCountCommand marks it with this note, the only trace it leaves.
            await Row(PostingScreenCatalog.InventoryAdjustment, db.WarehouseDocuments
                .Where(d => d.JournalEntryId == null && d.Status == WarehouseDocumentStatus.Posted
                    && d.DocumentType == WarehouseDocumentType.InventoryAdjustment
                    && (d.Notes == null || !d.Notes.StartsWith("إقفال جرد")))
                .Select(d => d.UpdatedAtUtc)),
            await Row(PostingScreenCatalog.InventoryCount, db.InventoryCounts.Where(c =>
                c.JournalEntryId == null && c.Status == InventoryCountStatus.Closed
                && c.Lines.Any(l => l.SettlementDecision == SettlementDecision.Approved && l.VarianceQuantity != null && l.VarianceQuantity != 0))
                .Select(c => c.UpdatedAtUtc)),
            await Row(PostingScreenCatalog.Waste, db.WasteRecords.Where(w => w.JournalEntryId == null).Select(w => w.CreatedAtUtc))
        ];
    }
}
