using Habbak.ERP.Application.Common.Exceptions;
using Habbak.ERP.Application.Common.Models;
using Habbak.ERP.Domain.Accounting;
using Habbak.ERP.Domain.Organization;
using Habbak.ERP.Infrastructure.Services;
using Habbak.ERP.Shared.Enums;
using Microsoft.EntityFrameworkCore;
using Xunit;

namespace Habbak.ERP.IntegrationTests;

/// <summary>
/// Integration tests for the central posting engine (01-Module-Accounting.md, section 3) —
/// mandatory per 00-Project-Overview.md, section 25: "any change to the posting engine must
/// not be merged without integration tests covering it." Each test uses its own CompanyId so
/// tests sharing the one LocalDB instance from the fixture never collide on unique indexes.
/// </summary>
public class PostingServiceTests(PostingServiceFixture fixture) : IClassFixture<PostingServiceFixture>
{
    private static long NewCompanyId() => Random.Shared.NextInt64(1, long.MaxValue);

    private sealed record Seed(long CashAccountId, long ExpenseAccountId, long DimensionId, long DimensionValueId,
        long OtherDimensionId, long OtherDimensionValueId);

    private async Task<Seed> SeedChartOfAccountsAsync(long companyId)
    {
        await using var db = fixture.CreateContext(new TestCurrentCompanyContext(companyId));

        var cash = new Account
        {
            CompanyId = companyId, Code = "1-1-01", NameAr = "الخزينة", NameEn = "Cash",
            AccountType = AccountType.Asset, Nature = AccountNature.Debit, IsPostable = true, IsActive = true
        };
        var expense = new Account
        {
            CompanyId = companyId, Code = "5-1-01", NameAr = "مصروفات عمومية", NameEn = "General Expenses",
            AccountType = AccountType.Expense, Nature = AccountNature.Debit, IsPostable = true, IsActive = true
        };
        var group = new Account
        {
            CompanyId = companyId, Code = "5", NameAr = "المصروفات", NameEn = "Expenses",
            AccountType = AccountType.Expense, Nature = AccountNature.Debit, IsPostable = false, IsActive = true
        };
        db.Accounts.AddRange(cash, expense, group);
        await db.SaveChangesAsync();

        var dimension = new CostCenterDimension
        {
            CompanyId = companyId, Code = CostCenterDimensionCodes.CostCenter, NameAr = "مركز التكلفة", NameEn = "Cost Center", IsActive = true
        };
        var otherDimension = new CostCenterDimension
        {
            CompanyId = companyId, Code = "SALES_CHANNEL", NameAr = "نوع المبيعات", NameEn = "Sales Channel", IsActive = true
        };
        db.CostCenterDimensions.AddRange(dimension, otherDimension);
        await db.SaveChangesAsync();

        var dimensionValue = new CostCenterDimensionValue
        {
            CostCenterDimensionId = dimension.Id, Code = "ADMIN", NameAr = "الإدارة العامة", NameEn = "Head Office"
        };
        var otherDimensionValue = new CostCenterDimensionValue
        {
            CostCenterDimensionId = otherDimension.Id, Code = "DINE_IN", NameAr = "صالة", NameEn = "Dine In"
        };
        db.CostCenterDimensionValues.AddRange(dimensionValue, otherDimensionValue);
        await db.SaveChangesAsync();

        db.AccountDimensionLinks.Add(new AccountDimensionLink
        {
            AccountId = expense.Id, CostCenterDimensionId = dimension.Id, DisplayOrder = 1, IsMandatory = true
        });
        await db.SaveChangesAsync();

        return new Seed(cash.Id, expense.Id, dimension.Id, dimensionValue.Id, otherDimension.Id, otherDimensionValue.Id);
    }

    private static PostingRequest BuildBalancedRequest(long companyId, Seed seed, DateOnly entryDate, long dimensionValueId)
    {
        var dimensionValues = new Dictionary<long, long> { [seed.DimensionId] = dimensionValueId };

        return new PostingRequest
        {
            CompanyId = companyId,
            EntryDate = entryDate,
            Description = "شراء أدوات مكتبية",
            SourceModule = SourceModule.Manual,
            IsAutoGenerated = false,
            Lines =
            [
                new PostingLineRequest
                {
                    AccountId = seed.ExpenseAccountId, DebitAmount = 100m, CreditAmount = 0m,
                    CurrencyCode = "EGP", ExchangeRate = 1m, BaseCurrencyDebitAmount = 100m, BaseCurrencyCreditAmount = 0m,
                    DimensionValues = dimensionValues
                },
                new PostingLineRequest
                {
                    AccountId = seed.CashAccountId, DebitAmount = 0m, CreditAmount = 100m,
                    CurrencyCode = "EGP", ExchangeRate = 1m, BaseCurrencyDebitAmount = 0m, BaseCurrencyCreditAmount = 100m
                }
            ]
        };
    }

    private sealed record BranchDimensionSeed(
        long ExpenseAccountId, long CashAccountId, long BranchDimensionId, long BranchId, string BranchNameAr);

    /// <summary>
    /// Bug-001: an expense account with a mandatory dimension whose CostCenterDimension is
    /// Branch-linked (LinkedEntityType.Branch), plus a Branch and — unless
    /// <paramref name="withMirroredValue"/> is false — the CostCenterDimensionValue
    /// BranchDimensionSync would already have mirrored for it.
    /// </summary>
    private async Task<BranchDimensionSeed> SeedBranchMandatoryDimensionAsync(long companyId, bool withMirroredValue = true)
    {
        await using var db = fixture.CreateContext(new TestCurrentCompanyContext(companyId));

        var cash = new Account
        {
            CompanyId = companyId, Code = "1-1-01", NameAr = "الخزينة", NameEn = "Cash",
            AccountType = AccountType.Asset, Nature = AccountNature.Debit, IsPostable = true, IsActive = true
        };
        var expense = new Account
        {
            CompanyId = companyId, Code = "5-1-01", NameAr = "مصروفات عمومية", NameEn = "General Expenses",
            AccountType = AccountType.Expense, Nature = AccountNature.Debit, IsPostable = true, IsActive = true
        };
        db.Accounts.AddRange(cash, expense);
        await db.SaveChangesAsync();

        var branch = new Branch { CompanyId = companyId, Code = "MAIN", NameAr = "الفرع الرئيسي", NameEn = "Main Branch", IsActive = true };
        db.Branches.Add(branch);
        await db.SaveChangesAsync();

        var branchDimension = new CostCenterDimension
        {
            CompanyId = companyId, Code = "BRANCH", NameAr = "الفروع", NameEn = "Branches",
            IsActive = true, LinkedEntityType = CostCenterLinkedEntityType.Branch
        };
        db.CostCenterDimensions.Add(branchDimension);
        await db.SaveChangesAsync();

        db.AccountDimensionLinks.Add(new AccountDimensionLink
        {
            AccountId = expense.Id, CostCenterDimensionId = branchDimension.Id, DisplayOrder = 1, IsMandatory = true
        });
        await db.SaveChangesAsync();

        if (withMirroredValue)
        {
            // What BranchDimensionSync would already have created on Branch create/update.
            db.CostCenterDimensionValues.Add(new CostCenterDimensionValue
            {
                CostCenterDimensionId = branchDimension.Id, Code = branch.Code, NameAr = branch.NameAr, NameEn = branch.NameEn, IsActive = true
            });
            await db.SaveChangesAsync();
        }

        return new BranchDimensionSeed(expense.Id, cash.Id, branchDimension.Id, branch.Id, branch.NameAr);
    }

    [Fact]
    public async Task PostAsync_WithBranchIdAndMandatoryBranchDimension_AutoResolvesAndPosts()
    {
        var companyId = NewCompanyId();
        var seed = await SeedBranchMandatoryDimensionAsync(companyId);
        await using var db = fixture.CreateContext(new TestCurrentCompanyContext(companyId));
        var sut = new PostingService(db, new Habbak.ERP.Application.Approvals.Services.ApprovalWorkflowService(db, new Habbak.ERP.Application.Approvals.Services.ApprovalStepResolutionService(db), new Habbak.ERP.Application.Notifications.NotificationService(db, new TestCurrentCompanyContext(companyId))), new JournalEntryNumberGenerator(new CodeGenerator(db, new TestCurrentCompanyContext(companyId))));

        var request = new PostingRequest
        {
            CompanyId = companyId,
            BranchId = seed.BranchId,
            EntryDate = new DateOnly(2026, 8, 15),
            Description = "سند صرف بدون تحديد بُعد يدويًا",
            SourceModule = SourceModule.Manual,
            IsAutoGenerated = false,
            Lines =
            [
                new PostingLineRequest
                {
                    AccountId = seed.ExpenseAccountId, DebitAmount = 100m, CreditAmount = 0m,
                    CurrencyCode = "EGP", ExchangeRate = 1m, BaseCurrencyDebitAmount = 100m, BaseCurrencyCreditAmount = 0m
                    // No DimensionValues — must be auto-resolved from BranchId.
                },
                new PostingLineRequest
                {
                    AccountId = seed.CashAccountId, DebitAmount = 0m, CreditAmount = 100m,
                    CurrencyCode = "EGP", ExchangeRate = 1m, BaseCurrencyDebitAmount = 0m, BaseCurrencyCreditAmount = 100m
                }
            ]
        };

        var result = await sut.PostAsync(request);
        await db.SaveChangesAsync();

        Assert.Equal(JournalEntryStatus.Posted, result.Status);
        var expenseLine = result.JournalEntry.Lines.Single(l => l.AccountId == seed.ExpenseAccountId);
        var resolvedDimension = Assert.Single(expenseLine.DimensionValues);
        Assert.Equal(seed.BranchDimensionId, resolvedDimension.CostCenterDimensionId);
    }

    [Fact]
    public async Task PostAsync_MandatoryBranchDimensionButNoBranchId_ThrowsNoBranchOnDocument()
    {
        var companyId = NewCompanyId();
        var seed = await SeedBranchMandatoryDimensionAsync(companyId);
        await using var db = fixture.CreateContext(new TestCurrentCompanyContext(companyId));
        var sut = new PostingService(db, new Habbak.ERP.Application.Approvals.Services.ApprovalWorkflowService(db, new Habbak.ERP.Application.Approvals.Services.ApprovalStepResolutionService(db), new Habbak.ERP.Application.Notifications.NotificationService(db, new TestCurrentCompanyContext(companyId))), new JournalEntryNumberGenerator(new CodeGenerator(db, new TestCurrentCompanyContext(companyId))));

        var request = new PostingRequest
        {
            CompanyId = companyId,
            // BranchId deliberately omitted.
            EntryDate = new DateOnly(2026, 8, 15),
            Description = "سند بدون فرع",
            SourceModule = SourceModule.Manual,
            IsAutoGenerated = false,
            Lines =
            [
                new PostingLineRequest
                {
                    AccountId = seed.ExpenseAccountId, DebitAmount = 100m, CreditAmount = 0m,
                    CurrencyCode = "EGP", ExchangeRate = 1m, BaseCurrencyDebitAmount = 100m, BaseCurrencyCreditAmount = 0m
                },
                new PostingLineRequest
                {
                    AccountId = seed.CashAccountId, DebitAmount = 0m, CreditAmount = 100m,
                    CurrencyCode = "EGP", ExchangeRate = 1m, BaseCurrencyDebitAmount = 0m, BaseCurrencyCreditAmount = 100m
                }
            ]
        };

        var ex = await Assert.ThrowsAsync<PostingValidationException>(() => sut.PostAsync(request));
        Assert.Contains(ex.Errors, e => e.Code == "ACC-R3-NO-BRANCH-ON-DOCUMENT");
    }

    [Fact]
    public async Task PostAsync_MandatoryBranchDimensionButBranchHasNoValue_ThrowsBranchDimensionUnresolved()
    {
        var companyId = NewCompanyId();
        var seed = await SeedBranchMandatoryDimensionAsync(companyId, withMirroredValue: false);
        await using var db = fixture.CreateContext(new TestCurrentCompanyContext(companyId));
        var sut = new PostingService(db, new Habbak.ERP.Application.Approvals.Services.ApprovalWorkflowService(db, new Habbak.ERP.Application.Approvals.Services.ApprovalStepResolutionService(db), new Habbak.ERP.Application.Notifications.NotificationService(db, new TestCurrentCompanyContext(companyId))), new JournalEntryNumberGenerator(new CodeGenerator(db, new TestCurrentCompanyContext(companyId))));

        var request = new PostingRequest
        {
            CompanyId = companyId,
            BranchId = seed.BranchId,
            EntryDate = new DateOnly(2026, 8, 15),
            Description = "سند لفرع مالوش قيمة بُعد بعد",
            SourceModule = SourceModule.Manual,
            IsAutoGenerated = false,
            Lines =
            [
                new PostingLineRequest
                {
                    AccountId = seed.ExpenseAccountId, DebitAmount = 100m, CreditAmount = 0m,
                    CurrencyCode = "EGP", ExchangeRate = 1m, BaseCurrencyDebitAmount = 100m, BaseCurrencyCreditAmount = 0m
                },
                new PostingLineRequest
                {
                    AccountId = seed.CashAccountId, DebitAmount = 0m, CreditAmount = 100m,
                    CurrencyCode = "EGP", ExchangeRate = 1m, BaseCurrencyDebitAmount = 0m, BaseCurrencyCreditAmount = 100m
                }
            ]
        };

        var ex = await Assert.ThrowsAsync<PostingValidationException>(() => sut.PostAsync(request));
        Assert.Contains(ex.Errors, e => e.Code == "ACC-R3-BRANCH-DIMENSION-UNRESOLVED");
    }

    [Fact]
    public async Task PostDraftEntryAsync_ManualEntryWithBranchIdAndMandatoryBranchDimension_AutoResolvesAndPosts()
    {
        var companyId = NewCompanyId();
        var seed = await SeedBranchMandatoryDimensionAsync(companyId);

        long entryId;
        await using (var seedDb = fixture.CreateContext(new TestCurrentCompanyContext(companyId)))
        {
            var draft = new JournalEntry
            {
                CompanyId = companyId, BranchId = seed.BranchId, EntryNumber = "JV-2026-88888",
                EntryDate = new DateOnly(2026, 8, 15), Description = "قيد يدوي بدون بُعد",
                SourceModule = SourceModule.Manual, IsAutoGenerated = false, Status = JournalEntryStatus.Draft
            };
            draft.Lines.Add(new JournalEntryLine
            {
                LineNumber = 1, AccountId = seed.ExpenseAccountId, DebitAmount = 100m, CreditAmount = 0m,
                CurrencyCode = "EGP", ExchangeRate = 1m, BaseCurrencyDebitAmount = 100m, BaseCurrencyCreditAmount = 0m
            });
            draft.Lines.Add(new JournalEntryLine
            {
                LineNumber = 2, AccountId = seed.CashAccountId, DebitAmount = 0m, CreditAmount = 100m,
                CurrencyCode = "EGP", ExchangeRate = 1m, BaseCurrencyDebitAmount = 0m, BaseCurrencyCreditAmount = 100m
            });
            seedDb.JournalEntries.Add(draft);
            await seedDb.SaveChangesAsync();
            entryId = draft.Id;
        }

        await using var db = fixture.CreateContext(new TestCurrentCompanyContext(companyId));
        var sut = new PostingService(db, new Habbak.ERP.Application.Approvals.Services.ApprovalWorkflowService(db, new Habbak.ERP.Application.Approvals.Services.ApprovalStepResolutionService(db), new Habbak.ERP.Application.Notifications.NotificationService(db, new TestCurrentCompanyContext(companyId))), new JournalEntryNumberGenerator(new CodeGenerator(db, new TestCurrentCompanyContext(companyId))));

        var result = await sut.PostDraftEntryAsync(entryId);
        await db.SaveChangesAsync();

        Assert.Equal(JournalEntryStatus.Posted, result.Status);

        await using var verifyDb = fixture.CreateContext(new TestCurrentCompanyContext(companyId));
        var expenseLine = await verifyDb.JournalEntryLines
            .Include(l => l.DimensionValues)
            .SingleAsync(l => l.JournalEntryId == entryId && l.AccountId == seed.ExpenseAccountId);
        var resolvedDimension = Assert.Single(expenseLine.DimensionValues);
        Assert.Equal(seed.BranchDimensionId, resolvedDimension.CostCenterDimensionId);
    }

    [Fact]
    public async Task PostAsync_WithBalancedEntryAndRequiredDimension_PostsDirectly()
    {
        var companyId = NewCompanyId();
        var seed = await SeedChartOfAccountsAsync(companyId);
        await using var db = fixture.CreateContext(new TestCurrentCompanyContext(companyId));
        var sut = new PostingService(db, new Habbak.ERP.Application.Approvals.Services.ApprovalWorkflowService(db, new Habbak.ERP.Application.Approvals.Services.ApprovalStepResolutionService(db), new Habbak.ERP.Application.Notifications.NotificationService(db, new TestCurrentCompanyContext(companyId))), new JournalEntryNumberGenerator(new CodeGenerator(db, new TestCurrentCompanyContext(companyId))));

        var request = BuildBalancedRequest(companyId, seed, new DateOnly(2026, 8, 15), seed.DimensionValueId);
        var result = await sut.PostAsync(request);
        await db.SaveChangesAsync();

        Assert.Equal(JournalEntryStatus.Posted, result.Status);
        Assert.NotNull(result.JournalEntry.PostedAtUtc);
        Assert.Equal(100m, result.JournalEntry.TotalDebit);
        Assert.Equal(100m, result.JournalEntry.TotalCredit);
        Assert.StartsWith("JV-", result.JournalEntry.EntryNumber);
    }

    [Fact]
    public async Task PostAsync_WithUnbalancedEntry_ThrowsRule1()
    {
        var companyId = NewCompanyId();
        var seed = await SeedChartOfAccountsAsync(companyId);
        await using var db = fixture.CreateContext(new TestCurrentCompanyContext(companyId));
        var sut = new PostingService(db, new Habbak.ERP.Application.Approvals.Services.ApprovalWorkflowService(db, new Habbak.ERP.Application.Approvals.Services.ApprovalStepResolutionService(db), new Habbak.ERP.Application.Notifications.NotificationService(db, new TestCurrentCompanyContext(companyId))), new JournalEntryNumberGenerator(new CodeGenerator(db, new TestCurrentCompanyContext(companyId))));

        var request = new PostingRequest
        {
            CompanyId = companyId,
            EntryDate = new DateOnly(2026, 8, 15),
            Description = "قيد غير متزن",
            SourceModule = SourceModule.Manual,
            IsAutoGenerated = false,
            Lines =
            [
                new PostingLineRequest
                {
                    AccountId = seed.ExpenseAccountId, DebitAmount = 100m, CreditAmount = 0m,
                    CurrencyCode = "EGP", ExchangeRate = 1m, BaseCurrencyDebitAmount = 100m, BaseCurrencyCreditAmount = 0m,
                    DimensionValues = new Dictionary<long, long> { [seed.DimensionId] = seed.DimensionValueId }
                },
                new PostingLineRequest
                {
                    AccountId = seed.CashAccountId, DebitAmount = 0m, CreditAmount = 50m,
                    CurrencyCode = "EGP", ExchangeRate = 1m, BaseCurrencyDebitAmount = 0m, BaseCurrencyCreditAmount = 50m
                }
            ]
        };

        var ex = await Assert.ThrowsAsync<PostingValidationException>(() => sut.PostAsync(request));
        Assert.Contains(ex.Errors, e => e.Code == "ACC-R1-UNBALANCED");
    }

    [Fact]
    public async Task PostAsync_ToNonPostableGroupAccount_ThrowsRule2()
    {
        var companyId = NewCompanyId();
        var seed = await SeedChartOfAccountsAsync(companyId);
        await using var db = fixture.CreateContext(new TestCurrentCompanyContext(companyId));
        var sut = new PostingService(db, new Habbak.ERP.Application.Approvals.Services.ApprovalWorkflowService(db, new Habbak.ERP.Application.Approvals.Services.ApprovalStepResolutionService(db), new Habbak.ERP.Application.Notifications.NotificationService(db, new TestCurrentCompanyContext(companyId))), new JournalEntryNumberGenerator(new CodeGenerator(db, new TestCurrentCompanyContext(companyId))));

        await using var lookupDb = fixture.CreateContext(new TestCurrentCompanyContext(companyId));
        var groupAccountId = (await lookupDb.Accounts.SingleAsync(a => a.Code == "5")).Id;

        var request = new PostingRequest
        {
            CompanyId = companyId,
            EntryDate = new DateOnly(2026, 8, 15),
            Description = "ترحيل خاطئ على حساب تجميعي",
            SourceModule = SourceModule.Manual,
            IsAutoGenerated = false,
            Lines =
            [
                new PostingLineRequest
                {
                    AccountId = groupAccountId, DebitAmount = 100m, CreditAmount = 0m,
                    CurrencyCode = "EGP", ExchangeRate = 1m, BaseCurrencyDebitAmount = 100m, BaseCurrencyCreditAmount = 0m
                },
                new PostingLineRequest
                {
                    AccountId = seed.CashAccountId, DebitAmount = 0m, CreditAmount = 100m,
                    CurrencyCode = "EGP", ExchangeRate = 1m, BaseCurrencyDebitAmount = 0m, BaseCurrencyCreditAmount = 100m
                }
            ]
        };

        var ex = await Assert.ThrowsAsync<PostingValidationException>(() => sut.PostAsync(request));
        Assert.Contains(ex.Errors, e => e.Code == "ACC-R2-NOT-POSTABLE");
    }

    [Fact]
    public async Task PostAsync_MissingMandatoryDimension_ThrowsRule3()
    {
        var companyId = NewCompanyId();
        var seed = await SeedChartOfAccountsAsync(companyId);
        await using var db = fixture.CreateContext(new TestCurrentCompanyContext(companyId));
        var sut = new PostingService(db, new Habbak.ERP.Application.Approvals.Services.ApprovalWorkflowService(db, new Habbak.ERP.Application.Approvals.Services.ApprovalStepResolutionService(db), new Habbak.ERP.Application.Notifications.NotificationService(db, new TestCurrentCompanyContext(companyId))), new JournalEntryNumberGenerator(new CodeGenerator(db, new TestCurrentCompanyContext(companyId))));

        var request = new PostingRequest
        {
            CompanyId = companyId,
            EntryDate = new DateOnly(2026, 8, 15),
            Description = "بدون تحديد مركز تكلفة",
            SourceModule = SourceModule.Manual,
            IsAutoGenerated = false,
            Lines =
            [
                new PostingLineRequest
                {
                    AccountId = seed.ExpenseAccountId, DebitAmount = 100m, CreditAmount = 0m,
                    CurrencyCode = "EGP", ExchangeRate = 1m, BaseCurrencyDebitAmount = 100m, BaseCurrencyCreditAmount = 0m
                    // No DimensionValues provided, even though the dimension is mandatory on this account.
                },
                new PostingLineRequest
                {
                    AccountId = seed.CashAccountId, DebitAmount = 0m, CreditAmount = 100m,
                    CurrencyCode = "EGP", ExchangeRate = 1m, BaseCurrencyDebitAmount = 0m, BaseCurrencyCreditAmount = 100m
                }
            ]
        };

        var ex = await Assert.ThrowsAsync<PostingValidationException>(() => sut.PostAsync(request));
        Assert.Contains(ex.Errors, e => e.Code == "ACC-R3-MISSING-DIMENSION");
    }

    [Fact]
    public async Task PostAsync_DimensionValueFromWrongDimension_ThrowsRule21()
    {
        var companyId = NewCompanyId();
        var seed = await SeedChartOfAccountsAsync(companyId);
        await using var db = fixture.CreateContext(new TestCurrentCompanyContext(companyId));
        var sut = new PostingService(db, new Habbak.ERP.Application.Approvals.Services.ApprovalWorkflowService(db, new Habbak.ERP.Application.Approvals.Services.ApprovalStepResolutionService(db), new Habbak.ERP.Application.Notifications.NotificationService(db, new TestCurrentCompanyContext(companyId))), new JournalEntryNumberGenerator(new CodeGenerator(db, new TestCurrentCompanyContext(companyId))));

        // Declares seed.DimensionId (Cost Center) but supplies a value that actually belongs to
        // the "Sales Channel" dimension — rule 21 must reject this mismatch.
        var request = BuildBalancedRequest(companyId, seed, new DateOnly(2026, 8, 15), seed.OtherDimensionValueId);

        var ex = await Assert.ThrowsAsync<PostingValidationException>(() => sut.PostAsync(request));
        Assert.Contains(ex.Errors, e => e.Code == "ACC-R21-DIMENSION-MISMATCH");
    }

    [Fact]
    public async Task PostAsync_IntoClosedPeriod_ThrowsRule9()
    {
        var companyId = NewCompanyId();
        var seed = await SeedChartOfAccountsAsync(companyId);

        var periodStart = new DateOnly(2026, 8, 1);
        var periodEnd = new DateOnly(2026, 8, 31);

        await using (var seedDb = fixture.CreateContext(new TestCurrentCompanyContext(companyId)))
        {
            seedDb.AccountingPeriods.Add(new AccountingPeriod
            {
                CompanyId = companyId, PeriodStart = periodStart, PeriodEnd = periodEnd,
                Status = AccountingPeriodStatus.Closed
            });
            await seedDb.SaveChangesAsync();
        }

        await using var db = fixture.CreateContext(new TestCurrentCompanyContext(companyId));
        var sut = new PostingService(db, new Habbak.ERP.Application.Approvals.Services.ApprovalWorkflowService(db, new Habbak.ERP.Application.Approvals.Services.ApprovalStepResolutionService(db), new Habbak.ERP.Application.Notifications.NotificationService(db, new TestCurrentCompanyContext(companyId))), new JournalEntryNumberGenerator(new CodeGenerator(db, new TestCurrentCompanyContext(companyId))));

        var request = BuildBalancedRequest(companyId, seed, new DateOnly(2026, 8, 15), seed.DimensionValueId);
        var ex = await Assert.ThrowsAsync<PostingValidationException>(() => sut.PostAsync(request));
        Assert.Contains(ex.Errors, e => e.Code == "ACC-R9-PERIOD-CLOSED");
    }

    [Fact]
    public async Task ReverseAsync_OfPostedEntry_CreatesDraftMirroredEntryWithSwappedAmounts()
    {
        var companyId = NewCompanyId();
        var seed = await SeedChartOfAccountsAsync(companyId);

        long originalEntryId;
        string originalEntryNumber;
        await using (var postDb = fixture.CreateContext(new TestCurrentCompanyContext(companyId)))
        {
            var postSut = new PostingService(postDb, new Habbak.ERP.Application.Approvals.Services.ApprovalWorkflowService(postDb, new Habbak.ERP.Application.Approvals.Services.ApprovalStepResolutionService(postDb), new Habbak.ERP.Application.Notifications.NotificationService(postDb, new TestCurrentCompanyContext(companyId))), new JournalEntryNumberGenerator(new CodeGenerator(postDb, new TestCurrentCompanyContext(companyId))));
            var request = BuildBalancedRequest(companyId, seed, new DateOnly(2026, 8, 15), seed.DimensionValueId);
            var posted = await postSut.PostAsync(request);
            await postDb.SaveChangesAsync();
            originalEntryId = posted.JournalEntry.Id;
            originalEntryNumber = posted.JournalEntry.EntryNumber;
        }

        await using var db = fixture.CreateContext(new TestCurrentCompanyContext(companyId));
        var sut = new PostingService(db, new Habbak.ERP.Application.Approvals.Services.ApprovalWorkflowService(db, new Habbak.ERP.Application.Approvals.Services.ApprovalStepResolutionService(db), new Habbak.ERP.Application.Notifications.NotificationService(db, new TestCurrentCompanyContext(companyId))), new JournalEntryNumberGenerator(new CodeGenerator(db, new TestCurrentCompanyContext(companyId))));

        var reversalResult = await sut.ReverseAsync(originalEntryId);
        await db.SaveChangesAsync();

        Assert.Equal(JournalEntryStatus.Draft, reversalResult.Status);
        Assert.Equal(originalEntryId, reversalResult.JournalEntry.ReversalOfEntryId);
        Assert.Contains($"عكس قيد رقم {originalEntryNumber}", reversalResult.JournalEntry.Description);
        Assert.Equal(100m, reversalResult.JournalEntry.TotalDebit);
        Assert.Equal(100m, reversalResult.JournalEntry.TotalCredit);

        var expenseLine = reversalResult.JournalEntry.Lines.Single(l => l.AccountId == seed.ExpenseAccountId);
        Assert.Equal(0m, expenseLine.DebitAmount);
        Assert.Equal(100m, expenseLine.CreditAmount);
    }

    [Fact]
    public async Task ReverseAsync_OfDraftEntry_Throws()
    {
        var companyId = NewCompanyId();
        var seed = await SeedChartOfAccountsAsync(companyId);

        await using var db = fixture.CreateContext(new TestCurrentCompanyContext(companyId));

        var draftEntry = new JournalEntry
        {
            CompanyId = companyId, EntryNumber = "JV-2026-99999", EntryDate = new DateOnly(2026, 8, 15),
            Description = "مسودة", SourceModule = SourceModule.Manual, IsAutoGenerated = false,
            Status = JournalEntryStatus.Draft
        };
        db.JournalEntries.Add(draftEntry);
        await db.SaveChangesAsync();

        var sut = new PostingService(db, new Habbak.ERP.Application.Approvals.Services.ApprovalWorkflowService(db, new Habbak.ERP.Application.Approvals.Services.ApprovalStepResolutionService(db), new Habbak.ERP.Application.Notifications.NotificationService(db, new TestCurrentCompanyContext(companyId))), new JournalEntryNumberGenerator(new CodeGenerator(db, new TestCurrentCompanyContext(companyId))));
        await Assert.ThrowsAsync<InvalidOperationException>(() => sut.ReverseAsync(draftEntry.Id));
    }
}
