using Habbak.ERP.Application.Common.Exceptions;
using Habbak.ERP.Application.Common.Interfaces;
using Habbak.ERP.Application.Common.Models;
using Habbak.ERP.Domain.Accounting;
using Habbak.ERP.Shared.Enums;
using MediatR;
using Microsoft.EntityFrameworkCore;

namespace Habbak.ERP.Application.Accounting.BankReconciliations.Commands.CompleteBankReconciliation;

/// <summary>
/// Rule 7: approving a bank reconciliation with a difference REQUIRES an adjustment entry —
/// there is no path that completes the run with AdjustmentAmount != 0 and no
/// AdjustmentJournalEntryId. When AdjustmentAmount is 0 no entry is posted at all.
/// </summary>
public sealed record CompleteBankReconciliationCommand(long RunId, decimal AdjustmentAmount, long? AdjustmentAccountId)
    : IRequest;

public sealed class CompleteBankReconciliationCommandHandler(IApplicationDbContext db, IPostingService postingService)
    : IRequestHandler<CompleteBankReconciliationCommand>
{
    public async Task Handle(CompleteBankReconciliationCommand request, CancellationToken cancellationToken)
    {
        var run = await db.BankReconciliationRuns
            .Include(r => r.BankAccount)
            .FirstOrDefaultAsync(r => r.Id == request.RunId, cancellationToken)
            ?? throw new NotFoundException(nameof(BankReconciliationRun), request.RunId);

        if (run.Status != BankReconciliationStatus.InProgress)
        {
            throw new BusinessRuleException("ACC-BANK-RECON-NOT-IN-PROGRESS", "المطابقة مكتملة بالفعل.");
        }

        if (request.AdjustmentAmount != 0)
        {
            if (request.AdjustmentAccountId is null)
            {
                throw new BusinessRuleException(
                    "ACC-R7-ADJUSTMENT-ACCOUNT-REQUIRED", "لازم تحديد حساب التسوية لأن هناك فرق يحتاج قيد تسوية.");
            }

            var isPositive = request.AdjustmentAmount > 0;
            var amount = Math.Abs(request.AdjustmentAmount);

            var postingRequest = new PostingRequest
            {
                CompanyId = run.BankAccount.CompanyId!.Value,
                EntryDate = run.PeriodTo,
                Description = $"قيد تسوية فرق مطابقة بنك رقم {run.Id}",
                SourceModule = SourceModule.Manual,
                IsAutoGenerated = true,
                Lines =
                [
                    new PostingLineRequest
                    {
                        AccountId = run.BankAccountId, DebitAmount = isPositive ? amount : 0m, CreditAmount = isPositive ? 0m : amount,
                        CurrencyCode = "EGP", ExchangeRate = 1m,
                        BaseCurrencyDebitAmount = isPositive ? amount : 0m, BaseCurrencyCreditAmount = isPositive ? 0m : amount
                    },
                    new PostingLineRequest
                    {
                        AccountId = request.AdjustmentAccountId.Value, DebitAmount = isPositive ? 0m : amount, CreditAmount = isPositive ? amount : 0m,
                        CurrencyCode = "EGP", ExchangeRate = 1m,
                        BaseCurrencyDebitAmount = isPositive ? 0m : amount, BaseCurrencyCreditAmount = isPositive ? amount : 0m
                    }
                ]
            };

            var result = await postingService.PostAsync(postingRequest, cancellationToken);
            run.AdjustmentJournalEntry = result.JournalEntry;
        }

        run.Status = BankReconciliationStatus.Completed;
        await db.SaveChangesAsync(cancellationToken);
    }
}
